// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package settings

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminPortalAccessOpenDetector.
func (*AdminPortalAccessOpenDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Admin Portal Access Not Restricted",
		Description: "Non-admin users can access the Azure AD admin portal. Restrict to prevent information disclosure.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/config/settings/admin-portal-access-open.go",
	}
}

// Doc returns catalog metadata for AppRegistrationOpenDetector.
func (*AppRegistrationOpenDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "App Registration Open to All Users",
		Description: "Any user can register applications. Restrict to reduce shadow IT.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/config/settings/app-registration-open.go",
	}
}

// Doc returns catalog metadata for LinkedInSyncEnabledDetector.
func (*LinkedInSyncEnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LinkedIn Account Synchronization Enabled",
		Description: "LinkedIn data synchronization is enabled. This shares organizational data with LinkedIn.",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/config/settings/linkedin-sync-enabled.go",
	}
}

// Doc returns catalog metadata for SelfServiceGroupsOpenDetector.
func (*SelfServiceGroupsOpenDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Self-Service Group Creation Open",
		Description: "Users can create M365 groups/teams without restrictions, leading to group sprawl.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/config/settings/self-service-groups-open.go",
	}
}

// Doc returns catalog metadata for UserConsentAllowAllDetector.
func (*UserConsentAllowAllDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "User Consent Allows All Applications",
		Description: "Users can consent to any application requesting permissions. This enables consent phishing.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/config/settings/user-consent-allow-all.go",
	}
}
