// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package monitoring

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AnonymousLdapAccessDetector.
func (*AnonymousLdapAccessDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Anonymous LDAP Access Allowed",
		Description: "LDAP server accepts anonymous binds. Attackers can enumerate AD objects (users, groups, computers) without valid credentials.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/monitoring/anonymous-ldap-access.go",
	}
}

// Doc returns catalog metadata for AuditPolicyWeakDetector.
func (*AuditPolicyWeakDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak Audit Policy Configuration",
		Description: "Critical audit categories are not configured for both Success and Failure, reducing visibility into security events.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/monitoring/audit-policy-weak.go",
	}
}

// Doc returns catalog metadata for PowershellLoggingDisabledDetector.
func (*PowershellLoggingDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PowerShell Logging Disabled",
		Description: "PowerShell Script Block Logging is not enabled, preventing detection of malicious PowerShell activity.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/monitoring/powershell-logging-disabled.go",
	}
}

// Doc returns catalog metadata for RecycleBinDisabledDetector.
func (*RecycleBinDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AD Recycle Bin Status Unknown",
		Description: "Unable to determine AD Recycle Bin status.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/advanced/monitoring/recycle-bin-disabled.go",
	}
}
