// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package mfa

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AllUsersDetector.
func (*AllUsersDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "MFA Not Enforced for All Users",
		Description: "No Conditional Access policy requires MFA for all users. MFA blocks 99.9% of automated attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/identity/mfa/mfa-not-enforced-all.go",
	}
}

// Doc returns catalog metadata for MFASuspiciousActivityDetector.
func (*MFASuspiciousActivityDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Suspicious MFA / sign-in activity pattern",
		Description: "Multiple Identity Protection signals (distinct source IPs, geographies, and/or high-risk events) correlate on the same user. This pattern is consistent with credential misuse or an in-progress MFA bypass attempt.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/mfa/mfa-suspicious-activity.go",
	}
}

// Doc returns catalog metadata for MFAUnusualLocationDetector.
func (*MFAUnusualLocationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "MFA sign-in from unusual geolocation",
		Description: "Identity Protection surfaced risky sign-ins from geographies outside the tenant's Named Locations. These may indicate credential theft or travel outside approved regions.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/mfa/mfa-unusual-location.go",
	}
}

// Doc returns catalog metadata for MfaNotEnforcedAdminsDetector.
func (*MfaNotEnforcedAdminsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "MFA Not Enforced for Administrators",
		Description: "No Conditional Access policy requires MFA for privileged directory roles. Administrative accounts without MFA are prime targets for credential attacks. This only recognizes the classic 'mfa' grant control; a policy that requires MFA through an authentication strength grant control instead is not currently detected (collector does not capture authenticationStrength on Conditional Access policies).",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/identity/mfa/mfa-not-enforced-admins.go",
	}
}

// Doc returns catalog metadata for NoFIDO2Detector.
func (*NoFIDO2Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "FIDO2 Security Keys Not Enabled Tenant-Wide",
		Description: "FIDO2 security keys are not enabled for all users. FIDO2 provides phishing-resistant authentication. A tenant-wide toggle without all_users coverage in includeTargets leaves most users without FIDO2 available.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/mfa/mfa-no-fido2.go",
	}
}

// Doc returns catalog metadata for NoPasswordlessDetector.
func (*NoPasswordlessDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Passwordless Authentication Not Confirmed",
		Description: "Neither FIDO2 (covering all users) nor Microsoft Authenticator is enabled. Passwordless methods eliminate password-based attack vectors. Note: an enabled Microsoft Authenticator method is not proof of passwordless capability - its per-group authentication mode (push-only vs. passwordless) is not currently collected, so this treats 'enabled' as a possible signal, not a confirmed one.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/mfa/mfa-no-passwordless.go",
	}
}

// Doc returns catalog metadata for NoStrongMethodDetector.
func (*NoStrongMethodDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Strong Authentication Method Configured",
		Description: "Neither Microsoft Authenticator nor FIDO2 security keys are enabled as authentication methods. SMS and voice are vulnerable to SIM-swapping.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/mfa/mfa-no-strong-method.go",
	}
}

// Doc returns catalog metadata for PhoneOnlyDetector.
func (*PhoneOnlyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Phone-Based MFA Methods Allowed Tenant-Wide (Policy)",
		Description: "The tenant's authentication methods policy allows phone-based methods (SMS, voice) while no stronger method (Microsoft Authenticator, FIDO2) is enabled. This checks the tenant-wide policy configuration, not any specific user's registered methods. Phone-based methods are vulnerable to SIM-swapping and social engineering attacks (NIST SP 800-63B-4 classifies SMS/voice OTP as a restricted authenticator for this reason).",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/mfa/mfa-phone-only.go",
	}
}
