// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package domainpolicy

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for FGPPNotConfiguredDetector.
func (*FGPPNotConfiguredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Fine-Grained Password Policy Not Configured",
		Description: "No Fine-Grained Password Policy (PSO) is configured. Privileged accounts (Tier 0) should have a dedicated FGPP with stricter requirements than the domain default policy.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/domain-policy/fgpp-not-configured.go",
	}
}

// Doc returns catalog metadata for MachineAccountQuotaAbuseDetector.
func (*MachineAccountQuotaAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Machine Account Quota Abuse",
		Description: "Unable to check machine account quota.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/domain-policy/machine-account-quota-abuse.go",
	}
}

// Doc returns catalog metadata for MachineAccountQuotaHighDetector.
func (*MachineAccountQuotaHighDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Machine Account Quota Elevated Above Default",
		Description: "Unable to check machine account quota.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/domain-policy/machine-account-quota-high.go",
	}
}

// Doc returns catalog metadata for WeakKerberosPolicyDetector.
func (*WeakKerberosPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak Kerberos Policy",
		Description: "Unable to check Kerberos policy.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/domain-policy/weak-kerberos-policy.go",
	}
}

// Doc returns catalog metadata for WeakPasswordPolicyDetector.
func (*WeakPasswordPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak Password Policy",
		Description: "Unable to check domain password policy.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/domain-policy/weak-password-policy.go",
	}
}
