// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package nist

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AC2AccountManagementDetector.
func (*AC2AccountManagementDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NIST AC-2 Account Management Non-Compliant",
		Description: "Account management practices do not fully meet NIST SP 800-53 AC-2 requirements.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/nist/ac2-account-management.go",
	}
}

// Doc returns catalog metadata for AC6LeastPrivilegeDetector.
func (*AC6LeastPrivilegeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NIST AC-6 Least Privilege Non-Compliant",
		Description: "Least privilege principles not fully implemented per NIST SP 800-53 AC-6 requirements.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/nist/ac6-least-privilege.go",
	}
}

// Doc returns catalog metadata for AU2AuditEventsDetector.
func (*AU2AuditEventsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NIST AU-2 Audit Events Non-Compliant",
		Description: "Audit event configuration does not meet NIST SP 800-53 AU-2 requirements for comprehensive event logging.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/nist/au2-audit-events.go",
	}
}

// Doc returns catalog metadata for IA5AuthenticatorDetector.
func (*IA5AuthenticatorDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NIST IA-5 Authenticator Management Non-Compliant",
		Description: "Authenticator management does not meet NIST SP 800-53 IA-5 requirements.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/nist/ia5-authenticator.go",
	}
}
