// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package nist

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AC2AccountManagementDetector.
func (*AC2AccountManagementDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NIST AC-2 Account Management Non-Compliant",
		Description: "Account management practices do not meet ETC's organization-defined thresholds implementing a narrow slice of NIST SP 800-53 AC-2 (inactive-account disable, privileged-account count, service accounts in privileged groups). AC-2 itself leaves these thresholds organization-defined - the specific numbers below are ETC-chosen defaults, not values mandated by the standard - and this check does not cover AC-2's full scope (account-type authorization, approval workflow, periodic access review process, and notification timing are not observable from this data).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/nist/ac2-account-management.go",
	}
}

// Doc returns catalog metadata for AC6LeastPrivilegeDetector.
func (*AC6LeastPrivilegeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NIST AC-6 Least Privilege Non-Compliant",
		Description: "Least privilege practices do not meet ETC's organization-defined thresholds implementing NIST SP 800-53 AC-6(1)/(5)/(10). AC-6 itself leaves these thresholds organization-defined - the specific numbers here are ETC-chosen defaults, not values mandated by the standard. Group membership is checked directly (not recursively through nested groups), except for the Everyone/Authenticated Users special-principal case in Server Operators / Backup Operators, which is fully accounted for.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/nist/ac6-least-privilege.go",
	}
}

// Doc returns catalog metadata for AU2AuditEventsDetector.
func (*AU2AuditEventsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NIST AU-2 Audit Events Non-Compliant",
		Description: "Audit event configuration does not meet ETC's organization-defined event-type selection implementing NIST SP 800-53 AU-2. AU-2 itself leaves the specific event types and levels organization-defined based on risk assessment - the 9 categories and minimums checked here are ETC-chosen defaults, not values mandated by the standard.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/nist/au2-audit-events.go",
	}
}

// Doc returns catalog metadata for IA5AuthenticatorDetector.
func (*IA5AuthenticatorDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NIST IA-5 Authenticator Management Non-Compliant",
		Description: "Authenticator management does not meet NIST SP 800-53 IA-5 requirements. Interdomain trust accounts (UAC flag 0x800) are not counted as accounts with password not required: Windows sets this flag on them by default, and their secret is managed by the system, not a human (KB 305144).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/nist/ia5-authenticator.go",
	}
}
