// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package privileged

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AuthenticatedUsersPrivilegedDetector.
func (*AuthenticatedUsersPrivilegedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Authenticated Users in Privileged Group",
		Description: "Authenticated Users principal is a member of a privileged group. This grants ALL authenticated domain users administrative privileges.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/groups/privileged/authenticated-users-privileged.go",
	}
}

// Doc returns catalog metadata for BuiltinModifiedDetector.
func (*BuiltinModifiedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Builtin Group Modified",
		Description: "Builtin groups contain non-standard members. This may indicate privilege escalation or backdoor access.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/groups/privileged/builtin-modified.go",
	}
}

// Doc returns catalog metadata for EmptyPrivilegedDetector.
func (*EmptyPrivilegedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Empty Privileged Group",
		Description: "Privileged groups with no members. While not a vulnerability, empty admin groups may indicate misconfiguration or unused infrastructure.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/groups/privileged/empty-privileged.go",
	}
}

// Doc returns catalog metadata for EveryoneInPrivilegedDetector.
func (*EveryoneInPrivilegedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Everyone in Privileged Group",
		Description: "The Everyone principal is a member of a privileged group. This grants ALL users (including anonymous) administrative privileges.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/groups/privileged/everyone-in-privileged.go",
	}
}

// Doc returns catalog metadata for ExcessivePrivilegedAccountsDetector.
func (*ExcessivePrivilegedAccountsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Excessive Privileged Accounts",
		Description: "Large number of accounts with administrative privileges increases attack surface. Each privileged account is a potential target for credential theft.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/groups/privileged/excessive-privileged-accounts.go",
	}
}

// Doc returns catalog metadata for ProtectedUsersEmptyDetector.
func (*ProtectedUsersEmptyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Protected Users Group Empty",
		Description: "The Protected Users group has no members. Privileged accounts should be added to this group for enhanced security (NTLM disabled, Kerberos delegation blocked, credential caching prevented).",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/groups/privileged/protected-users-empty.go",
	}
}

// Doc returns catalog metadata for SchemaAdminsNotEmptyDetector.
func (*SchemaAdminsNotEmptyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Schema Admins or Enterprise Admins Group Is Not Empty",
		Description: "Forest-level privileged groups (Schema Admins, Enterprise Admins) have %d total member(s) across %d group(s). These groups should remain empty in steady state and be populated on-demand only for forest-level operations (schema extension, intra-forest trust). ANSSI PA-099 R17.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/groups/privileged/schema-admins-not-empty.go",
	}
}
