// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package membership

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DnsAdminsMemberDetector.
func (*DnsAdminsMemberDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DnsAdmins Member",
		Description: "Users in DnsAdmins group. Can load arbitrary DLLs on domain controllers (escalation to Domain Admin).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/groups/membership/dns-admins-member.go",
	}
}

// Doc returns catalog metadata for GpoModifyRightsDetector.
func (*GpoModifyRightsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Group Policy Creator Owners Member",
		Description: "Users in Group Policy Creator Owners group. Can create/modify GPOs and execute code on domain machines.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/groups/membership/gpo-modify-rights.go",
	}
}

// Doc returns catalog metadata for PreWindows2000AccessDetector.
func (*PreWindows2000AccessDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Pre-Windows 2000 Compatible Access",
		Description: "Pre-Windows 2000 Compatible Access group has members. Overly permissive read access to AD objects.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/groups/membership/pre-windows-2000-access.go",
	}
}
