// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package access

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminRoleDetector.
func (*AdminRoleDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Guest User with Administrative Role",
		Description: "External guest users have administrative directory roles. This is a critical security risk.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/guest-external/access/guest-admin-role.go",
	}
}

// Doc returns catalog metadata for AppAccessUnrestrictedDetector.
func (*AppAccessUnrestrictedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Guest Application Access Unrestricted",
		Description: "Guest users are assigned the \"User\" role (guestUserRoleId), granting the same application access as regular members.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/guest-external/access/guest-app-access.go",
	}
}

// Doc returns catalog metadata for DirectoryVisibilityDetector.
func (*DirectoryVisibilityDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Guest Directory Access Not Restricted",
		Description: "Guest users can enumerate directory objects. Restrict guest access to directory.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/guest-external/access/guest-directory-visibility.go",
	}
}

// Doc returns catalog metadata for GuestToGuestInviteDetector.
func (*GuestToGuestInviteDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Guests Can Invite Other Guests",
		Description: "Guest users can invite other external users, creating an uncontrolled invitation chain.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/guest-external/access/guest-to-guest-invite.go",
	}
}

// Doc returns catalog metadata for NoCAPolicyDetector.
func (*NoCAPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No CA Policy for Guest Users",
		Description: "No CA policy specifically targets guest or external users by name/ID matching. Targeting done exclusively via Microsoft's newer 'All guest and external users' condition is not currently detected (collector does not capture includeGuestsOrExternalUsers).",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/guest-external/access/guest-no-ca-policy.go",
	}
}

// Doc returns catalog metadata for NoMFARequiredDetector.
func (*NoMFARequiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No MFA Required for Guest Users",
		Description: "No CA policy requires MFA for guest/external users via name/ID matching plus the classic 'mfa' grant control. Guest targeting via Microsoft's 'All guest and external users' condition, and MFA required via an authentication strength grant control, are not currently detected (collector gaps - see code comment).",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/guest-external/access/guest-no-mfa-required.go",
	}
}
