// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package delegation

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ConstrainedDelegationDetector.
func (*ConstrainedDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Constrained Delegation",
		Description: "Computer with constrained Kerberos delegation. Can impersonate users to specified services.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/constrained-delegation.go",
	}
}

// Doc returns catalog metadata for DCSyncRightsDetector.
func (*DCSyncRightsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer DCSync Rights",
		Description: "Computer with DCSync replication rights. Can extract all domain password hashes.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/dcsync-rights.go",
	}
}

// Doc returns catalog metadata for InAdminGroupDetector.
func (*InAdminGroupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer in Admin Group",
		Description: "Enabled computer account is a direct member of a privileged group protected by AdminSDHolder (Domain Admins, Enterprise Admins, Administrators, Schema Admins, Account/Backup/Print/Server Operators, Key/Enterprise Key Admins, Domain Controllers), matched by SID so a same-named decoy group or a localized forest cannot hide or fake this membership. Domain Admins, Enterprise Admins and Administrators give direct domain compromise; the other groups give a documented escalation path through AD administration, DC replication or key-trust rights, and how exploitable it is depends on what else that group can reach in this directory. Disabled computer accounts in these groups are reported separately by COMPUTER_IN_ADMIN_GROUP_ON_DISABLED_ACCOUNT.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/in-admin-group.go",
	}
}

// Doc returns catalog metadata for InAdminGroupOnDisabledAccountDetector.
func (*InAdminGroupOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer in Admin Group (Disabled Account)",
		Description: "Disabled computer account is a direct member of a privileged group protected by AdminSDHolder (Domain Admins, Enterprise Admins, Administrators, Schema Admins, Account/Backup/Print/Server Operators, Key/Enterprise Key Admins, Domain Controllers), matched by SID. It cannot authenticate while disabled, so it cannot exercise the privilege. Membership is not removed by this state - it returns to full effect the instant the account is re-enabled. Remediation: remove the account from the group.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/computers/delegation/in-admin-group-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for RbcdDetector.
func (*RbcdDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer RBCD",
		Description: "Computer with Resource-Based Constrained Delegation. Enables privilege escalation via RBCD attack.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/rbcd.go",
	}
}

// Doc returns catalog metadata for UnconstrainedDelegationDetector.
func (*UnconstrainedDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Unconstrained Delegation",
		Description: "Enabled non-domain-controller computer accounts with unconstrained Kerberos delegation enabled (UAC 0x80000). Servers can be used for privilege escalation attacks. Domain controllers are excluded: they always carry unconstrained delegation by design (Microsoft Defender for Identity excludes them from this assessment for the same reason).",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/unconstrained-delegation.go",
	}
}

// Doc returns catalog metadata for UnconstrainedDelegationOnDisabledAccountDetector.
func (*UnconstrainedDelegationOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Unconstrained Delegation (Disabled Account)",
		Description: "Disabled non-domain-controller computer accounts with unconstrained Kerberos delegation enabled (UAC 0x80000) are not exploitable while disabled. Two separate refusals apply: the account cannot obtain a ticket-granting ticket of its own, which closes the delegation-origin role, and the KDC will not issue a service ticket for its SPN, which closes the delegation-target role. The configuration remains set, and both roles become exploitable again the instant the account is re-enabled. Domain controllers are excluded: they always carry unconstrained delegation by design (Microsoft Defender for Identity excludes them from this assessment for the same reason). Remediation: remove the delegation bit or delete the account.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/computers/delegation/unconstrained-delegation-on-disabled-account.go",
	}
}
