// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package delegation

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ConstrainedDelegationDetector.
func (*ConstrainedDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Constrained Delegation",
		Description: "Computer with constrained Kerberos delegation. Can impersonate users to specified services.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/constrained-delegation.go",
	}
}

// Doc returns catalog metadata for DCSyncRightsDetector.
func (*DCSyncRightsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer DCSync Rights",
		Description: "Computer with DCSync replication rights. Can extract all domain password hashes.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/dcsync-rights.go",
	}
}

// Doc returns catalog metadata for InAdminGroupDetector.
func (*InAdminGroupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer in Admin Group",
		Description: "Computer account in Domain Admins or Enterprise Admins. Computer compromise leads to domain admin access.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/in-admin-group.go",
	}
}

// Doc returns catalog metadata for RbcdDetector.
func (*RbcdDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer RBCD",
		Description: "Computer with Resource-Based Constrained Delegation. Enables privilege escalation via RBCD attack.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/rbcd.go",
	}
}

// Doc returns catalog metadata for UnconstrainedDelegationDetector.
func (*UnconstrainedDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Unconstrained Delegation",
		Description: "Computer with unconstrained delegation enabled. Servers can be used for privilege escalation attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/delegation/unconstrained-delegation.go",
	}
}
