// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package kerberos

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminAsrepRoastableDetector.
func (*AdminAsrepRoastableDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Account AS-REP Roastable",
		Description: "Enabled privileged accounts (Domain Admins, Domain Controllers, Schema Admins, Enterprise Admins, Key Admins, Enterprise Key Admins, Administrators, Account Operators, Server Operators, Print Operators, Backup Operators) without Kerberos pre-authentication. High-value targets for AS-REP roasting attacks - immediate domain compromise risk.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/kerberos/admin-asrep-roastable.go",
	}
}

// Doc returns catalog metadata for AdminAsrepRoastableOnDisabledAccountDetector.
func (*AdminAsrepRoastableOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Account AS-REP Roastable (Disabled Account)",
		Description: "Disabled privileged accounts (Domain Admins, Domain Controllers, Schema Admins, Enterprise Admins, Key Admins, Enterprise Key Admins, Administrators, Account Operators, Server Operators, Print Operators, Backup Operators) without Kerberos pre-authentication. Not exploitable while disabled - the KDC rejects the AS-REQ on account status first - but the bit remains set and would apply again if the account is re-enabled.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/kerberos/admin-asrep-roastable-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for AsrepRoastingOnDisabledAccountDetector.
func (*AsrepRoastingOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AS-REP Roasting Risk (Disabled Account)",
		Description: "Disabled user accounts without Kerberos pre-authentication required (UAC 0x400000). Not exploitable while disabled - the KDC rejects the AS-REQ on account status first - but the bit remains set and would apply again if the account is re-enabled.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/kerberos/asrep-roasting-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for AsrepRoastingRiskDetector.
func (*AsrepRoastingRiskDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AS-REP Roasting Risk",
		Description: "Enabled user accounts without Kerberos pre-authentication required (UAC 0x400000). Vulnerable to AS-REP roasting attacks today.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/kerberos/asrep-roasting-risk.go",
	}
}

// Doc returns catalog metadata for ConstrainedDelegationDetector.
func (*ConstrainedDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Constrained Delegation",
		Description: "User accounts with constrained Kerberos delegation configured (UAC 0x1000000). Can impersonate users to specific services.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/kerberos/constrained-delegation.go",
	}
}

// Doc returns catalog metadata for ConstrainedDelegationOnDisabledAccountDetector.
func (*ConstrainedDelegationOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Constrained Delegation (Disabled Account)",
		Description: "Disabled user accounts with constrained Kerberos delegation configured (UAC 0x1000000 and/or msDS-AllowedToDelegateTo). Not exploitable while disabled - obtaining the TGT that either delegation path requires is blocked at AS-REQ - but the configuration remains set and would apply again if the account is re-enabled.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/kerberos/constrained-delegation-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for DelegationUnknownTargetDetector.
func (*DelegationUnknownTargetDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Constrained Delegation to Unknown Target",
		Description: "Accounts with constrained delegation configured to SPNs whose target hostname does not match any known computer in Active Directory. This may indicate stale delegation entries pointing to decommissioned servers, or delegation to external/unknown systems. Attackers could potentially register a machine with the missing hostname to intercept delegated credentials.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/kerberos/delegation-unknown-target.go",
	}
}

// Doc returns catalog metadata for GoldenTicketRiskDetector.
func (*GoldenTicketRiskDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Golden Ticket Risk",
		Description: "krbtgt account password unchanged for 6+ months. Enables persistent Golden Ticket attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/kerberos/golden-ticket-risk.go",
	}
}

// Doc returns catalog metadata for KerberoastingRiskDetector.
func (*KerberoastingRiskDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Kerberoasting Risk - Tier 0 admin exposes a SPN",
		Description: "%d Tier 0 admin account(s) carry a SPN, exposing them to Kerberoasting (any authenticated user can request a TGS and crack the returned ticket offline). Tier 0 is recognized by well-known SID (fixed RID, e.g. Domain Admins, Enterprise Admins), by name for DnsAdmins (no fixed RID exists), plus recursive group nesting and tier0_groups.yaml customer config. Move the SPN to a dedicated service identity (gMSA preferred) outside Tier 0, or remove the SPN if unused. ANSSI PA-099 R69 violation.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/kerberos/kerberoasting-risk.go",
	}
}

// Doc returns catalog metadata for KerberosAesDisabledDetector.
func (*KerberosAesDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AES Encryption Disabled",
		Description: "User accounts with AES Kerberos encryption disabled. Forces use of weaker DES/RC4 encryption vulnerable to offline attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/kerberos/kerberos-aes-disabled.go",
	}
}

// Doc returns catalog metadata for KerberosRc4FallbackDetector.
func (*KerberosRc4FallbackDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "RC4 Fallback Enabled",
		Description: "User accounts support both AES and RC4 encryption. RC4 fallback enables downgrade attacks even when AES is available.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/kerberos/kerberos-rc4-fallback.go",
	}
}

// Doc returns catalog metadata for KerberosRenewableTicketLongDetector.
func (*KerberosRenewableTicketLongDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Kerberos Renewable Ticket Lifetime Too Long",
		Description: "Renewable ticket lifetime exceeds recommended 7 days, allowing persistent access with stolen tickets.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/kerberos/kerberos-renewable-ticket-long.go",
	}
}

// Doc returns catalog metadata for KerberosTicketLifetimeLongDetector.
func (*KerberosTicketLifetimeLongDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Kerberos Ticket Lifetime Too Long",
		Description: "Kerberos TGT lifetime exceeds recommended 10 hours, increasing the attack window for stolen tickets.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/kerberos/kerberos-ticket-lifetime-long.go",
	}
}

// Doc returns catalog metadata for UnconstrainedDelegationDetector.
func (*UnconstrainedDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Unconstrained Delegation",
		Description: "Enabled user accounts with unconstrained Kerberos delegation enabled (UAC 0x80000). Can impersonate any user.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/kerberos/unconstrained-delegation.go",
	}
}

// Doc returns catalog metadata for UnconstrainedDelegationOnDisabledAccountDetector.
func (*UnconstrainedDelegationOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Unconstrained Delegation (Disabled Account)",
		Description: "Disabled user accounts with unconstrained Kerberos delegation enabled (UAC 0x80000) are not exploitable while disabled. Two separate refusals apply: the account cannot obtain a ticket-granting ticket of its own, which closes the delegation-origin role, and the KDC will not issue a service ticket for its SPN, which closes the delegation-target role. The configuration remains set, and both roles become exploitable again the instant the account is re-enabled. Remediation: remove the delegation bit or delete the account.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/kerberos/unconstrained-delegation-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for WeakEncryptionDESDetector.
func (*WeakEncryptionDESDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak DES Encryption",
		Description: "User accounts with DES encryption algorithms enabled (UAC 0x200000 or msDS-SupportedEncryptionTypes). DES is cryptographically broken.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/kerberos/weak-encryption-des.go",
	}
}

// Doc returns catalog metadata for WeakEncryptionDESOnDisabledAccountDetector.
func (*WeakEncryptionDESOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak DES Encryption (Disabled Account)",
		Description: "Disabled user accounts with DES encryption algorithms enabled (UAC 0x200000 and/or msDS-SupportedEncryptionTypes). Dormant for two combined reasons: as a client, a disabled account cannot complete the initial Kerberos exchange (AS-REQ) where DES could actually be negotiated, even on the branch that would succeed if the account were active; as a target, a service ticket requested by a third party against this account can never be protected with DES regardless of its enabled state, since the KDC categorically refuses DES for service tickets. A domain controller whose Kerberos encryption policy does not include DES reinforces this further, but is not itself the reason the disabled half stays dormant. The configuration remains set and stays reported for when the account is re-enabled.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/kerberos/weak-encryption-des-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for WeakEncryptionRC4Detector.
func (*WeakEncryptionRC4Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak RC4 Encryption",
		Description: "User accounts supporting RC4 encryption without AES. RC4 is deprecated and vulnerable to attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/kerberos/weak-encryption-rc4.go",
	}
}
