// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package gpo

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AuthenticatedUsersApplyDetector.
func (*AuthenticatedUsersApplyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "GPO Applies to All Authenticated Users",
		Description: "GPOs with Authenticated Users granted the 'Apply Group Policy' permission. This is the default but may be too broad for sensitive policies.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/authenticated-users-apply.go",
	}
}

// Doc returns catalog metadata for BitLockerDetector.
func (*BitLockerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "BitLocker Not Required via GPO",
		Description: "BitLocker drive encryption is not enforced via Group Policy. Without disk encryption, stolen or decommissioned hardware exposes Active Directory data, cached credentials, and other sensitive information.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/gpo/infrastructure-security.go",
	}
}

// Doc returns catalog metadata for CachedLogonsDetector.
func (*CachedLogonsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Excessive Cached Logons",
		Description: "Winlogon\\CachedLogonsCount > 4 (ANSSI PA-099 R34.1 threshold; ideally 0 on Tier 0). Cached MS-CACHE-V2 hashes can be cracked offline if a workstation is stolen, exposing the most recent interactive logons.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/gpo/credential-security.go",
	}
}

// Doc returns catalog metadata for CredentialGuardDetector.
func (*CredentialGuardDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Credential Guard Not Enabled",
		Description: "Windows Credential Guard is not deployed via GPO. Credential Guard uses virtualization-based security to isolate NTLM hashes and Kerberos TGTs from direct memory access, preventing credential theft even if the OS is compromised.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/credential-security.go",
	}
}

// Doc returns catalog metadata for DangerousPermissionsDetector.
func (*DangerousPermissionsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "GPO Permissions Review Required",
		Description: "Group Policy Objects should be reviewed for overly permissive ACLs that allow non-administrators to modify GPO settings.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/gpo/dangerous-permissions.go",
	}
}

// Doc returns catalog metadata for DefenderASRDetector.
func (*DefenderASRDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Defender Attack Surface Reduction Not Configured",
		Description: "Microsoft Defender Attack Surface Reduction (ASR) rules are not deployed via GPO. ASR rules block common attack techniques such as Office macro execution, script obfuscation, credential stealing from LSASS, and other malware delivery methods.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/defender-asr.go",
	}
}

// Doc returns catalog metadata for DisabledButLinkedDetector.
func (*DisabledButLinkedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Disabled GPO Still Linked",
		Description: "GPOs are disabled (both user and computer settings) but remain linked. This may indicate configuration drift or incomplete changes.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/disabled-but-linked.go",
	}
}

// Doc returns catalog metadata for FirewallOutboundDetector.
func (*FirewallOutboundDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Windows Firewall Outbound Not Blocked",
		Description: "Windows Firewall does not block outbound connections by default for the domain profile. Allowing unrestricted outbound connections enables malware to communicate with C2 servers, exfiltrate data, and establish reverse shells.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/gpo/firewall-outbound.go",
	}
}

// Doc returns catalog metadata for FolderOptionsNotHardenedDetector.
func (*FolderOptionsNotHardenedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No GPO Hardens Folder-Options Script Execution",
		Description: "No Group Policy configures DefaultFileTypeRisk or LowRiskFileTypes to restrict dangerous script extensions (.hta, .js, .vbs, .wsf). By default Windows allows these file types to execute on double-click without a security warning, which is a common phishing and malware delivery vector.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/folder-options-not-hardened.go",
	}
}

// Doc returns catalog metadata for FolderOptionsScriptExecDetector.
func (*FolderOptionsScriptExecDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Folder Options Allow Script Execution Without Warning",
		Description: "A Group Policy configures file associations to treat dangerous script types (.hta, .js, .vbs, .wsf) as low-risk, allowing them to execute without security warnings. This can be abused for phishing and malware delivery.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/folder-options-script-exec.go",
	}
}

// Doc returns catalog metadata for GPOInventoryDetector.
func (*GPOInventoryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Group Policy Object",
		Description: "Inventory entry — exposes the GPO as a first-class asset to the SaaS (linked containers, permissions, WMI filter).",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/gpo/gpo-inventory.go",
	}
}

// Doc returns catalog metadata for HardenedUNCPathsDetector.
func (*HardenedUNCPathsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Hardened UNC Paths Not Configured",
		Description: "Hardened UNC paths are not properly configured for SYSVOL and NETLOGON shares. Without RequireMutualAuthentication and RequireIntegrity, GPO settings can be tampered with during transit, enabling attacks like GPO hijacking.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/gpo/hardened-unc-paths.go",
	}
}

// Doc returns catalog metadata for KerberosArmoringClientDetector.
func (*KerberosArmoringClientDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Kerberos Armoring (FAST) Not Required on Clients",
		Description: "Kerberos FAST armoring is not required on client machines. Without client-side enforcement, pre-authentication exchanges remain vulnerable to interception and offline attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/kerberos-armoring.go",
	}
}

// Doc returns catalog metadata for KerberosArmoringDCDetector.
func (*KerberosArmoringDCDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Kerberos Armoring (FAST) Not Enforced on DCs",
		Description: "Kerberos Flexible Authentication Secure Tunneling (FAST/Armoring) is not configured on Domain Controllers. FAST protects Kerberos pre-authentication exchanges from offline brute-force and AS-REP roasting attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/kerberos-armoring.go",
	}
}

// Doc returns catalog metadata for LAPSNotDeployedDetector.
func (*LAPSNotDeployedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LAPS Not Deployed via GPO",
		Description: "No active Group Policy Object was found deploying LAPS (Local Administrator Password Solution). This leaves local admin passwords vulnerable to reuse attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/laps-not-deployed.go",
	}
}

// Doc returns catalog metadata for LLMNRNotDisabledDetector.
func (*LLMNRNotDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LLMNR Not Disabled",
		Description: "Link-Local Multicast Name Resolution (LLMNR) is not disabled via Group Policy. LLMNR responds to broadcast name queries and can be abused by attackers on the local network to capture NTLMv2 hashes via poisoning attacks (e.g., Responder).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/gpo/llmnr-not-disabled.go",
	}
}

// Doc returns catalog metadata for LSAProtectionDetector.
func (*LSAProtectionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LSA Protection (RunAsPPL) Not Enabled",
		Description: "LSASS process is not running as a Protected Process Light (PPL). Without this protection, attackers can dump credentials directly from the LSASS process memory using tools like Mimikatz, procdump, or task manager.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/gpo/credential-security.go",
	}
}

// Doc returns catalog metadata for NTLMv1Detector.
func (*NTLMv1Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NTLMv1 Authentication Allowed",
		Description: "LAN Manager authentication level does not enforce NTLMv2-only. NTLMv1 responses can be cracked offline in seconds. Level 5 (Send NTLMv2 response only, refuse LM & NTLM) should be enforced.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/gpo/credential-security.go",
	}
}

// Doc returns catalog metadata for NetSessionHardeningDetector.
func (*NetSessionHardeningDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Net Session Hardening Not Configured (NetCease)",
		Description: "Network session enumeration (NetSessionEnum) is not restricted. By default, any authenticated user can enumerate active sessions on servers, revealing which users are logged into which machines. This information is heavily used in attack path mapping (e.g., BloodHound session collection).",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/net-session-hardening.go",
	}
}

// Doc returns catalog metadata for NoSecurityFilteringDetector.
func (*NoSecurityFilteringDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "GPO Without Security Filtering",
		Description: "GPOs that apply to all Authenticated Users or Everyone without specific security filtering. Consider restricting GPO application to specific groups.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/no-security-filtering.go",
	}
}

// Doc returns catalog metadata for OrphanedDetector.
func (*OrphanedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Orphaned GPOs Detected",
		Description: "GPOs with mismatched AD objects and SYSVOL directories. Orphaned GPOs can cause processing errors and may indicate tampering.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/orphaned.go",
	}
}

// Doc returns catalog metadata for PasswordInSysvolDetector.
func (*PasswordInSysvolDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Passwords Found in GPO SYSVOL",
		Description: "GPO Preferences contain cleartext passwords in SYSVOL (cPassword vulnerability MS14-025). These passwords can be easily decrypted by any domain user.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/gpo/password-in-sysvol.go",
	}
}

// Doc returns catalog metadata for PrintNightmareDetector.
func (*PrintNightmareDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PrintNightmare Mitigation Not Applied",
		Description: "Point-and-Print restrictions are not configured to prevent PrintNightmare (CVE-2021-34527) exploitation. The NoWarningNoElevationOnInstall setting allows any user to install printer drivers from remote servers without elevation, enabling remote code execution as SYSTEM.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/gpo/infrastructure-security.go",
	}
}

// Doc returns catalog metadata for RemoteSAMDetector.
func (*RemoteSAMDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Remote SAM Access Not Restricted",
		Description: "The Security Account Manager (SAM) remote access is not restricted via GPO. By default, any authenticated user can enumerate local accounts and group memberships remotely, aiding reconnaissance.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/credential-security.go",
	}
}

// Doc returns catalog metadata for SeBackupAbuseDetector.
func (*SeBackupAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SeBackupPrivilege Overly Assigned",
		Description: "The SeBackupPrivilege user right is assigned to accounts beyond Administrators and Backup Operators. This privilege allows reading any file on the system, bypassing all ACLs, enabling extraction of the NTDS.dit database, SAM hive, and other sensitive data.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/gpo/privilege-rights-abuse.go",
	}
}

// Doc returns catalog metadata for SeDebugAbuseDetector.
func (*SeDebugAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SeDebugPrivilege Assigned to Non-Administrators",
		Description: "The SeDebugPrivilege user right is assigned to accounts beyond the Administrators group. This privilege allows debugging any process, enabling credential extraction from LSASS memory, process injection, and full system compromise.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/gpo/privilege-rights-abuse.go",
	}
}

// Doc returns catalog metadata for SeLoadDriverAbuseDetector.
func (*SeLoadDriverAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SeLoadDriverPrivilege Assigned to Non-Administrators",
		Description: "The SeLoadDriverPrivilege user right is assigned to accounts beyond Administrators. This privilege allows loading kernel-mode drivers, which can be abused to install rootkits, disable security software, and achieve full system compromise at the kernel level.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/gpo/privilege-rights-abuse.go",
	}
}

// Doc returns catalog metadata for SeRestoreAbuseDetector.
func (*SeRestoreAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SeRestorePrivilege Overly Assigned",
		Description: "The SeRestorePrivilege user right is assigned beyond Administrators and Backup Operators. This privilege allows writing to any file and registry key, bypassing ACLs, enabling DLL hijacking, service binary replacement, and other privilege escalation techniques.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/gpo/privilege-rights-abuse.go",
	}
}

// Doc returns catalog metadata for SeTcbAbuseDetector.
func (*SeTcbAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SeTcbPrivilege (Act as Part of OS) Assigned",
		Description: "The SeTcbPrivilege (Act as part of the operating system) user right is assigned to user accounts. This privilege allows impersonating any user without authentication, equivalent to being SYSTEM. No user account should have this privilege.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/gpo/privilege-rights-abuse.go",
	}
}

// Doc returns catalog metadata for TerminalServicesNotHardenedDetector.
func (*TerminalServicesNotHardenedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Terminal Services / RDP Not Hardened",
		Description: "Remote Desktop Protocol (RDP) security settings are not properly hardened via GPO. Without NLA (Network Level Authentication) and TLS security layer, RDP sessions are vulnerable to man-in-the-middle attacks and credential theft.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/terminal-services.go",
	}
}

// Doc returns catalog metadata for UnlinkedDetector.
func (*UnlinkedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Unlinked Group Policy Objects",
		Description: "GPOs exist that are not linked to any OU, domain, or site. These may be orphaned or indicate incomplete deployment.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/gpo/unlinked.go",
	}
}

// Doc returns catalog metadata for WDigestDetector.
func (*WDigestDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "WDigest Authentication Stores Cleartext Credentials",
		Description: "WDigest UseLogonCredential is not explicitly disabled. On systems prior to Windows 8.1/2012 R2, or when enabled, WDigest stores cleartext passwords in LSASS memory, which can be extracted with tools like Mimikatz.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/gpo/credential-security.go",
	}
}

// Doc returns catalog metadata for WSUSHTTPDetector.
func (*WSUSHTTPDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "WSUS Configured Over HTTP",
		Description: "Windows Server Update Services (WSUS) is configured to use HTTP instead of HTTPS. This allows attackers on the network to perform man-in-the-middle attacks and inject malicious updates, achieving code execution on all domain-joined machines.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/gpo/infrastructure-security.go",
	}
}

// Doc returns catalog metadata for WeakPasswordPolicyDetector.
func (*WeakPasswordPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak Password Policy",
		Description: "Domain password policy requires only %d characters minimum. Microsoft recommends at least 12 characters for standard accounts, 14+ for privileged accounts.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/gpo/weak-password-policy.go",
	}
}

// Doc returns catalog metadata for ZerologonDetector.
func (*ZerologonDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Zerologon (CVE-2020-1472) Enforcement Not Enabled",
		Description: "Secure channel enforcement for Zerologon (CVE-2020-1472) is not explicitly configured. Without FullSecureChannelProtection set to 1, Domain Controllers may still accept unauthenticated Netlogon connections, allowing complete domain takeover.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/gpo/infrastructure-security.go",
	}
}
