// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package network

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DNSZoneAUCreateChildDetector.
func (*DNSZoneAUCreateChildDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNS Zone Allows Authenticated Users to Create Records",
		Description: "DNS zones where Authenticated Users can create child objects allow any domain user to add arbitrary DNS records, enabling man-in-the-middle and credential theft attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dns-zone-au-create-child.go",
	}
}

// Doc returns catalog metadata for DcBackupDetector.
func (*DcBackupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Domain Controller Backup Review",
		Description: "Active Directory should be backed up regularly (tombstone lifetime is 180 days). This check has no direct visibility into backup jobs: no attribute in the directory records when a backup last completed. It uses the most recent whenChanged timestamp across NTDS Settings objects (CN=Sites) as an indirect activity indicator, since a valid AD backup updates replication metadata. That same timestamp also moves for unrelated reasons (site/topology edits, FSMO transfers, DC promotion or demotion), so it can look more recent than the last real backup. Treat this as a prompt to verify backups directly, not as a backup date.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/network/dc-backup.go",
	}
}

// Doc returns catalog metadata for DcLdapsWeakTlsDetector.
func (*DcLdapsWeakTlsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LDAPS Accepts Weak TLS Versions",
		Description: "Domain controllers accepting TLS 1.0 or 1.1 on LDAPS (port 636) are vulnerable to downgrade attacks and known TLS protocol vulnerabilities (POODLE, BEAST).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dc-ldaps-weak-tls.go",
	}
}

// Doc returns catalog metadata for DcSpoolerDetector.
func (*DcSpoolerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Print Spooler Running on Domain Controller",
		Description: "Domain controllers where the Print Spooler RPC pipe (\\PIPE\\spoolss) was confirmed reachable are vulnerable to PrintNightmare (CVE-2021-34527) and PrinterBug attacks for credential relay. SMB (port 445) being open is not evidence by itself: it is open on every domain controller regardless of spooler state.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dc-spooler.go",
	}
}

// Doc returns catalog metadata for DfsrDetector.
func (*DfsrDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DFSR Migration Status",
		Description: "FRS (File Replication Service) was deprecated in Windows Server 2008 R2; DFSR (DFS Replication) has been available for SYSVOL since the Windows Server 2008 domain functional level. This flags domains confirmed still using FRS for SYSVOL despite a functional level that already supports migrating to DFSR. Source: https://learn.microsoft.com/en-us/windows-server/storage/dfs-replication/migrate-sysvol-to-dfsr",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/network/dfsr.go",
	}
}

// Doc returns catalog metadata for DnsDynamicUpdateDetector.
func (*DnsDynamicUpdateDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNS Dynamic Update Insecure",
		Description: "DNS zones allowing non-secure dynamic updates. Attackers can inject malicious DNS records without authentication.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dns-dynamic-update.go",
	}
}

// Doc returns catalog metadata for DnsWildcardDetector.
func (*DnsWildcardDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNS Wildcard Records Detected",
		Description: "Wildcard DNS records (*.domain) can be exploited for MITM attacks. Review and remove unnecessary wildcards.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/network/dns-wildcard.go",
	}
}

// Doc returns catalog metadata for DnsZoneTransferDetector.
func (*DnsZoneTransferDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNS Zone Transfer Unrestricted",
		Description: "DNS zones allowing zone transfers to any server. Attackers can enumerate DNS records to map internal network topology.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dns-zone-transfer.go",
	}
}

// Doc returns catalog metadata for DnssecDetector.
func (*DnssecDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNSSEC Not Enabled",
		Description: "Retired: DNSSEC signing state is not currently collected by any provider (see type comment). This detector never fires.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/network/dnssec.go",
	}
}

// Doc returns catalog metadata for NtpDetector.
func (*NtpDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NTP Configuration Review Needed",
		Description: "Time synchronization configuration should be reviewed. The PDC Emulator must be configured as the authoritative time source to prevent Kerberos authentication issues.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/network/ntp.go",
	}
}

// Doc returns catalog metadata for SiteTopologyDetector.
func (*SiteTopologyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AD Sites Without a Domain Controller",
		Description: "Sites with zero domain controllers force clients in that site to authenticate against a DC in another site, increasing latency and WAN traffic. This check only counts sites with no DC assigned - it does not evaluate site links, replication costs, or subnet-to-site mappings, none of which are collected today.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/network/site-topology.go",
	}
}

// Doc returns catalog metadata for SubnetMissingDetector.
func (*SubnetMissingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AD Sites Missing Subnets",
		Description: "Sites without subnet definitions. Clients in undefined subnets will select DCs randomly, potentially crossing WAN links.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/network/subnet-missing.go",
	}
}

// Doc returns catalog metadata for SysvolNetlogonDetector.
func (*SysvolNetlogonDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "TODO_EXTRACTION_FAILED",
		Description: "Doc() metadata could not be extracted automatically; edit cataloggen or override manually.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/network/sysvol-netlogon.go",
	}
}
