// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package network

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DNSZoneAUCreateChildDetector.
func (*DNSZoneAUCreateChildDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNS Zone Allows Authenticated Users to Create Records",
		Description: "DNS zones where Authenticated Users can create child objects allow any domain user to add arbitrary DNS records, enabling man-in-the-middle and credential theft attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dns-zone-au-create-child.go",
	}
}

// Doc returns catalog metadata for DcBackupDetector.
func (*DcBackupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Domain Controller Backup Review",
		Description: "Active Directory should be backed up regularly. Tombstone lifetime is 180 days.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/network/dc-backup.go",
	}
}

// Doc returns catalog metadata for DcDiskSpaceDetector.
func (*DcDiskSpaceDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DC Disk Space Monitoring",
		Description: "Domain controller disk space should be monitored. Low disk space can cause AD database corruption and replication failures.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/network/dc-disk-space.go",
	}
}

// Doc returns catalog metadata for DcLdapsWeakTlsDetector.
func (*DcLdapsWeakTlsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LDAPS Accepts Weak TLS Versions",
		Description: "Domain controllers accepting TLS 1.0 or 1.1 on LDAPS (port 636) are vulnerable to downgrade attacks and known TLS protocol vulnerabilities (POODLE, BEAST).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dc-ldaps-weak-tls.go",
	}
}

// Doc returns catalog metadata for DcSpoolerDetector.
func (*DcSpoolerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Print Spooler Running on Domain Controller",
		Description: "Domain controllers with Print Spooler service running are vulnerable to PrintNightmare (CVE-2021-34527) and PrinterBug attacks for credential relay.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dc-spooler.go",
	}
}

// Doc returns catalog metadata for DcTimeSyncDetector.
func (*DcTimeSyncDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DC Time Synchronization Review",
		Description: "Domain controllers with potential time sync issues detected. Kerberos requires time difference < 5 minutes.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dc-time-sync.go",
	}
}

// Doc returns catalog metadata for DfsrDetector.
func (*DfsrDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DFSR Migration Status",
		Description: "FRS (File Replication Service) is deprecated. SYSVOL should be replicated using DFSR (DFS Replication) for better reliability.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/network/dfsr.go",
	}
}

// Doc returns catalog metadata for DnsDynamicUpdateDetector.
func (*DnsDynamicUpdateDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNS Dynamic Update Insecure",
		Description: "DNS zones allowing non-secure dynamic updates. Attackers can inject malicious DNS records without authentication.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dns-dynamic-update.go",
	}
}

// Doc returns catalog metadata for DnsWildcardDetector.
func (*DnsWildcardDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNS Wildcard Records Detected",
		Description: "Wildcard DNS records (*.domain) can be exploited for MITM attacks. Review and remove unnecessary wildcards.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/network/dns-wildcard.go",
	}
}

// Doc returns catalog metadata for DnsZoneTransferDetector.
func (*DnsZoneTransferDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNS Zone Transfer Unrestricted",
		Description: "DNS zones allowing zone transfers to any server. Attackers can enumerate DNS records to map internal network topology.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/dns-zone-transfer.go",
	}
}

// Doc returns catalog metadata for DnssecDetector.
func (*DnssecDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DNSSEC Not Enabled",
		Description: "DNSSEC is not enabled for the domain. DNS responses can be spoofed, enabling cache poisoning and MITM attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/network/dnssec.go",
	}
}

// Doc returns catalog metadata for NtpDetector.
func (*NtpDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NTP Configuration Review Needed",
		Description: "Time synchronization configuration should be reviewed. The PDC Emulator must be configured as the authoritative time source to prevent Kerberos authentication issues.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/network/ntp.go",
	}
}

// Doc returns catalog metadata for SiteTopologyDetector.
func (*SiteTopologyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AD Site Topology Issues",
		Description: "Sites without domain controllers cause clients to authenticate against remote DCs, increasing latency and WAN traffic.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/network/site-topology.go",
	}
}

// Doc returns catalog metadata for SubnetMissingDetector.
func (*SubnetMissingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AD Sites Missing Subnets",
		Description: "Sites without subnet definitions. Clients in undefined subnets will select DCs randomly, potentially crossing WAN links.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/network/subnet-missing.go",
	}
}

// Doc returns catalog metadata for SysvolNetlogonDetector.
func (*SysvolNetlogonDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SYSVOL/NETLOGON Permissions Review",
		Description: "SYSVOL and NETLOGON share permissions should be audited. Weak permissions allow attackers to modify logon scripts and GPOs.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/network/sysvol-netlogon.go",
	}
}
