// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package lifecycle

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DisabledNotBlockedDetector.
func (*DisabledNotBlockedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Disabled Users With Session Revocation Not Confirmed",
		Description: "User accounts are disabled (new sign-in is already blocked), but this collector has no way to confirm whether their existing sessions and refresh tokens were separately revoked (Microsoft Entra ID does not revoke them automatically on disable). Run 'Revoke sessions' for each to close any window an already-issued token leaves open.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/lifecycle/user-disabled-not-blocked.go",
	}
}

// Doc returns catalog metadata for NeverSignedInDetector.
func (*NeverSignedInDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Users Never Signed In",
		Description: "User accounts that have never signed in. These may be provisioning errors or abandoned accounts.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/lifecycle/user-never-signed-in.go",
	}
}

// Doc returns catalog metadata for NoManagerDetector.
func (*NoManagerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Users Without Manager Assigned",
		Description: "User accounts without a manager attribute. Manager data is needed for access reviews and organizational hierarchy.",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/identity/lifecycle/user-no-manager.go",
	}
}

// Doc returns catalog metadata for UserStale90DaysDetector.
func (*UserStale90DaysDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Stale User Accounts (90+ Days)",
		Description: "User accounts with no sign-in activity for 90+ days. Stale accounts increase attack surface.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/lifecycle/user-stale-90-days.go",
	}
}
