// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package policies

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for NoAllAppsCoverageDetector.
func (*NoAllAppsCoverageDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No CA Policy Covers All Cloud Apps",
		Description: "No CA policy targets all cloud applications. Individual app targeting may leave gaps.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/conditional-access/policies/ca-no-all-apps-coverage.go",
	}
}

// Doc returns catalog metadata for NoDeviceComplianceDetector.
func (*NoDeviceComplianceDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No CA Policy Requires Device Compliance",
		Description: "No CA policy requires compliant or domain-joined devices.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/conditional-access/policies/ca-no-device-compliance.go",
	}
}

// Doc returns catalog metadata for NoLegacyAuthBlockDetector.
func (*NoLegacyAuthBlockDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No CA Policy Blocks Legacy Authentication",
		Description: "No CA policy blocks legacy authentication protocols that cannot use MFA.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/conditional-access/policies/ca-no-legacy-auth-block.go",
	}
}

// Doc returns catalog metadata for NoMFARequirementDetector.
func (*NoMFARequirementDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No CA Policy Requires MFA",
		Description: "No enabled CA policy requires multi-factor authentication in its grant controls.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/conditional-access/policies/ca-no-mfa-requirement.go",
	}
}

// Doc returns catalog metadata for NoPolicyAdminsDetector.
func (*NoPolicyAdminsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No CA Policy Targeting Admin Roles",
		Description: "No CA policy specifically targets administrative directory roles.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/conditional-access/policies/ca-no-policy-admins.go",
	}
}

// Doc returns catalog metadata for NoPolicyAllUsersDetector.
func (*NoPolicyAllUsersDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No CA Policy Targeting All Users",
		Description: "No enabled Conditional Access policy targets all users. Without comprehensive coverage, users may bypass security controls.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/conditional-access/policies/ca-no-policy-all-users.go",
	}
}

// Doc returns catalog metadata for NoRiskBasedSignInDetector.
func (*NoRiskBasedSignInDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Sign-In Risk-Based CA Policy",
		Description: "No CA policy uses sign-in risk levels. Risk-based policies provide adaptive security.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/conditional-access/policies/ca-no-risk-based-signin.go",
	}
}

// Doc returns catalog metadata for NoRiskBasedUserDetector.
func (*NoRiskBasedUserDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No User Risk-Based CA Policy",
		Description: "No CA policy uses user risk levels for adaptive protection.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/conditional-access/policies/ca-no-risk-based-user.go",
	}
}

// Doc returns catalog metadata for NoSessionControlsDetector.
func (*NoSessionControlsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No CA Policy with Session Controls",
		Description: "No CA policy configures session controls (sign-in frequency, persistent browser).",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/conditional-access/policies/ca-no-session-controls.go",
	}
}

// Doc returns catalog metadata for PolicyReportOnlyDetector.
func (*PolicyReportOnlyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Conditional Access Policies in Report-Only Mode",
		Description: "CA policies in report-only mode are not enforced. Review and enable them.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/conditional-access/policies/ca-policy-report-only.go",
	}
}
