// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package disa

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AccountPoliciesDetector.
func (*AccountPoliciesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DISA STIG Account Policies Non-Compliant",
		Description: "Account policies do not meet DISA STIG requirements for Windows Server.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/disa/account-policies.go",
	}
}

// Doc returns catalog metadata for AuditPoliciesDetector.
func (*AuditPoliciesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DISA STIG Audit Policies Non-Compliant",
		Description: "Audit policies do not meet DISA STIG requirements for Windows Server.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/disa/audit-policies.go",
	}
}
