// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package response

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for HighRiskUsersActiveDetector.
func (*HighRiskUsersActiveDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "High-Risk Users with Active Accounts",
		Description: "Users flagged as high risk still have active accounts. Investigate and remediate immediately.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/risk-protection/response/high-risk-users-active.go",
	}
}

// Doc returns catalog metadata for LeakedCredentialsNotBlockedDetector.
func (*LeakedCredentialsNotBlockedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Leaked Credentials Not Blocked",
		Description: "Users with confirmed compromised credentials are not blocked. Immediately remediate these accounts.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/risk-protection/response/leaked-credentials-not-blocked.go",
	}
}

// Doc returns catalog metadata for NoAutomatedResponseDetector.
func (*NoAutomatedResponseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Automated Risk Response",
		Description: "No CA policy automates response to user or sign-in risks. Configure automatic remediation.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/risk-protection/response/no-automated-response.go",
	}
}

// Doc returns catalog metadata for RiskySignInsNotInvestigatedDetector.
func (*RiskySignInsNotInvestigatedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Risky Sign-Ins Not Investigated",
		Description: "Risk detections have not been investigated. Each detection may indicate an active compromise.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/risk-protection/response/risky-signins-not-investigated.go",
	}
}

// Doc returns catalog metadata for RiskyUsersNotRemediatedDetector.
func (*RiskyUsersNotRemediatedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Risky Users Not Remediated",
		Description: "Users flagged as risky have not been remediated or dismissed. Active risks indicate compromised accounts.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/risk-protection/response/risky-users-not-remediated.go",
	}
}
