// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package other

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminSdHolderModifiedDetector.
func (*AdminSdHolderModifiedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AdminSDHolder Review Required",
		Description: "AdminSDHolder permissions should be reviewed. Modifications propagate to all protected accounts (Domain Admins, Enterprise Admins, etc.) via SDProp process.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/other/admin-sd-holder-modified.go",
	}
}

// Doc returns catalog metadata for AltSecurityIdentitiesDetector.
func (*AltSecurityIdentitiesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Accounts with altSecurityIdentities Configured",
		Description: "Privileged accounts have the altSecurityIdentities attribute configured, which maps external credentials (certificates, Kerberos principals) to AD accounts. This can be exploited for certificate-based impersonation attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/alt-security-identities.go",
	}
}

// Doc returns catalog metadata for BadSuccessorDMSADetector.
func (*BadSuccessorDMSADetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Delegated Managed Service Account (dMSA) Escalation Risk (BadSuccessor)",
		Description: "Users with CreateChild permissions on OUs could create delegated Managed Service Accounts (dMSA) that inherit the permissions of any existing account by setting it as a predecessor. This Windows Server 2025 vulnerability (CVE-2025-21293) allows privilege escalation to Domain Admin.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/other/badsuccessor-dmsa.go",
	}
}

// Doc returns catalog metadata for DCShadowDetector.
func (*DCShadowDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Evidence of Mimikatz DCShadow Attack",
		Description: "Domain Controller objects detected outside the standard Domain Controllers OU. This may indicate a DCShadow attack where rogue DCs were registered to inject malicious changes into the directory via replication.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/other/dcshadow.go",
	}
}

// Doc returns catalog metadata for DangerousLogonScriptsDetector.
func (*DangerousLogonScriptsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Dangerous Logon Scripts",
		Description: "Logon scripts with weak ACLs can be modified by attackers for code execution on user login.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/dangerous-logon-scripts.go",
	}
}

// Doc returns catalog metadata for DefaultPolicyChangedDetector.
func (*DefaultPolicyChangedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Default Domain Policy Modified",
		Description: "The Default Domain Policy or Default Domain Controllers Policy has been recently modified. Changes to these built-in GPOs affect all domain objects and should be carefully reviewed.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/default-policy-changed.go",
	}
}

// Doc returns catalog metadata for DelegationPrivilegeDetector.
func (*DelegationPrivilegeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Delegation Privilege",
		Description: "Account has SeEnableDelegationPrivilege. Can enable delegation on user/computer accounts.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/delegation-privilege.go",
	}
}

// Doc returns catalog metadata for DisplaySpecifiersChangesDetector.
func (*DisplaySpecifiersChangesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Display Specifier Objects Recently Modified",
		Description: "Display Specifier objects under CN=DisplaySpecifiers,CN=Configuration have been modified within the last 90 days. These objects control UI behavior in AD management tools and could be weaponized for code execution when admins open AD tools.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/display-specifiers-changes.go",
	}
}

// Doc returns catalog metadata for DsHeuristicsModifiedDetector.
func (*DsHeuristicsModifiedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "dsHeuristics Status Unknown",
		Description: "Unable to check dsHeuristics attribute.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/ds-heuristics-modified.go",
	}
}

// Doc returns catalog metadata for EphemeralAdminsDetector.
func (*EphemeralAdminsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Ephemeral Admin Accounts Detected (PAM Shadow Principals)",
		Description: "Shadow principal configuration detected, indicating Privileged Access Management (PAM) is in use with time-bound privileged group memberships. Review to ensure PAM configuration is intentional and properly managed.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/ephemeral-admins.go",
	}
}

// Doc returns catalog metadata for ExchangePrivEscPathDetector.
func (*ExchangePrivEscPathDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Exchange Privilege Escalation Risk",
		Description: "Users in Exchange security groups with potentially dangerous permissions. Exchange Trusted Subsystem has WriteDacl on domain by default (CVE-2019-1166).",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/other/exchange-priv-esc-path.go",
	}
}

// Doc returns catalog metadata for ForeignSecurityPrincipalsDetector.
func (*ForeignSecurityPrincipalsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Foreign Security Principals",
		Description: "Foreign security principals from external forests. Potential for cross-forest privilege escalation.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/foreign-security-principals.go",
	}
}

// Doc returns catalog metadata for GMSANotInUseDetector.
func (*GMSANotInUseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Group Managed Service Accounts (gMSA) Not in Use",
		Description: "No Group Managed Service Accounts (gMSA) are deployed in the domain despite having service accounts with SPNs. gMSA provides automatic password management and eliminates the risk of stale service account passwords.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/advanced/other/gmsa-not-used.go",
	}
}

// Doc returns catalog metadata for GMSAOldPasswordDetector.
func (*GMSAOldPasswordDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "gMSA Objects with Old Passwords",
		Description: "Group Managed Service Accounts with passwords that haven't rotated in over 60 days. gMSA passwords should auto-rotate per their managed password interval.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/gmsa-old-password.go",
	}
}

// Doc returns catalog metadata for NtlmRelayOpportunityDetector.
func (*NtlmRelayOpportunityDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NTLM Relay Opportunity",
		Description: "LDAP signing or channel binding not enforced. Enables NTLM relay attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/ntlm-relay-opportunity.go",
	}
}

// Doc returns catalog metadata for OUUnprotectedDetector.
func (*OUUnprotectedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Organizational Units Without Deletion Protection",
		Description: "Organizational Units (OUs) without 'Protect object from accidental deletion' enabled can be accidentally deleted, causing mass disruption.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/advanced/other/ou-unprotected.go",
	}
}

// Doc returns catalog metadata for PrivilegedGroupChangesDetector.
func (*PrivilegedGroupChangesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Group Membership Recently Changed",
		Description: "Members have been added to or removed from privileged groups (Domain Admins, Enterprise Admins, Schema Admins, etc.) within the last 7 days. Frequent changes may indicate compromise or unauthorized privilege escalation.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/privileged-group-changes.go",
	}
}

// Doc returns catalog metadata for RecentObjectsDetector.
func (*RecentObjectsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AD Objects Created Within the Last 10 Days",
		Description: "New Active Directory objects have been created recently. Review to ensure all new accounts, computers, and groups are authorized and properly configured.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/recent-objects.go",
	}
}

// Doc returns catalog metadata for RecentPrivilegedCreationDetector.
func (*RecentPrivilegedCreationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Recent Privileged Account Creation Activity",
		Description: "New privileged accounts have been created in the last 10 days. Unauthorized creation of administrative accounts may indicate compromise or insider threats.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/recent-privileged-creation.go",
	}
}

// Doc returns catalog metadata for SIDHistoryRecentDetector.
func (*SIDHistoryRecentDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Recent SIDHistory Changes on Objects",
		Description: "Users with SIDHistory attribute that were recently modified. SIDHistory changes can indicate domain migration activity or privilege escalation attempts by injecting SIDs.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/sidhistory-recent.go",
	}
}

// Doc returns catalog metadata for SIDHistoryWellKnownDetector.
func (*SIDHistoryWellKnownDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Well-Known Privileged SIDs in SIDHistory",
		Description: "Users with SIDHistory containing well-known privileged SIDs (Domain Admins, Enterprise Admins, etc.). This grants them the privileges of those groups even if they are not members, enabling privilege escalation and persistence.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/other/sidhistory-wellknown.go",
	}
}

// Doc returns catalog metadata for SchemaSDChangesDetector.
func (*SchemaSDChangesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Schema Security Descriptor Recently Modified",
		Description: "The security descriptor on the Active Directory Schema naming context has been modified within the last 90 days. Schema permission changes are rare in production and may indicate privilege escalation or unauthorized access.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/schema-sd-changes.go",
	}
}

// Doc returns catalog metadata for SmartcardRotationDetector.
func (*SmartcardRotationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Smart Card Password Rotation Disabled",
		Description: "Smart card users have passwords that haven't been rotated. When smart card password rotation is disabled, the underlying password remains static, making the account vulnerable if the password hash is compromised.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/smartcard-rotation.go",
	}
}
