// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package other

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminSdHolderModifiedDetector.
func (*AdminSdHolderModifiedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AdminSDHolder Review Required",
		Description: "AdminSDHolder permissions should be reviewed. Modifications propagate to all protected accounts (Domain Admins, Enterprise Admins, etc.) via SDProp process.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/other/admin-sd-holder-modified.go",
	}
}

// Doc returns catalog metadata for AltSecurityIdentitiesDetector.
func (*AltSecurityIdentitiesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Accounts with altSecurityIdentities Configured",
		Description: "Privileged accounts have the altSecurityIdentities attribute configured, which maps external credentials (certificates, Kerberos principals) to AD accounts. This can be exploited for certificate-based impersonation attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/alt-security-identities.go",
	}
}

// Doc returns catalog metadata for BadSuccessorDMSADetector.
func (*BadSuccessorDMSADetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Delegated Managed Service Account (dMSA) Escalation Risk (BadSuccessor)",
		Description: "Users with CreateChild permissions on OUs could create delegated Managed Service Accounts (dMSA) that inherit the permissions of any existing account by setting it as a predecessor (CVE-2025-53779, patched by Microsoft in the August 2025 security update). This requires at least one Windows Server 2025 domain controller in the domain.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/other/badsuccessor-dmsa.go",
	}
}

// Doc returns catalog metadata for DCShadowDetector.
func (*DCShadowDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Domain Controller Object Outside Standard OU",
		Description: "A computer object with the SERVER_TRUST_ACCOUNT flag (or an already-known domain controller) was found outside the standard OU=Domain Controllers container. This is ONE of several evidence classes MITRE ATT&CK T1207 associates with a DCShadow rogue-DC registration (object placement), not the full set - this detector does not inspect nTDSDSA/server object churn, the DRS replication SPN, replication RPC calls, or Kerberos telemetry, which are the other signals MITRE documents for this technique. Treat a hit as a directory anomaly to investigate, not as confirmed evidence of an attack.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/other/dcshadow.go",
	}
}

// Doc returns catalog metadata for DangerousLogonScriptsDetector.
func (*DangerousLogonScriptsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Logon Script Configured With Network Path",
		Description: "This account's logon script (scriptPath) references a network location (a UNC-style path) rather than a name resolved relative to NETLOGON. This detector only inspects the path string - it does not read the file, share, or NTFS ACL protecting that script, so it cannot confirm whether the location is actually writable by non-administrators. Per MITRE ATT&CK T1037.003, the real risk requires write access to the script; treat this as a review/precursor indicator, not a confirmed weak-ACL finding.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/dangerous-logon-scripts.go",
	}
}

// Doc returns catalog metadata for DefaultPolicyChangedDetector.
func (*DefaultPolicyChangedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Default Domain Policy Modified",
		Description: "The Default Domain Policy or Default Domain Controllers Policy has been recently modified. Changes to these built-in GPOs affect all domain objects and should be carefully reviewed.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/default-policy-changed.go",
	}
}

// Doc returns catalog metadata for DelegationPrivilegeDetector.
func (*DelegationPrivilegeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Delegation Privilege",
		Description: "Account has SeEnableDelegationPrivilege. Can enable delegation on user/computer accounts.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/delegation-privilege.go",
	}
}

// Doc returns catalog metadata for DisplaySpecifiersChangesDetector.
func (*DisplaySpecifiersChangesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Display Specifier Objects Recently Modified",
		Description: "Display Specifier objects under CN=DisplaySpecifiers,CN=Configuration have been modified within the last 90 days. These objects control UI behavior in AD management tools and could be weaponized for code execution when admins open AD tools.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/display-specifiers-changes.go",
	}
}

// Doc returns catalog metadata for DsHeuristicsModifiedDetector.
func (*DsHeuristicsModifiedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "dsHeuristics Status Unknown",
		Description: "Unable to check dsHeuristics attribute.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/ds-heuristics-modified.go",
	}
}

// Doc returns catalog metadata for EphemeralAdminsDetector.
func (*EphemeralAdminsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Ephemeral Admin Accounts Detected (PAM Shadow Principals)",
		Description: "A user, computer, or group memberOf value contains \"shadow principal\", suggesting Privileged Access Management (PAM) time-bound/shadow-principal group membership is in use. This is a substring-match heuristic on group membership, not a direct read of the CN=Shadow Principal Configuration container or its msDS-ShadowPrincipal objects. Review to confirm the PAM configuration is intentional and properly managed.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/ephemeral-admins.go",
	}
}

// Doc returns catalog metadata for ExchangePrivEscPathDetector.
func (*ExchangePrivEscPathDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Exchange Privilege Escalation Risk",
		Description: "Accounts in Exchange security groups with potentially dangerous permissions. 'Exchange Windows Permissions' has WriteDacl on the domain object by default (PrivExchange, CVE-2019-0686 / ADV190007); 'Exchange Trusted Subsystem' is a member of that group, and 'Exchange Servers' (the Exchange servers' own machine accounts) is nested inside it.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/other/exchange-priv-esc-path.go",
	}
}

// Doc returns catalog metadata for ForeignSecurityPrincipalsDetector.
func (*ForeignSecurityPrincipalsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Foreign Security Principals",
		Description: "Foreign security principal (FSP) placeholder objects exist in the domain. Some may represent real principals from a trusted external domain/forest (potential cross-forest exposure); Windows also creates the same kind of placeholder for well-known SIDs (Everyone, Authenticated Users, Anonymous Logon, ...) referenced in any ACL, which is normal and not itself a trust exposure. This count cannot distinguish the two - manually review each FSP's SID before treating it as a foreign-forest risk.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/foreign-security-principals.go",
	}
}

// Doc returns catalog metadata for GMSANotInUseDetector.
func (*GMSANotInUseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Group Managed Service Accounts (gMSA) Not in Use",
		Description: "No Group Managed Service Accounts (gMSA) are deployed in the domain despite having service accounts with SPNs. gMSA provides automatic password management and eliminates the risk of stale service account passwords.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/advanced/other/gmsa-not-used.go",
	}
}

// Doc returns catalog metadata for GMSAOldPasswordDetector.
func (*GMSAOldPasswordDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "gMSA Objects with Old Passwords",
		Description: "Group Managed Service Accounts with passwords that haven't rotated in over 60 days. gMSA passwords should auto-rotate per their managed password interval.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/gmsa-old-password.go",
	}
}

// Doc returns catalog metadata for NtlmRelayOpportunityDetector.
func (*NtlmRelayOpportunityDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "NTLM Relay Opportunity",
		Description: "LDAP signing or channel binding not enforced. Enables NTLM relay attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/ntlm-relay-opportunity.go",
	}
}

// Doc returns catalog metadata for OUUnprotectedDetector.
func (*OUUnprotectedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Organizational Units Without Deletion Protection",
		Description: "Organizational Units (OUs) without 'Protect object from accidental deletion' enabled can be accidentally deleted, causing mass disruption.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/advanced/other/ou-unprotected.go",
	}
}

// Doc returns catalog metadata for PrivilegedGroupChangesDetector.
func (*PrivilegedGroupChangesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Group Membership Recently Changed",
		Description: "Members have been added to or removed from privileged groups (Domain Admins, Enterprise Admins, Schema Admins, etc.) within the last 7 days. Frequent changes may indicate compromise or unauthorized privilege escalation.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/privileged-group-changes.go",
	}
}

// Doc returns catalog metadata for RecentObjectsDetector.
func (*RecentObjectsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AD Objects Created Within the Last 10 Days",
		Description: "New Active Directory objects have been created recently. Review to ensure all new accounts, computers, and groups are authorized and properly configured.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/recent-objects.go",
	}
}

// Doc returns catalog metadata for RecentPrivilegedCreationDetector.
func (*RecentPrivilegedCreationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Recent Privileged Account Creation Activity",
		Description: "New privileged accounts have been created in the last 10 days. Unauthorized creation of administrative accounts may indicate compromise or insider threats.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/recent-privileged-creation.go",
	}
}

// Doc returns catalog metadata for SIDHistoryRecentDetector.
func (*SIDHistoryRecentDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Recently Modified User Accounts Carrying SIDHistory",
		Description: "User accounts that carry a non-empty sIDHistory and were modified within the last 90 days. Active Directory does not expose a per-attribute last-modified timestamp for sIDHistory over LDAP, so whenChanged - which reflects ANY attribute change on the object, not specifically sIDHistory - is used as a proxy: a stable, long-migrated account that receives an unrelated edit (e.g. a phone number update) will also match. Computer objects are not evaluated by this detector.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/sidhistory-recent.go",
	}
}

// Doc returns catalog metadata for SIDHistoryWellKnownDetector.
func (*SIDHistoryWellKnownDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Well-Known Privileged SIDs in SIDHistory",
		Description: "Users with SIDHistory containing well-known privileged SIDs (Domain Admins, Enterprise Admins, etc.). This grants them the privileges of those groups even if they are not members, enabling privilege escalation and persistence.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/other/sidhistory-wellknown.go",
	}
}

// Doc returns catalog metadata for SchemaSDChangesDetector.
func (*SchemaSDChangesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Schema Security Descriptor Recently Modified",
		Description: "The security descriptor on the Active Directory Schema naming context has been modified within the last 90 days. Schema permission changes are rare in production and may indicate privilege escalation or unauthorized access.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/other/schema-sd-changes.go",
	}
}

// Doc returns catalog metadata for SmartcardRotationDetector.
func (*SmartcardRotationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Smart Card Password Rotation Disabled",
		Description: "Smart card users have passwords that haven't been rotated. When smart card password rotation is disabled, the underlying password remains static, making the account vulnerable if the password hash is compromised.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/other/smartcard-rotation.go",
	}
}
