// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package serviceprincipals

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for SPDisabledWithPermissionsDetector.
func (*SPDisabledWithPermissionsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Disabled Service Principals with Permissions",
		Description: "Disabled service principals still have permission grants. Remove permissions from unused SPs. Remove permissions or delete unused service principals.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/service-principals/sp-disabled-with-permissions.go",
	}
}

// Doc returns catalog metadata for SPExternalOrganizationDetector.
func (*SPExternalOrganizationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Principals from External Organizations",
		Description: "Service principals owned by external organizations have access to your tenant. Verify they require access to your tenant.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/service-principals/sp-external-organization.go",
	}
}

// Doc returns catalog metadata for SPHighPrivilegeDetector.
func (*SPHighPrivilegeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Principals with High Privilege Roles",
		Description: "Service principals assigned privileged directory roles. Use managed identities and apply least privilege.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/service-principals/sp-high-privilege.go",
	}
}

// Doc returns catalog metadata for SPNoOwnerDetector.
func (*SPNoOwnerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Principals Without Owner",
		Description: "Service principals without assigned owners cannot be properly managed. Assign owners to these service principals to ensure proper lifecycle management.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/service-principals/sp-no-owner.go",
	}
}

// Doc returns catalog metadata for SPStaleCredentialDetector.
func (*SPStaleCredentialDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Principals with Stale Credentials",
		Description: "Service principal credentials older than 1 year. Rotate credentials regularly. Implement regular credential rotation.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/service-principals/sp-stale-credential.go",
	}
}
