// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package adcs

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ESC10Detector.
func (*ESC10Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC10 - Certificate Mapping Enforcement (Manual Verification Required)",
		Description: "Not an automated finding: whether domain controllers reject weak certificate mappings depends on the StrongCertificateBindingEnforcement registry value on each DC, which is local to the DC and cannot be read via LDAP. This entry is a reminder to verify that setting manually - it does not confirm a vulnerability.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/adcs/esc10.go",
	}
}

// Doc returns catalog metadata for ESC11Detector.
func (*ESC11Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC11 - RPC Encryption Enforcement (Manual Verification Required)",
		Description: "Not an automated finding: RPC encryption enforcement for certificate enrollment (IF_ENFORCEENCRYPTICERTREQUEST) is a per-CA registry flag that cannot be read via LDAP, and it is enabled by default on Windows CAs. This entry is a reminder to verify it manually - it does not confirm a vulnerability.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/adcs/esc11.go",
	}
}

// Doc returns catalog metadata for ESC1Detector.
func (*ESC1Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC1 - Misconfigured Certificate Template",
		Description: "Certificate template allows enrollee to specify Subject Alternative Name (SAN) and has client authentication EKU, enabling privilege escalation to any user/computer.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/adcs/esc1.go",
	}
}

// Doc returns catalog metadata for ESC2Detector.
func (*ESC2Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC2 - Any Purpose Certificate Template",
		Description: "Certificate template has 'Any Purpose' EKU or no EKU constraints, allowing issued certificates to be used for any purpose including client authentication.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/adcs/esc2.go",
	}
}

// Doc returns catalog metadata for ESC3Detector.
func (*ESC3Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC3 - Enrollment Agent Certificate Template",
		Description: "Certificate template allows issuance of enrollment agent certificates, which can be used to enroll certificates on behalf of other users.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/adcs/esc3.go",
	}
}

// Doc returns catalog metadata for ESC4Detector.
func (*ESC4Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC4 - Certificate Template ACL Review Required",
		Description: "Certificate templates with authentication capability should be reviewed for overly permissive ACLs that allow non-admins to modify template properties.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/adcs/esc4.go",
	}
}

// Doc returns catalog metadata for ESC5Detector.
func (*ESC5Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC5 - PKI Object ACL Review Required",
		Description: "PKI-related AD objects should be reviewed for overly permissive ACLs that could allow non-admins to modify CA configuration or templates.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/adcs/esc5.go",
	}
}

// Doc returns catalog metadata for ESC8Detector.
func (*ESC8Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC8 - HTTP Web Enrollment Enabled",
		Description: "Certificate Authority web enrollment is accessible over HTTP, enabling NTLM relay attacks against certificate enrollment.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/adcs/esc8.go",
	}
}

// Doc returns catalog metadata for ESC9Detector.
func (*ESC9Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC9 - No Security Extension in Certificate Template",
		Description: "Certificate templates with the CT_FLAG_NO_SECURITY_EXTENSION flag set in msPKI-Enrollment-Flag issue certificates without the szOID_NTDS_CA_SECURITY_EXT SID extension. Combined with weak certificate mapping, this allows certificate impersonation attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/adcs/esc9.go",
	}
}
