// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package advanced

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DsHeuristicsLDAPSecurityDetector.
func (*DsHeuristicsLDAPSecurityDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "dsHeuristics LDAP Security Weakened",
		Description: "The dsHeuristics attribute contains settings that weaken LDAP security. Position 7 controls anonymous LDAP operations binding. When not set to '2', anonymous binds may be permitted, allowing unauthenticated enumeration of directory objects.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/ds-heuristics.go",
	}
}
