package helpers

import (
	"strings"

	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// tier0SeedRIDSuffixes is the RID-suffix table for well-known Active
// Directory Tier 0 admin groups, matched against types.Group.ObjectSID -
// never against sAMAccountName. A group's displayed name (and its
// sAMAccountName for every one of these builtin/default groups) is
// generated by the localized Windows Server setup program: "Domain
// Admins" becomes "Domänen-Admins" on a German-language DC. The RID
// portion of a well-known group's SID is not - Microsoft fixes it across
// every forest, language and Windows Server version.
//
// Source (live, verified 2026-09-25):
// https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers
// - "Well-known SIDs" table (S-1-5-32-* builtin RIDs) and "The following
// RIDs are relative to each domain" table (domain/root-domain RIDs).
//
//	-512 Domain Admins          S-1-5-<domain>-512
//	-518 Schema Admins          S-1-5-<root domain>-518
//	-519 Enterprise Admins      S-1-5-<root domain>-519
//	-526 Key Admins             S-1-5-<root domain>-526
//	-527 Enterprise Key Admins  S-1-5-<domain>-527
//	-544 Administrators         S-1-5-32-544 (builtin, identical on every DC)
//	-548 Account Operators      S-1-5-32-548
//	-549 Server Operators       S-1-5-32-549
//	-550 Print Operators        S-1-5-32-550
//	-551 Backup Operators       S-1-5-32-551
//
// Deliberately NOT included:
//
//   - -516 Domain Controllers. The same Microsoft page documents it as the
//     group of domain controller COMPUTER accounts, not an admin group; the
//     two real callers of this seed set (KERBEROASTING_RISK,
//     ANSSI_R40_NO_PSO_TIER0) both reason about admin USERS. This is also
//     the one entry types.PrivilegedSIDSuffixes carries beyond this table -
//     that shared map answers a different question ("is this trustee
//     dangerous enough to exclude from an ACL finding") and is deliberately
//     not reused as-is here.
//   - -525 Protected Users. It has a fixed, well-known RID like the ten
//     above - Microsoft's own page lists it - but it is excluded from the
//     seed set on purpose: Protected Users (S-1-5-<domain>-525) restricts
//     its members' authentication (no NTLM, no DES/RC4 pre-auth, no
//     delegation, 4h max TGT lifetime) - it does not grant them any
//     privilege. Membership in it is a protection applied TO an account,
//     not evidence that the account IS Tier 0. Source (live, verified
//     2026-09-25):
//     https://learn.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/protected-users-security-group
//     - its own "Protected Users group Active Directory properties" table
//     states, verbatim: "Default user rights | No default user rights" and
//     "Protected by AdminSDHolder? | No" - unlike every one of the ten RIDs
//     above, which the same family of pages documents as privilege-bearing.
var tier0SeedRIDSuffixes = map[string]string{
	"-512": "Domain Admins",
	"-518": "Schema Admins",
	"-519": "Enterprise Admins",
	"-526": "Key Admins",
	"-527": "Enterprise Key Admins",
	"-544": "Administrators",
	"-548": "Account Operators",
	"-549": "Server Operators",
	"-550": "Print Operators",
	"-551": "Backup Operators",
}

// tier0NameOnlySeeds are Tier 0 admin groups recognized by sAMAccountName
// because, unlike every entry in tier0SeedRIDSuffixes, they carry NO
// fixed, Microsoft-documented RID: DnsAdmins is created by the DNS Server
// role installer, and its RID is allocated dynamically by that domain's
// RID master at creation time - it differs from forest to forest and
// cannot be hardcoded. Checked against the same Microsoft "Well-known
// SIDs" page cited above (verified 2026-09-25): DnsAdmins does not appear
// in it at all, in either RID table.
//
// This is a known, explicit, permanent limitation (id_matching: mixed for
// the seed set as a whole), not an oversight: on a forest where DnsAdmins
// has been renamed, this seed silently fails to match, exactly like the
// pre-fix behavior for every other group in this file. There is no SID-
// based alternative to fall back to for this one group.
var tier0NameOnlySeeds = []string{
	"dnsadmins",
}

// maxRecursionDepth caps the recursive group expansion to prevent infinite
// loops on cyclic memberships and pathological forests.
const maxRecursionDepth = 10

// Tier0Members returns the lowercase DN set of all USERS considered Tier 0:
// direct and transitive members of the Tier 0 group set (see Tier0Groups)
// plus any custom group DNs supplied via customGroupDNs.
//
// v3.1.18 added a second source here: every user with AdminCount=1
// (AdminSDHolder-protected at its last SDProp cycle), regardless of current
// group membership. That source has been REMOVED: SDProp sets adminCount=1
// and never clears it automatically when the user leaves the protected
// group, so it does not mean "is Tier 0 today" - it means "was Tier 0 at
// some point in the past, maybe still is". Measured on a live lab forest:
// every Critical KERBEROASTING_RISK finding this source alone produced was
// an adminCount=1 orphan with zero current group membership - a population
// the SAME audit already reports, correctly, as ADMIN_COUNT_ORPHANED.
// Stale-adminCount detection belongs to that detector, which is designed
// for it (it distinguishes "orphaned" from "protected account, no
// membership needed" - krbtgt, Administrator); this helper's two real
// callers (KERBEROASTING_RISK and ANSSI_R40_NO_PSO_TIER0 - confirmed by
// grep, not assumed) are the wrong place to fold a freshness judgment into
// their severities.
func Tier0Members(data *audit.DetectorData, customGroupDNs []string) map[string]bool {
	out := map[string]bool{}
	if data == nil {
		return out
	}

	tier0Groups := Tier0Groups(data, customGroupDNs)
	visited := map[string]bool{}
	for groupDN := range tier0Groups {
		expandGroupMembers(data, groupDN, out, visited, 0)
	}

	return out
}

// Tier0Groups returns the lowercase DN set of all GROUPS considered Tier 0
// - the seed set used by Tier0Members for recursive member expansion.
//
// Sources:
//  1. Groups whose ObjectSID ends in one of tier0SeedRIDSuffixes (ID-based,
//     never localized) or whose sAMAccountName matches tier0NameOnlySeeds
//     (DnsAdmins only - no fixed RID exists to match on instead; see that
//     var's doc comment).
//  2. Groups whose DN is explicitly listed in customGroupDNs (case-insensitive).
//  3. Groups discovered transitively as nested members of (1) or (2).
//
// Use this when a detector needs to evaluate a control SCOPED to Tier 0
// containers (e.g. R23 - permissions on Tier 0 accounts and groups in AD).
func Tier0Groups(data *audit.DetectorData, customGroupDNs []string) map[string]bool {
	out := map[string]bool{}
	if data == nil {
		return out
	}

	// Index groups by DN for transitive expansion.
	byDN := map[string]types.Group{}
	for _, g := range data.Groups {
		byDN[strings.ToLower(g.DN)] = g
	}

	// Seed: RID-based match (ten well-known groups) + name-based match
	// (DnsAdmins only).
	for _, g := range data.Groups {
		if isTier0SeedRIDSuffix(g.ObjectSID) || isTier0NameOnlySeed(g.SAMAccountName) {
			out[strings.ToLower(g.DN)] = true
		}
	}
	// Seed: customer-supplied custom DNs (validated against actually-collected groups).
	for _, dn := range customGroupDNs {
		k := strings.ToLower(strings.TrimSpace(dn))
		if k == "" {
			continue
		}
		if _, ok := byDN[k]; ok {
			out[k] = true
		}
		// Silently skip DNs not present in data.Groups - they may simply
		// not exist anymore. Detectors using this helper log no-op.
	}

	// Transitive: any group nested inside a Tier 0 group is itself Tier 0.
	visited := map[string]bool{}
	queue := make([]string, 0, len(out))
	for k := range out {
		queue = append(queue, k)
	}
	for len(queue) > 0 {
		dn := queue[0]
		queue = queue[1:]
		if visited[dn] {
			continue
		}
		visited[dn] = true

		g, ok := byDN[dn]
		if !ok {
			continue
		}
		for _, memberDN := range g.Members {
			mk := strings.ToLower(memberDN)
			if _, isGroup := byDN[mk]; isGroup && !out[mk] {
				out[mk] = true
				queue = append(queue, mk)
			}
		}
	}

	return out
}

// isTier0SeedRIDSuffix reports whether a group's ObjectSID ends in one of
// the RID suffixes in tier0SeedRIDSuffixes. Matching is by SUFFIX, not
// substring containment from the start: "-1512" must not match "-512". A
// past version of the sibling table types.PrivilegedSIDSuffixes documented
// exactly this failure mode (see audit.IsBuiltinAdminTrustee), which is why
// this uses strings.HasSuffix rather than strings.Contains.
func isTier0SeedRIDSuffix(sid string) bool {
	s := strings.TrimSpace(sid)
	if s == "" {
		return false
	}
	for suffix := range tier0SeedRIDSuffixes {
		if strings.HasSuffix(s, suffix) {
			return true
		}
	}
	return false
}

// isTier0NameOnlySeed returns true when a group sAMAccountName matches one
// of tier0NameOnlySeeds (case-insensitive comparison). Currently just
// DnsAdmins - see that var's doc comment for why it cannot be matched by
// RID instead.
func isTier0NameOnlySeed(sam string) bool {
	s := strings.ToLower(strings.TrimSpace(sam))
	for _, n := range tier0NameOnlySeeds {
		if s == n {
			return true
		}
	}
	return false
}

// expandGroupMembers walks a group's direct members and recursively expands
// any nested group encountered. USER members are added to `out`; GROUP
// members trigger recursion. Bounded by maxRecursionDepth and `visited`.
func expandGroupMembers(data *audit.DetectorData, groupDN string, out, visited map[string]bool, depth int) {
	if depth > maxRecursionDepth {
		return
	}
	gk := strings.ToLower(groupDN)
	if visited[gk] {
		return
	}
	visited[gk] = true

	// Find the group object.
	var g *types.Group
	for i := range data.Groups {
		if strings.EqualFold(data.Groups[i].DN, groupDN) {
			g = &data.Groups[i]
			break
		}
	}
	if g == nil {
		return
	}

	// Build a quick "is this DN a known group?" lookup.
	groupSet := map[string]bool{}
	for _, gg := range data.Groups {
		groupSet[strings.ToLower(gg.DN)] = true
	}

	for _, memberDN := range g.Members {
		mk := strings.ToLower(memberDN)
		if groupSet[mk] {
			expandGroupMembers(data, memberDN, out, visited, depth+1)
		} else {
			// Treat as user/computer DN. Compliance Tier 0 detectors care
			// about user identities; computer accounts in admin groups are
			// uncommon and addressed elsewhere (DCSync detector).
			out[mk] = true
		}
	}
}
