// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package signing

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for LdapChannelBindingDisabledDetector.
func (*LdapChannelBindingDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LDAP Channel Binding Not Required",
		Description: "LDAP channel binding is not set to 'Always', leaving the domain vulnerable to LDAP relay attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/signing/ldap-channel-binding-disabled.go",
	}
}

// Doc returns catalog metadata for LdapSigningDisabledDetector.
func (*LdapSigningDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LDAP Signing Not Required",
		Description: "LDAP signing is not required on domain controllers, making the environment vulnerable to LDAP relay attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/signing/ldap-signing-disabled.go",
	}
}

// Doc returns catalog metadata for SmbSigningDisabledDetector.
func (*SmbSigningDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SMB Signing Not Required",
		Description: "SMB signing is not required on domain controllers, making the environment vulnerable to NTLM relay attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/signing/smb-signing-disabled.go",
	}
}

// Doc returns catalog metadata for SmbV1EnabledDetector.
func (*SmbV1EnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SMBv1 Enabled",
		Description: "SMBv1 is enabled on domain controllers. SMBv1 is deprecated and vulnerable to critical attacks (EternalBlue, WannaCry).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/signing/smb-v1-enabled.go",
	}
}
