// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package status

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AccountExpireSoonDetector.
func (*AccountExpireSoonDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Account Expiring Soon",
		Description: "User accounts set to expire within the next 30 days. Review if these expirations are intentional or if accounts need to be extended.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/status/account-expire-soon.go",
	}
}

// Doc returns catalog metadata for AdminLogonCountLowDetector.
func (*AdminLogonCountLowDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Admin Account with Low Logon Count",
		Description: "Administrative accounts (adminCount=1) with fewer than 5 logons. May indicate unused privileged accounts that should be reviewed or disabled.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/accounts/status/admin-logon-count-low.go",
	}
}

// Doc returns catalog metadata for Inactive365Detector.
func (*Inactive365Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Inactive 365+ Days",
		Description: "User accounts inactive for 365+ days. Should be disabled or deleted.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/status/inactive-365.go",
	}
}

// Doc returns catalog metadata for NeverLoggedOnDetector.
func (*NeverLoggedOnDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Never Logged On",
		Description: "Enabled user accounts that have never logged into the domain. May indicate orphaned accounts, provisioning issues, or unused accounts that should be disabled.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/status/never-logged-on.go",
	}
}

// Doc returns catalog metadata for StaleAccountDetector.
func (*StaleAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Stale Account (180+ Days)",
		Description: "Enabled user accounts inactive for 180+ days. Stale accounts increase attack surface and should be reviewed.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/status/stale-account.go",
	}
}
