// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package obsolete

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ObsoleteOS2003Detector.
func (*ObsoleteOS2003Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Obsolete OS: Windows Server 2003",
		Description: "Computers running Windows Server 2003, an unsupported operating system. No security patches available, making these systems highly vulnerable to exploitation.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/obsolete/obsolete-os.go",
	}
}

// Doc returns catalog metadata for ObsoleteOS2008Detector.
func (*ObsoleteOS2008Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Obsolete OS: Windows Server 2008",
		Description: "Computers running Windows Server 2008, an unsupported operating system. No security patches available, making these systems highly vulnerable to exploitation.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/obsolete/obsolete-os.go",
	}
}

// Doc returns catalog metadata for ObsoleteOSNTDetector.
func (*ObsoleteOSNTDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Obsolete OS: Windows NT/2000",
		Description: "Computers running Windows NT 4.0 or Windows 2000, extremely outdated and unsupported operating systems. These systems lack all modern security features and are trivially exploitable.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/obsolete/obsolete-os.go",
	}
}

// Doc returns catalog metadata for ObsoleteOSVistaDetector.
func (*ObsoleteOSVistaDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Obsolete OS: Windows Vista",
		Description: "Computers running Windows Vista, an unsupported operating system. No security patches available, making these systems highly vulnerable to exploitation.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/obsolete/obsolete-os.go",
	}
}

// Doc returns catalog metadata for ObsoleteOSXPDetector.
func (*ObsoleteOSXPDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Obsolete OS: Windows XP",
		Description: "Computers running Windows XP, an unsupported operating system. No security patches available, making these systems highly vulnerable to exploitation.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/obsolete/obsolete-os.go",
	}
}
