// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package governance

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for InvitationUnrestrictedDetector.
func (*InvitationUnrestrictedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Guest Invitation Policy Unrestricted",
		Description: "Any user can invite external guests. Restrict to admins or specific roles.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/guest-external/governance/guest-invitation-unrestricted.go",
	}
}

// Doc returns catalog metadata for NeverSignedInDetector.
func (*NeverSignedInDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Guest Users Never Signed In",
		Description: "Invited guests who never accepted or signed in. Remove pending invitations.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/guest-external/governance/guest-never-signed-in.go",
	}
}

// Doc returns catalog metadata for NoAccessReviewDetector.
func (*NoAccessReviewDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Guest Access Review Configured",
		Description: "No automated access reviews for guest users. Regular reviews prevent stale external access.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/guest-external/governance/guest-no-access-review.go",
	}
}

// Doc returns catalog metadata for NoExpirationPolicyDetector.
func (*NoExpirationPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Guest Account Expiration Policy",
		Description: "Guest accounts do not have automatic expiration. Set time-limited access for external users.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/guest-external/governance/guest-no-expiration-policy.go",
	}
}

// Doc returns catalog metadata for StaleGuest90Detector.
func (*StaleGuest90Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Stale Guest Accounts (90+ Days)",
		Description: "Guest user accounts inactive for 90+ days should be reviewed and removed.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/guest-external/governance/guest-stale-90-days.go",
	}
}
