// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package devices

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DeviceComplianceMissingDetector.
func (*DeviceComplianceMissingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Device Compliance Policy Missing",
		Description: "Managed devices without compliance policies. Non-compliant devices may access corporate resources without meeting security requirements.",
		Severity:    types.SeverityHigh,
		SourceFile:  "intune/devices/device-compliance-missing.go",
	}
}

// Doc returns catalog metadata for EncryptionNotEnforcedDetector.
func (*EncryptionNotEnforcedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Device Encryption Not Enforced",
		Description: "Managed devices without disk encryption requirements. Unencrypted devices risk data exposure if lost or stolen.",
		Severity:    types.SeverityHigh,
		SourceFile:  "intune/devices/encryption-not-enforced.go",
	}
}
