// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package serviceaccounts

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for InteractiveDetector.
func (*InteractiveDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Account with Interactive Logon",
		Description: "Service accounts appear to allow or use interactive logon. Service accounts should be restricted to service-only authentication.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/service-accounts/interactive.go",
	}
}

// Doc returns catalog metadata for NamingDetector.
func (*NamingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Account by Naming Convention",
		Description: "User accounts matching service account naming patterns (svc_, _svc, service, etc.) without SPN. Review if these are actual service accounts.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/service-accounts/naming.go",
	}
}

// Doc returns catalog metadata for NoPreauthDetector.
func (*NoPreauthDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Account Without Pre-Authentication (AS-REP Roasting)",
		Description: "Service accounts with 'Do not require Kerberos pre-authentication' enabled. Attackers can request AS-REP tickets and crack them offline.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/service-accounts/no-preauth.go",
	}
}

// Doc returns catalog metadata for OldPasswordDetector.
func (*OldPasswordDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Account with Old Password",
		Description: "Service accounts with passwords not changed in over 1 year. These accounts are high-value targets and passwords should be rotated regularly.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/service-accounts/old-password.go",
	}
}

// Doc returns catalog metadata for PrivilegedDetector.
func (*PrivilegedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Account in Privileged Group",
		Description: "Service accounts with membership in privileged groups (Domain Admins, etc.). If compromised, attackers gain full domain control.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/accounts/service-accounts/privileged.go",
	}
}

// Doc returns catalog metadata for WeakEncryptionDetector.
func (*WeakEncryptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Account Using Weak Kerberos Encryption",
		Description: "Service accounts configured to use only weak Kerberos encryption (DES/RC4) without AES. Makes offline cracking easier.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/service-accounts/weak-encryption.go",
	}
}

// Doc returns catalog metadata for WithSpnDetector.
func (*WithSpnDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Account with SPN (Kerberoasting Target)",
		Description: "User accounts with Service Principal Name configured. These accounts are targets for Kerberoasting attacks where attackers request TGS tickets and crack them offline.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/service-accounts/with-spn.go",
	}
}
