// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package status

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminCountDetector.
func (*AdminCountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer adminCount Set",
		Description: "Computer with adminCount attribute set to 1. May indicate current or former administrative privileges.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/computers/status/admin-count.go",
	}
}

// Doc returns catalog metadata for AdminCountOnDisabledAccountDetector.
func (*AdminCountOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer adminCount Set (Disabled Account)",
		Description: "Disabled computer account with adminCount attribute set to 1. Not a live administrative surface - the account cannot authenticate - but the residue indicates current or former administrative privileges and would matter again if the account is re-enabled.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/computers/status/admin-count-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for DCInactiveDetector.
func (*DCInactiveDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Inactive Domain Controller",
		Description: "One or more domain controllers have not authenticated in over 45 days. This may indicate a failed decommission, a replication break, or a rogue DC object. An inactive DC object can be hijacked to re-introduce a compromised machine.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/status/dc-inactive.go",
	}
}

// Doc returns catalog metadata for DisabledNotDeletedDetector.
func (*DisabledNotDeletedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Disabled Not Deleted",
		Description: "Disabled computer not deleted (>30 days, an etc-collector operational-hygiene benchmark rather than a named standard's requirement). Clutters AD, potential security oversight.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/computers/status/disabled-not-deleted.go",
	}
}

// Doc returns catalog metadata for NeverLoggedOnDetector.
func (*NeverLoggedOnDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Never Logged On",
		Description: "Enabled computer accounts that have never authenticated to the domain. These may be orphaned accounts from failed deployments or unused systems that should be cleaned up.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/computers/status/never-logged-on.go",
	}
}

// Doc returns catalog metadata for PasswordOldDetector.
func (*PasswordOldDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Password Old",
		Description: "Computer password not changed for 90+ days. Increases risk of password-based attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/status/password-old.go",
	}
}

// Doc returns catalog metadata for PreCreatedDetector.
func (*PreCreatedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Pre-Created (Staging)",
		Description: "Computer accounts with UAC flags PASSWD_NOTREQD and WORKSTATION_TRUST_ACCOUNT set. These are staging accounts pre-created but not yet joined to the domain. Should be reviewed and cleaned up.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/status/pre-created.go",
	}
}

// Doc returns catalog metadata for StaleInactiveDetector.
func (*StaleInactiveDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Stale/Inactive",
		Description: "Computer inactive for 90+ days. Orphaned computer accounts could be exploited without detection.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/status/stale-inactive.go",
	}
}
