// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package hds

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for HDS514AuthForteDetector.
func (*HDS514AuthForteDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS 5.1.4 — Authentification forte à vérifier hors AD",
		Description: "HDS 5.1.4 requires strong authentication for any account that may access health data. AD alone cannot confirm MFA enforcement; cross-check with Entra Conditional Access or third-party MFA.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/hds/hds_detectors.go",
	}
}

// Doc returns catalog metadata for HDS514PentestCadenceDetector.
func (*HDS514PentestCadenceDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS 5.14 — Vérifier la cadence de pentest annuel",
		Description: "HDS 5.14 requires periodic testing of the security measures (typically a yearly pentest). This finding is informational — verify with your CISO that the last AD pentest is less than 12 months old.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/hds/hds_detectors.go",
	}
}

// Doc returns catalog metadata for HDS52TLSEnforcedDetector.
func (*HDS52TLSEnforcedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS 5.2 — Vérifier le chiffrement de tout le trafic AD",
		Description: "HDS 5.2 requires strong encryption for all data in transit. Verify LDAPS-only on every DC (port 389 disabled or signing-required) and that LDAP_SIGNING / channel binding GPOs are enforced. Use 'etc-collector audit ad' TLSDiag output as evidence.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/hds/hds_detectors.go",
	}
}

// Doc returns catalog metadata for HDS54LogAccessHealthDetector.
func (*HDS54LogAccessHealthDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS 5.4 — Audit Object Access non configuré",
		Description: "HDS 5.4 requires traceability of access to health data. No GPO enables 'Audit Object Access' (success+failure), making file-level access logging incomplete.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/hds/hds_detectors.go",
	}
}

// Doc returns catalog metadata for HDS58DRPlanDetector.
func (*HDS58DRPlanDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS 5.8 — Plan de continuité AD insuffisant",
		Description: "HDS 5.8 requires a documented business continuity plan with redundant infrastructure. Detected %d domain controller(s); a single-DC forest cannot satisfy HDS BCP.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/hds/hds_detectors.go",
	}
}
