// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package hds

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for HDS514AuthForteDetector.
func (*HDS514AuthForteDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS - Authentification forte à vérifier hors AD",
		Description: "Strong authentication for accounts accessing health data is a standard expectation of HDS-certified environments. Référentiel HDS Exigences V1.1.20221027 does not set this out as a specific numbered requirement (its chapter 5 covers ISMS governance/process clauses 5.4-5.10, not per-topic technical controls). AD alone cannot confirm MFA enforcement; cross-check with Entra Conditional Access or third-party MFA.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/hds/hds-5-1-4-strong-auth.go",
	}
}

// Doc returns catalog metadata for HDS514PentestCadenceDetector.
func (*HDS514PentestCadenceDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS - Vérifier la cadence de pentest annuel",
		Description: "Periodic security testing (e.g. an annual penetration test) is part of the continuous-improvement process HDS-certified environments are expected to run (Référentiel HDS Exigences V1.1.20221027 §5.9 Evaluation des performances / §5.10 Amélioration), but the document does not set a specific numbered pentest-cadence requirement - this finding is purely informational. Verify with your CISO that the last AD pentest is less than 12 months old.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/hds/hds-5-14-pentest-cadence.go",
	}
}

// Doc returns catalog metadata for HDS52TLSEnforcedDetector.
func (*HDS52TLSEnforcedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS - Vérifier le chiffrement de tout le trafic AD",
		Description: "Encryption of data in transit is a standard expectation of HDS-certified environments. Référentiel HDS Exigences V1.1.20221027 does not set this out as a specific numbered chapter-5 requirement - the only related mention anywhere in the document is Annexe 2's SecNumCloud cross-reference matrix, where ISO 27001 Annex A control 5.14 'Transferts d'information' maps to SecNumCloud §10.2 'Chiffrement des flux' (a mapping-matrix entry, not an HDS exigence). Verify LDAPS-only on every DC (port 389 disabled or signing-required) and that LDAP_SIGNING / channel binding GPOs are enforced. Use 'etc-collector audit ad' TLSDiag output as evidence.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/hds/hds-5-2-tls-not-enforced.go",
	}
}

// Doc returns catalog metadata for HDS54LogAccessHealthDetector.
func (*HDS54LogAccessHealthDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS - Audit Object Access non configuré (Success et Failure)",
		Description: "Traceability of access to health data is a standard expectation of HDS-certified environments. Référentiel HDS Exigences V1.1.20221027 does not set this out as a specific numbered chapter-5 requirement (chapter 5 covers generic ISMS process clauses 5.4-5.10; the closest related mentions are the risk-factor list in §5.6.1.2 and the audit obligation in §5.9.2, neither of which mandates this specific GPO setting). No GPO enables 'Audit Object Access' for both Success and Failure, leaving file-level access logging incomplete.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/hds/hds-5-4-log-access-to-health-data.go",
	}
}

// Doc returns catalog metadata for HDS58DRPlanDetector.
func (*HDS58DRPlanDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "HDS - Plan de continuité AD insuffisant (heuristique)",
		Description: "A documented business continuity plan is a standard expectation of HDS-certified environments. Référentiel HDS Exigences V1.1.20221027 does not set this out as a specific numbered chapter-5 requirement (5.8 'Fonctionnement' is generic ISO 27001-style operational/risk-treatment planning, not a business-continuity mandate). HEURISTIC, not a direct measurement: this check uses domain-controller count as a rough, AD-observable proxy - a domain with %d co-located domain controller(s) and no real DR plan would still pass at >=2, while a well-planned single-DC deployment with off-domain backups still fails here. Treat as a prompt to verify manually, not a confirmed absence of continuity planning.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/hds/hds-5-8-dr-plan-missing.go",
	}
}
