// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package workspace

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DriveSharingExternalDetector.
func (*DriveSharingExternalDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "External Drive Sharing",
		Description: "Google Drive files shared externally or with public links. Unrestricted sharing may expose sensitive corporate data.",
		Severity:    types.SeverityMedium,
		SourceFile:  "google/workspace/drive-sharing-external.go",
	}
}

// Doc returns catalog metadata for OAuthOverprivilegedDetector.
func (*OAuthOverprivilegedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Overprivileged OAuth Applications",
		Description: "Third-party OAuth apps with excessive permissions. Overprivileged apps can access sensitive data across the organization.",
		Severity:    types.SeverityHigh,
		SourceFile:  "google/workspace/oauth-overprivileged.go",
	}
}

// Doc returns catalog metadata for TwoFANotEnforcedDetector.
func (*TwoFANotEnforcedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "2FA Not Enforced",
		Description: "Google Workspace users without 2-Step Verification. Accounts without 2FA are vulnerable to credential-based attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "google/workspace/two-fa-not-enforced.go",
	}
}
