// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package industry

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AuditLogRetentionDetector.
func (*AuditLogRetentionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Audit Log Retention Review Required",
		Description: "Audit log retention settings cannot be verified via LDAP (event log size/retention lives on each DC, not in the directory). This is a standing reminder to verify manually, not an automated detection - it does not indicate an actual finding either way. Ensure logs are retained for compliance requirements (typically 90-365 days depending on regulation). Related (not verified by this check): NIST AU-4 (Audit Storage Capacity), ANSSI Guide d'hygiène M36 (logs activated).",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/industry/audit-log-retention.go",
	}
}

// Doc returns catalog metadata for BackupNotVerifiedDetector.
func (*BackupNotVerifiedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "TODO_EXTRACTION_FAILED",
		Description: "Doc() metadata could not be extracted automatically; edit cataloggen or override manually.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/industry/backup-not-verified.go",
	}
}

// Doc returns catalog metadata for ChangeManagementBypassDetector.
func (*ChangeManagementBypassDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Change Management Compliance Review",
		Description: "Review privileged access to ensure change management processes cannot be easily bypassed.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/industry/change-management-bypass.go",
	}
}

// Doc returns catalog metadata for DataClassificationDetector.
func (*DataClassificationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Data Classification Review Required",
		Description: "Data classification implementation cannot be verified via LDAP. Ensure sensitive AD attributes and objects are properly classified.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/industry/data-classification.go",
	}
}

// Doc returns catalog metadata for EncryptionAtRestDetector.
func (*EncryptionAtRestDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Encryption at Rest Review Required",
		Description: "Encryption at rest status for AD data cannot be verified via LDAP. Ensure domain controllers use disk encryption.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/industry/encryption-at-rest.go",
	}
}

// Doc returns catalog metadata for MFANotEnforcedDetector.
func (*MFANotEnforcedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "MFA Not Enforced for Privileged Accounts",
		Description: "Multi-factor authentication is not enforced for all privileged accounts. Smartcard requirement should be enabled for admin accounts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/industry/mfa-not-enforced.go",
	}
}

// Doc returns catalog metadata for PrivilegedAccessReviewDetector.
func (*PrivilegedAccessReviewDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Access Review Required",
		Description: "Regular review of privileged access is required for compliance. Some privileged accounts show signs of inactivity.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/industry/privileged-access-review.go",
	}
}

// Doc returns catalog metadata for VendorAccountUnmonitoredDetector.
func (*VendorAccountUnmonitoredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Accounts With Vendor-Like Naming - Manual Review Suggested",
		Description: "SAMAccountName/description naming-pattern heuristic, not a monitoring-status check: these accounts contain words like 'vendor', 'contractor', or 'service' commonly used for external/third-party accounts. Whether they are actually monitored is not evaluated here - 'service' in particular tends to dominate matches with ordinary service accounts rather than real vendor accounts. Manually confirm which matches are genuine vendor/contractor accounts before acting.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/compliance/industry/vendor-account-unmonitored.go",
	}
}
