// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package industry

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AuditLogRetentionDetector.
func (*AuditLogRetentionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Audit Log Retention Review Required",
		Description: "Audit log retention settings cannot be verified via LDAP. Ensure logs are retained for compliance requirements (typically 90-365 days depending on regulation).",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/industry/audit-log-retention.go",
	}
}

// Doc returns catalog metadata for BackupNotVerifiedDetector.
func (*BackupNotVerifiedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AD Backup Verification Required",
		Description: "Active Directory backup verification status cannot be determined via LDAP. Ensure regular AD backups are performed and periodically tested.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/industry/backup-not-verified.go",
	}
}

// Doc returns catalog metadata for ChangeManagementBypassDetector.
func (*ChangeManagementBypassDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Change Management Compliance Review",
		Description: "Review privileged access to ensure change management processes cannot be easily bypassed.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/industry/change-management-bypass.go",
	}
}

// Doc returns catalog metadata for DataClassificationDetector.
func (*DataClassificationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Data Classification Review Required",
		Description: "Data classification implementation cannot be verified via LDAP. Ensure sensitive AD attributes and objects are properly classified.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/industry/data-classification.go",
	}
}

// Doc returns catalog metadata for EncryptionAtRestDetector.
func (*EncryptionAtRestDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Encryption at Rest Review Required",
		Description: "Encryption at rest status for AD data cannot be verified via LDAP. Ensure domain controllers use disk encryption.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/industry/encryption-at-rest.go",
	}
}

// Doc returns catalog metadata for MFANotEnforcedDetector.
func (*MFANotEnforcedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "MFA Not Enforced for Privileged Accounts",
		Description: "Multi-factor authentication is not enforced for all privileged accounts. Smartcard requirement should be enabled for admin accounts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/industry/mfa-not-enforced.go",
	}
}

// Doc returns catalog metadata for PrivilegedAccessReviewDetector.
func (*PrivilegedAccessReviewDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Access Review Required",
		Description: "Regular review of privileged access is required for compliance. Some privileged accounts show signs of inactivity.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/industry/privileged-access-review.go",
	}
}

// Doc returns catalog metadata for VendorAccountUnmonitoredDetector.
func (*VendorAccountUnmonitoredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Vendor Account Monitoring Review",
		Description: "Potential vendor/external accounts detected. Ensure these accounts are properly monitored and have limited access.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/industry/vendor-account-unmonitored.go",
	}
}
