// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package saml

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for SAMLCertExpiredDetector.
func (*SAMLCertExpiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SAML signing certificate expired",
		Description: "One or more service principals have an expired SAML SSO token-signing certificate. Federated sign-in through this SP will fail until the certificate is rotated.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/applications/saml/saml-certificate-health.go",
	}
}

// Doc returns catalog metadata for SAMLCertExpiringDetector.
func (*SAMLCertExpiringDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SAML signing certificate expiring within 30 days",
		Description: "One or more SAML token-signing certificates will expire within 30 days. Rotate and coordinate metadata updates with the relying party before expiry.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/saml/saml-certificate-health.go",
	}
}

// Doc returns catalog metadata for SAMLCertLongLifetimeDetector.
func (*SAMLCertLongLifetimeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SAML signing certificate has excessive lifetime",
		Description: "One or more SAML token-signing certificates are valid for more than 2 years. Long-lived signing credentials increase blast radius if compromised.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/saml/saml-certificate-health.go",
	}
}
