// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package critical

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for CertificateEscDetector.
func (*CertificateEscDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Certificate Template Escalation to Domain Admin",
		Description: "Vulnerable certificate templates (ESC1-like) allow users to request certificates for any user including Domain Admins.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/attack-paths/critical/certificate-esc.go",
	}
}
