// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package dangerous

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for CrossDomainSidDangerousACEDetector.
func (*CrossDomainSidDangerousACEDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Dangerous ACE Granted to an Unverifiable Cross-Domain SID",
		Description: "A grant ACE (GenericAll/full control, WriteDACL, WriteOwner or GenericWrite) names a trustee SID from a domain other than this one, with no matching well-known or domain-local principal. A legitimate cross-domain grant of this kind normally shows up here as a foreignSecurityPrincipal object — this collector currently only counts those (see domain summary), it does not enumerate their individual SIDs, so this exact SID cannot be confirmed against that count. It may be an intentional, still-active trust grant, or a stale reference left behind by a trust that was later removed or reconfigured — if the referenced domain is ever reachable again (trust re-established, its DC compromised), this SID can be forged via sIDHistory to inherit these rights immediately, with no dependency on RID recycling. Verify against the domain's current trust relationships before deciding whether to remove it.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/permissions/dangerous/orphaned-sid-ace.go",
	}
}

// Doc returns catalog metadata for DCSyncDetector.
func (*DCSyncDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DS-Replication-Get-Changes Rights (DCSync)",
		Description: "Non-standard principals with directory replication rights. Enables DCSync attacks to extract all password hashes from the domain.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/permissions/dangerous/dcsync.go",
	}
}

// Doc returns catalog metadata for DPAPIKeyACLDetector.
func (*DPAPIKeyACLDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Non-Default Access to DPAPI Master Key",
		Description: "Non-privileged principals have access to DPAPI master key objects. DPAPI keys protect credentials, certificates, and other secrets. Unauthorized access could allow decryption of protected data.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/dangerous/dpapi-key-acl.go",
	}
}

// Doc returns catalog metadata for EnterpriseKeyAdminsDetector.
func (*EnterpriseKeyAdminsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Enterprise Key Admins with Full Access to Domain",
		Description: "The Enterprise Key Admins group has write access to msDS-KeyCredentialLink attribute on domain objects. This allows Shadow Credentials attacks, enabling members to authenticate as any domain user or computer.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/dangerous/enterprise-key-admins.go",
	}
}

// Doc returns catalog metadata for GenericAllDetector.
func (*GenericAllDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ACL GenericAll",
		Description: "GenericAll permission on sensitive AD objects. Full control over object (reset passwords, modify groups, etc.).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/dangerous/genericall.go",
	}
}

// Doc returns catalog metadata for OrphanedSidDangerousACEDetector.
func (*OrphanedSidDangerousACEDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Dangerous ACE Granted to an Orphaned Local SID",
		Description: "A grant ACE (GenericAll/full control, WriteDACL, WriteOwner or GenericWrite) names a trustee SID whose domain prefix belongs to this domain, but which resolves to no user, group, computer, OU or well-known principal — most likely a deleted account whose access control entries were never cleaned up. Nobody can currently exercise this grant through a normal logon, but the stale ACE should still be removed: AD does not recycle RIDs in normal operation, so unlike a live account this SID cannot simply be renamed or reset — reclaiming it would require sIDHistory injection, which itself presupposes prior privileged access.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/dangerous/orphaned-sid-ace.go",
	}
}

// Doc returns catalog metadata for ReanimateTombstonesDetector.
func (*ReanimateTombstonesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Objects with Reanimate-Tombstones Extended Right",
		Description: "Non-privileged principals have the Reanimate-Tombstones extended right. This allows restoring deleted objects from the AD recycle bin or tombstone, potentially recovering sensitive or previously removed accounts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/dangerous/reanimate-tombstones.go",
	}
}

// Doc returns catalog metadata for SchemaPermissionsDetector.
func (*SchemaPermissionsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Non-Standard Schema Permissions",
		Description: "Non-privileged principals have write or modify permissions on the Active Directory schema. Schema modifications are irreversible and affect the entire forest, representing a critical risk.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/dangerous/schema-permissions.go",
	}
}

// Doc returns catalog metadata for SelfMembershipDetector.
func (*SelfMembershipDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Self-Membership Rights",
		Description: "Principals with self-membership rights on groups. Allows adding oneself to a group, potentially gaining elevated privileges.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/dangerous/self-membership.go",
	}
}

// Doc returns catalog metadata for ServerTrustAccountDetector.
func (*ServerTrustAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Users with Rights to Set Server Trust Account",
		Description: "Non-privileged principals can modify the userAccountControl attribute to set the SERVER_TRUST_ACCOUNT flag. This could allow creating rogue domain controllers for DCShadow attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/permissions/dangerous/server-trust-account.go",
	}
}

// Doc returns catalog metadata for WriteDACLDetector.
func (*WriteDACLDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ACL WriteDACL",
		Description: "WriteDACL permission on sensitive AD objects. Can modify object's security descriptor to grant additional permissions.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/dangerous/writedacl.go",
	}
}

// Doc returns catalog metadata for WriteOwnerDetector.
func (*WriteOwnerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ACL WriteOwner",
		Description: "WriteOwner permission on sensitive AD objects. Can take ownership of object and modify permissions.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/dangerous/writeowner.go",
	}
}
