// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package licensing

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for NoP2LicenseDetector.
func (*NoP2LicenseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Azure AD P2 License Not Active",
		Description: "Advisory: Key security features (PIM, Identity Protection, Access Reviews) require Azure AD P2 licensing.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/compliance/licensing/no-p2-license.go",
	}
}

// Doc returns catalog metadata for P2NotFullyUtilizedDetector.
func (*P2NotFullyUtilizedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Azure AD P2 Features Not Fully Utilized",
		Description: "P2 is licensed but key P2-gated features are unused: .",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/compliance/licensing/p2-not-fully-utilized.go",
	}
}
