// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package controls

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for NoLocationBlockDetector.
func (*NoLocationBlockDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Location-Based Access Blocking",
		Description: "No CA policy uses location conditions to block access from untrusted locations.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/conditional-access/controls/ca-no-location-block.go",
	}
}

// Doc returns catalog metadata for NoNamedLocationsDetector.
func (*NoNamedLocationsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Named Locations Defined",
		Description: "No named locations configured for use in CA policies. Named locations enable location-based access control.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/conditional-access/controls/ca-no-named-locations.go",
	}
}

// Doc returns catalog metadata for NoPlatformFilterDetector.
func (*NoPlatformFilterDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Platform-Based CA Policy",
		Description: "No CA policy filters by device platform. Platform filtering can enforce platform-specific controls.",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/conditional-access/controls/ca-no-platform-filter.go",
	}
}

// Doc returns catalog metadata for NoTrustedLocationsDetector.
func (*NoTrustedLocationsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Trusted Locations Configured",
		Description: "No named locations are marked as trusted. Trusted locations help reduce MFA friction for known networks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/conditional-access/controls/ca-no-trusted-locations.go",
	}
}

// Doc returns catalog metadata for PersistentBrowserEnabledDetector.
func (*PersistentBrowserEnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Persistent Browser Session Allowed",
		Description: "CA policies allow persistent browser sessions. Users remain signed in indefinitely on shared devices.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/conditional-access/controls/ca-persistent-browser.go",
	}
}

// Doc returns catalog metadata for TokenProtectionDisabledDetector.
func (*TokenProtectionDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Token Protection Not Configured",
		Description: "No CA policy enables token protection (token binding). Token theft allows session hijacking.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/conditional-access/controls/ca-token-protection.go",
	}
}
