// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package emergency

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for EmergencyCredentialStaleDetector.
func (*EmergencyCredentialStaleDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Emergency Account Credential Hygiene Cannot Be Verified",
		Description: "Emergency access account credentials could not be verified against Microsoft's current guidance. Use phishing-resistant, non-expiring credentials (passkey/FIDO2 or certificate-based authentication) for break-glass accounts rather than passwords, and validate at least every 90 days that the accounts still work.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/privileged-access/emergency/emergency-credential-stale.go",
	}
}

// Doc returns catalog metadata for EmergencyNoExclusionDetector.
func (*EmergencyNoExclusionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Emergency Accounts Not Excluded from CA",
		Description: "CA policies targeting all users do not exclude any accounts. Break-glass accounts must be excluded from CA policies to prevent lockout. Configure emergency access accounts and exclude them from all CA policies.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/privileged-access/emergency/emergency-no-ca-exclusion.go",
	}
}

// Doc returns catalog metadata for NoEmergencyAccountsDetector.
func (*NoEmergencyAccountsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Emergency Access Accounts Detected",
		Description: "No break-glass/emergency access accounts found: fewer than two accounts hold a permanent Global Administrator assignment and are excluded from all-users Conditional Access policies. Emergency accounts prevent lockout during CA policy misconfigurations or Azure AD outages. Create 2+ cloud-only accounts, permanently assigned Global Administrator, and exclude them from CA policies that block or restrict sign-in.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/privileged-access/emergency/no-emergency-accounts.go",
	}
}
