// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package emergency

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for EmergencyCredentialStaleDetector.
func (*EmergencyCredentialStaleDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Emergency Account Credentials May Be Stale",
		Description: "Emergency access account credentials should be tested and rotated regularly. Establish a process to test break-glass accounts quarterly and rotate credentials every 90-180 days to ensure they work when needed.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/privileged-access/emergency/emergency-credential-stale.go",
	}
}

// Doc returns catalog metadata for EmergencyNoExclusionDetector.
func (*EmergencyNoExclusionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Emergency Accounts Not Excluded from CA",
		Description: "CA policies targeting all users do not exclude any accounts. Break-glass accounts must be excluded from CA policies to prevent lockout. Configure emergency access accounts and exclude them from all CA policies.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/privileged-access/emergency/emergency-no-ca-exclusion.go",
	}
}

// Doc returns catalog metadata for EmergencyNoMonitoringDetector.
func (*EmergencyNoMonitoringDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Emergency Account Usage Not Monitored",
		Description: "No alerts configured for emergency account sign-ins. Usage of break-glass accounts must be monitored and investigated immediately. Configure Azure Monitor alerts for sign-ins by emergency access accounts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/privileged-access/emergency/emergency-no-monitoring.go",
	}
}

// Doc returns catalog metadata for NoEmergencyAccountsDetector.
func (*NoEmergencyAccountsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Emergency Access Accounts Detected",
		Description: "No break-glass/emergency access accounts found. Emergency accounts prevent lockout during CA policy misconfigurations or Azure AD outages. Create 2+ cloud-only accounts excluded from all CA policies.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/privileged-access/emergency/no-emergency-accounts.go",
	}
}
