// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package moderate

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AddMemberDetector.
func (*AddMemberDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Add-Member Rights on Groups",
		Description: "Principals with rights to add members to groups. Can be abused to add accounts to privileged groups.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/permissions/moderate/add-member.go",
	}
}

// Doc returns catalog metadata for AdminSDHolderBackdoorDetector.
func (*AdminSDHolderBackdoorDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AdminSDHolder Backdoor",
		Description: "Unexpected ACL on AdminSDHolder object. Persistent permissions on admin accounts.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/permissions/moderate/adminsdholder-backdoor.go",
	}
}

// Doc returns catalog metadata for EveryoneInACLDetector.
func (*EveryoneInACLDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Everyone in ACL",
		Description: "Everyone or Authenticated Users with write permissions in ACL. Overly permissive access.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/permissions/moderate/everyone-in-acl.go",
	}
}

// Doc returns catalog metadata for GPOLinkPoisoningDetector.
func (*GPOLinkPoisoningDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "GPO Link Poisoning",
		Description: "Weak ACLs on Group Policy Objects. Can modify GPO to execute code on targeted systems.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/permissions/moderate/gpo-link-poisoning.go",
	}
}

// Doc returns catalog metadata for GenericWriteDetector.
func (*GenericWriteDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ACL GenericWrite",
		Description: "GenericWrite permission on sensitive AD objects. Can modify many object attributes.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/permissions/moderate/genericwrite.go",
	}
}

// Doc returns catalog metadata for UserForceChangePasswordDetector.
func (*UserForceChangePasswordDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "User-Force-Change-Password Rights",
		Description: "Principals with rights to force password change on user accounts. Can reset passwords to take over accounts.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/permissions/moderate/force-change-password.go",
	}
}

// Doc returns catalog metadata for WritePropertyExtendedDetector.
func (*WritePropertyExtendedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Extended Write Property Rights",
		Description: "Principals with dangerous extended write property rights. Can modify script paths, home directories, or key credentials.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/permissions/moderate/write-property-extended.go",
	}
}

// Doc returns catalog metadata for WriteSPNAbuseDetector.
func (*WriteSPNAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Write SPN Abuse",
		Description: "WriteProperty permission for servicePrincipalName attribute. Can set SPNs for targeted Kerberoasting.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/permissions/moderate/writespn-abuse.go",
	}
}

// Doc returns catalog metadata for WriteValidatedDNSDetector.
func (*WriteValidatedDNSDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Validated-Write-DNS on Computers",
		Description: "Principals with rights to modify DNS host names on computer objects. Can be used for DNS spoofing and MITM attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/permissions/moderate/write-validated-dns.go",
	}
}
