// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package password

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for CannotChangeDetector.
func (*CannotChangeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "User Cannot Change Password",
		Description: "User accounts denied the User-Change-Password extended right for Everyone or NT AUTHORITY\\SELF, preventing self-service password rotation. Detects the real AD DS representation (Deny ACEs on the Change-Password extended right); does not depend on the userAccountControl bit, which real AD DS never sets over LDAP.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/password/cannot-change.go",
	}
}

// Doc returns catalog metadata for CleartextStorageDetector.
func (*CleartextStorageDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Cleartext Password Storage",
		Description: "User accounts with attributes that may store passwords in cleartext or reversible format. These attributes (userPassword, unixUserPassword) can be read by attackers with LDAP access.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/password/cleartext-storage.go",
	}
}

// Doc returns catalog metadata for CommonPatternsDetector.
func (*CommonPatternsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Common Password Pattern Risk",
		Description: "User accounts with names suggesting default or commonly-used passwords (admin, test, user, temp). These accounts are primary targets for password spraying attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/password/common-patterns.go",
	}
}

// Doc returns catalog metadata for DictAttackRiskDetector.
func (*DictAttackRiskDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Dictionary Attack Risk",
		Description: "User accounts showing signs of password guessing attacks (multiple bad password attempts or lockouts). May indicate weak passwords being targeted or ongoing brute-force attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/password/dict-attack-risk.go",
	}
}

// Doc returns catalog metadata for InDescriptionDetector.
func (*InDescriptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password in Description",
		Description: "User accounts with passwords or password-like strings in the description field. Cleartext credential exposure.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/password/in-description.go",
	}
}

// Doc returns catalog metadata for NeverExpiresDetector.
func (*NeverExpiresDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password Never Expires",
		Description: "Enabled user accounts with passwords set to never expire (UAC flag 0x10000). A compromised password on these accounts remains valid indefinitely.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/password/never-expires.go",
	}
}

// Doc returns catalog metadata for NeverExpiresOnDisabledAccountDetector.
func (*NeverExpiresOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password Never Expires (Disabled Account)",
		Description: "Disabled user accounts with passwords set to never expire (UAC flag 0x10000). Not usable while disabled, but the configuration survives a re-enable.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/password/never-expires-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for NotRequiredDetector.
func (*NotRequiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password Not Required",
		Description: "Enabled user accounts where the password-length policy does not apply (UAC flag 0x20, MS-ADTS 2.2.16): the account can be assigned an empty password, but this detector does not read whether the current password actually is one. Interdomain trust accounts (UAC flag 0x800) are excluded: Windows sets this flag on them by default, and their secret is managed by the system (KB 305144).",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/password/not-required.go",
	}
}

// Doc returns catalog metadata for NotRequiredOnDisabledAccountDetector.
func (*NotRequiredOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password Not Required (Disabled Account)",
		Description: "Disabled user accounts where the password-length policy does not apply (UAC flag 0x20, MS-ADTS 2.2.16). Not usable while disabled, but the configuration survives a re-enable, and this detector does not read whether the current password actually is empty. Interdomain trust accounts (UAC flag 0x800) are excluded: Windows sets this flag on them by default (KB 305144).",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/password/not-required-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for PasswordInDescriptionOnDisabledAccountDetector.
func (*PasswordInDescriptionOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password in Description (Disabled Account)",
		Description: "Disabled user accounts with passwords or password-like strings in the description field. Not usable to log on today - UF_ACCOUNTDISABLE blocks authentication for this account across every protocol - but the plaintext value remains readable on the object and would matter again if the account is re-enabled.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/password/in-description-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for ReversibleEncryptionDetector.
func (*ReversibleEncryptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Reversible Encryption",
		Description: "Passwords stored with reversible encryption (UAC flag 0x80, ENCRYPTED_TEXT_PASSWORD_ALLOWED). Equivalent to storing the password in cleartext in the directory. The exposure is at rest, not tied to authentication: disabling the account does not clear the stored reversible secret, and a re-enable restores its full usefulness immediately.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/password/reversible-encryption.go",
	}
}

// Doc returns catalog metadata for ServiceAccountPasswordPolicyDetector.
func (*ServiceAccountPasswordPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Strong Password Policy for Service Accounts",
		Description: "No Fine-Grained Password Policy with MinimumPasswordLength >= 20 applies to service accounts. Service accounts should have long, complex passwords since they cannot use MFA and are primary targets for Kerberoasting.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/password/service-account-password-policy.go",
	}
}

// Doc returns catalog metadata for VeryOldDetector.
func (*VeryOldDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password Very Old",
		Description: "User accounts with passwords older than 365 days. Increases risk of credential compromise.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/password/very-old.go",
	}
}
