// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package password

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for CannotChangeDetector.
func (*CannotChangeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "User Cannot Change Password",
		Description: "User accounts forbidden from changing their own password (UAC flag 0x40). Prevents password rotation.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/password/cannot-change.go",
	}
}

// Doc returns catalog metadata for CleartextStorageDetector.
func (*CleartextStorageDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Cleartext Password Storage",
		Description: "User accounts with attributes that may store passwords in cleartext or reversible format. These attributes (userPassword, unixUserPassword) can be read by attackers with LDAP access.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/password/cleartext-storage.go",
	}
}

// Doc returns catalog metadata for CommonPatternsDetector.
func (*CommonPatternsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Common Password Pattern Risk",
		Description: "User accounts with names suggesting default or commonly-used passwords (admin, test, user, temp). These accounts are primary targets for password spraying attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/password/common-patterns.go",
	}
}

// Doc returns catalog metadata for DictAttackRiskDetector.
func (*DictAttackRiskDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Dictionary Attack Risk",
		Description: "User accounts showing signs of password guessing attacks (multiple bad password attempts or lockouts). May indicate weak passwords being targeted or ongoing brute-force attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/password/dict-attack-risk.go",
	}
}

// Doc returns catalog metadata for InDescriptionDetector.
func (*InDescriptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password in Description",
		Description: "User accounts with passwords or password-like strings in the description field. Cleartext credential exposure.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/password/in-description.go",
	}
}

// Doc returns catalog metadata for NeverExpiresDetector.
func (*NeverExpiresDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password Never Expires",
		Description: "User accounts with passwords set to never expire (UAC flag 0x10000). Old passwords increase breach risk.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/password/never-expires.go",
	}
}

// Doc returns catalog metadata for NotRequiredDetector.
func (*NotRequiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password Not Required",
		Description: "User accounts that do not require a password (UAC flag 0x20). Attackers can authenticate without credentials.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/password/not-required.go",
	}
}

// Doc returns catalog metadata for ReversibleEncryptionDetector.
func (*ReversibleEncryptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Reversible Encryption",
		Description: "Passwords stored with reversible encryption (UAC flag 0x80). Equivalent to storing passwords in cleartext.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/password/reversible-encryption.go",
	}
}

// Doc returns catalog metadata for ServiceAccountPasswordPolicyDetector.
func (*ServiceAccountPasswordPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Strong Password Policy for Service Accounts",
		Description: "No Fine-Grained Password Policy with MinimumPasswordLength >= 20 applies to service accounts. Service accounts should have long, complex passwords since they cannot use MFA and are primary targets for Kerberoasting.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/password/service-account-password-policy.go",
	}
}

// Doc returns catalog metadata for VeryOldDetector.
func (*VeryOldDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password Very Old",
		Description: "User accounts with passwords older than 365 days. Increases risk of credential compromise.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/password/very-old.go",
	}
}
