// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package other

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DescriptionSensitiveDetector.
func (*DescriptionSensitiveDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Description Sensitive",
		Description: "Computer description contains sensitive data (passwords, IPs, etc.). Information disclosure.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/other/description-sensitive.go",
	}
}

// Doc returns catalog metadata for PreWindows2000Detector.
func (*PreWindows2000Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Windows 95/98 Computer",
		Description: "Windows 95/98 compatible computer object. Weak security settings, potential compatibility exploits. Windows NT/2000 is reported separately by COMPUTER_OS_OBSOLETE_NT.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/other/pre-windows-2000.go",
	}
}
