// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package certificates

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for CBAPersistenceDetector.
func (*CBAPersistenceDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Active certificate-based authentication on applications",
		Description: "One or more app registrations or service principals have active (non-expired) certificate credentials. Certificate-based authentication provides a persistence vector that survives password resets. Review each certificate's ownership and necessity.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/certificates/cba-persistence.go",
	}
}
