// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package security

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ImplicitFlowEnabledTenantDetector.
func (*ImplicitFlowEnabledTenantDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Implicit Flow Allowed Tenant-Wide",
		Description: "OAuth implicit flow is not blocked at the tenant level. Implicit flow tokens are exposed in URLs.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/config/security/implicit-flow-enabled-tenant.go",
	}
}

// Doc returns catalog metadata for SecurityDefaultsDisabledDetector.
func (*SecurityDefaultsDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Security Defaults Disabled",
		Description: "Azure AD Security Defaults are disabled. Security Defaults provide baseline protection including MFA.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/config/security/security-defaults-disabled.go",
	}
}

// Doc returns catalog metadata for SecurityDefaultsNoCADetector.
func (*SecurityDefaultsNoCADetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Security Defaults Disabled Without CA Policies",
		Description: "Security Defaults are disabled but no Conditional Access policies replace them.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/config/security/security-defaults-no-ca.go",
	}
}
