// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package compliance

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ScoreDetector.
func (*ScoreDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Compliance Score Assessment",
		Description: "Overall compliance score based on detected policy settings and configurations.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/score.go",
	}
}
