// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package compliance

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ScoreDetector.
func (*ScoreDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Partial Compliance Score (password policy + admin count only)",
		Description: "Product-level score computed from 5 signals only: password length/history/age, lockout policy, and Domain Admins count. It is NOT an overall compliance assessment - a high score here does not mean other compliance detectors (CIS, DISA, ANSSI, NIST, industry) are also passing; they check independent controls this score does not evaluate.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/compliance/score.go",
	}
}
