// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package hybrid

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for HybridCloudOnlyPrivilegedDetector.
func (*HybridCloudOnlyPrivilegedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "On-Prem-Synced Account Holds Privileged Role",
		Description: "One or more privileged role assignments target accounts synced from on-premises Active Directory. Microsoft recommends privileged (Tier 0) accounts be cloud-only with no ties to on-premises AD, precisely because a synced privileged account can be reached by compromising the on-prem AD it syncs from.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/hybrid/hybrid-sync-health.go",
	}
}

// Doc returns catalog metadata for HybridOrphanedCloudUserDetector.
func (*HybridOrphanedCloudUserDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Disabled Hybrid-Synced User Account",
		Description: "Cloud user accounts flagged as on-prem synced are in a disabled state in Entra ID. This is a routine hygiene signal, not a proven sync failure: a disabled synced account is the normal, expected state right after on-prem offboarding. Review the list to confirm each disablement was intentional and, where it wasn't, investigate the on-prem sync.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/hybrid/hybrid-sync-health.go",
	}
}
