// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package hybrid

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for HybridCloudOnlyPrivilegedDetector.
func (*HybridCloudOnlyPrivilegedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Cloud-only user assigned to privileged role",
		Description: "One or more privileged role assignments target cloud-only user accounts (no on-premises sync). In hybrid tenants this can be intentional for break-glass accounts, but otherwise represents a gap in the usual tier-0 governance.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/hybrid/hybrid-sync-health.go",
	}
}

// Doc returns catalog metadata for HybridOrphanedCloudUserDetector.
func (*HybridOrphanedCloudUserDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Potentially orphaned hybrid cloud user",
		Description: "Cloud user accounts flagged as on-prem synced are in a disabled state in Entra ID. These may be leftovers from an on-prem deletion where Connect failed to remove the cloud object, leaving a stale synced identity.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/hybrid/hybrid-sync-health.go",
	}
}
