// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package organization

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for OUInventoryDetector.
func (*OUInventoryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Organizational Unit",
		Description: "Inventory entry — exposes the OU as a first-class asset to the SaaS (linked GPOs, direct-child census, delegations).",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/permissions/organization/ou-inventory.go",
	}
}
