// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package patterns

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for PrimaryGroupIdSpoofingDetector.
func (*PrimaryGroupIdSpoofingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "primaryGroupID Spoofing",
		Description: "User accounts with non-standard primaryGroupID. Can be used to hide group membership.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/patterns/primarygroupid-spoofing.go",
	}
}

// Doc returns catalog metadata for SharedAccountDetector.
func (*SharedAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Shared Account",
		Description: "User accounts with shared/generic naming. Prevents proper accountability.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/patterns/shared-account.go",
	}
}

// Doc returns catalog metadata for TestAccountDetector.
func (*TestAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Test Account",
		Description: "User accounts with test/demo/temp naming. Should be removed from production.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/patterns/test-account.go",
	}
}
