// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package anssi

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for BP039CCINotDeployedDetector.
func (*BP039CCINotDeployedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI BP-039 R6/R7 — Configurable Code Integrity (CCI/WDAC) not deployed",
		Description: "ANSSI BP-039 R6 (sensitive workstations) and R7 (other workstations) recommend deploying Configurable Code Integrity / WDAC. No GPO references CodeIntegrity\\ConfigCIPolicyFilePath nor sets DeviceGuard\\RequirePlatformSecurityFeatures, so kernel-mode + user-mode binaries aren't constrained to a signed allowlist.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/compliance/anssi/bp039_phase_c.go",
	}
}

// Doc returns catalog metadata for BP039CredGuardLimitedScopeDetector.
func (*BP039CredGuardLimitedScopeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI BP-039 R10** — Credential Guard scope appears limited",
		Description: "ANSSI BP-039 R10** recommends Credential Guard on ALL workstations (R10* is the lower-bar variant for sensitive ones only). No GPO with LsaCfgFlags>=1 is linked at the domain root, so deployment is restricted to a subset of OUs. Link the Credential Guard GPO at the domain root for full coverage (defense in depth).",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/compliance/anssi/bp039_phase_c.go",
	}
}

// Doc returns catalog metadata for BP039CredGuardNoUEFILockDetector.
func (*BP039CredGuardNoUEFILockDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI BP-039 R14 — Credential Guard enabled without UEFI lock",
		Description: "ANSSI BP-039 R14 requires Credential Guard to be activated with UEFI lock (LsaCfgFlags=2). Current GPOs set LsaCfgFlags to 1 (enabled, no lock), allowing a local admin to disable the protection from the OS at next reboot.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/bp039_phase_c.go",
	}
}

// Doc returns catalog metadata for BP039HVCINoUEFILockDetector.
func (*BP039HVCINoUEFILockDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI BP-039 R9 — HVCI enabled without UEFI lock",
		Description: "ANSSI BP-039 R9 requires HVCI to be deployed with UEFI lock. Current GPOs enable HVCI (=1) but no GPO sets it to 2 (with UEFI lock), so a local administrator can disable HVCI from the OS without UEFI access.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/compliance/anssi/bp039_phase_c.go",
	}
}

// Doc returns catalog metadata for BP039HVCIOffDetector.
func (*BP039HVCIOffDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI BP-039 R8 — HVCI not enabled",
		Description: "ANSSI BP-039 R8 recommends enabling Hypervisor-Enforced Code Integrity (HVCI) on every compatible workstation. No GPO sets DeviceGuard\\HypervisorEnforcedCodeIntegrity, so kernel-mode integrity verification doesn't run inside the secure VBS partition.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/bp039_phase_c.go",
	}
}

// Doc returns catalog metadata for BP039PrivAccountsCachedDetector.
func (*BP039PrivAccountsCachedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI BP-039 R13 — AD privileged accounts cached on workstations",
		Description: "",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/bp039_phase_c.go",
	}
}

// Doc returns catalog metadata for BP039VBSOffDetector.
func (*BP039VBSOffDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI BP-039 R5 — VBS not enabled domain-wide",
		Description: "ANSSI BP-039 R5 recommends enabling Virtualization-Based Security (VBS) on every compatible workstation. No GPO sets DeviceGuard\\EnableVirtualizationBasedSecurity to 1, so HVCI / Credential Guard / Code Integrity isolation cannot benefit from hypervisor-enforced protections.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/bp039_phase_c.go",
	}
}

// Doc returns catalog metadata for M12DefaultAdminNotRenamedDetector.
func (*M12DefaultAdminNotRenamedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI Guide M12 — Built-in Administrator account is not renamed",
		Description: "The RID-500 built-in Administrator account still carries its default name (\"\"). ANSSI Guide d'hygiène M12 recommends changing default authentication elements: a known-constant account name lowers the cost of password spraying and credential-stuffing attacks against the most privileged on-prem identity.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/m12_default_admin.go",
	}
}

// Doc returns catalog metadata for M29LocalAdminNotRestrictedDetector.
func (*M29LocalAdminNotRestrictedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI Guide M29 — No GPO restricts local Administrators",
		Description: "ANSSI Guide d'hygiène M29 requires limiting local-administrator rights on workstations to strict operational need. None of the %d parsed GPO(s) defines a [Group Membership] / Restricted Groups entry pinning BUILTIN\\Administrators (SID %s) to a specific member set. Without it, any privileged user who logs in interactively can persist as a local admin via classic abuse paths.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/m29_local_admin.go",
	}
}

// Doc returns catalog metadata for PA038NetSessionHardeningDetector.
func (*PA038NetSessionHardeningDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-038 — NetCease : énumération des sessions réseau non restreinte",
		Description: "ANSSI PA-038 recommends applying NetCease (SrvsvcSessionInfo DACL restriction) to prevent unprivileged users from enumerating active SMB sessions via NetSessionEnum, which is used by BloodHound/SharpHound for user-to-host mapping.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/pa038_windows_hardening.go",
	}
}

// Doc returns catalog metadata for PA038PSModuleLoggingDetector.
func (*PA038PSModuleLoggingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-038 — PowerShell : Module Logging désactivé",
		Description: "ANSSI PA-038 requires PowerShell Module Logging (EventID 4103) to record pipeline execution details per module. Complements Script Block Logging for full command visibility.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/pa038_windows_hardening.go",
	}
}

// Doc returns catalog metadata for PA038PSScriptBlockDetector.
func (*PA038PSScriptBlockDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-038 — PowerShell : Script Block Logging désactivé",
		Description: "ANSSI PA-038 requires PowerShell Script Block Logging (EventID 4104) to detect obfuscated/malicious scripts executed in memory. Without it, PowerShell-based attacks (Empire, Cobalt Strike) leave no forensic trail.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/pa038_windows_hardening.go",
	}
}

// Doc returns catalog metadata for PA038PSTranscriptionDetector.
func (*PA038PSTranscriptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-038 — PowerShell : Transcription non activée",
		Description: "ANSSI PA-038 recommends PowerShell Transcription (EnableTranscripting=1) to write full session I/O to a central log path. Provides forensic audit trail for interactive PS sessions.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/compliance/anssi/pa038_windows_hardening.go",
	}
}

// Doc returns catalog metadata for PA038PointAndPrintDetector.
func (*PA038PointAndPrintDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-038 — Point and Print : élévation non requise (PrintNightmare)",
		Description: "ANSSI PA-038 requires Point and Print restrictions to enforce elevation (NoWarningNoElevationOnInstall=0). CVE-2021-34527 (PrintNightmare) exploits this to install malicious printer drivers as SYSTEM.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/pa038_windows_hardening.go",
	}
}

// Doc returns catalog metadata for PA038RDPNLADetector.
func (*PA038RDPNLADetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-038 — RDP : NLA (Network Level Authentication) non requis",
		Description: "ANSSI PA-038 requires NLA for all RDP connections (HKLM\\...\\Terminal Services\\UserAuthentication=1). Without NLA, the Windows login screen is exposed before authentication, enabling DoS and pre-auth exploits.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/pa038_windows_hardening.go",
	}
}

// Doc returns catalog metadata for PA038RDPSecurityLayerDetector.
func (*PA038RDPSecurityLayerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-038 — RDP : couche de sécurité inférieure à TLS (SSL)",
		Description: "ANSSI PA-038 requires RDP security layer = 2 (TLS/SSL). Values 0 (RDP native) and 1 (negotiate) allow downgrade attacks and weaker encryption.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/pa038_windows_hardening.go",
	}
}

// Doc returns catalog metadata for PA038WSUSDetector.
func (*PA038WSUSDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-038 — WSUS non configuré (mises à jour Windows non centralisées)",
		Description: "ANSSI PA-038 requires centralized patch management. No GPO configures a WUServer (WSUS/MECM endpoint), meaning workstations may pull updates directly from Microsoft or not at all, making patch status unverifiable.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/compliance/anssi/pa038_windows_hardening.go",
	}
}

// Doc returns catalog metadata for R121ForcePwdResetDetector.
func (*R121ForcePwdResetDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R12.1 — User-Force-Change-Password accordé hors comptes système",
		Description: "ANSSI R12.1 (sub-reco) — the extended right User-Force-Change-Password lets the holder reset arbitrary user passwords without knowing the old one. Should be restricted to Tier 0 admin groups only.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/sub_recos.go",
	}
}

// Doc returns catalog metadata for R122UserRestrictionsDetector.
func (*R122UserRestrictionsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R12.2 — User-Account-Restrictions accordé hors comptes système",
		Description: "ANSSI R12.2 (sub-reco) — the User-Account-Restrictions property set lets the holder modify userAccountControl bits (disable, no-preauth, smartcard required, etc.). Should be restricted to Tier 0 admins only.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/sub_recos.go",
	}
}

// Doc returns catalog metadata for R14RBCDAuditDetector.
func (*R14RBCDAuditDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R14 — RBCD configuré sans audit",
		Description: "ANSSI R14 requires explicit audit trail for every msDS-AllowedToActOnBehalfOfOtherIdentity value. Orphan RBCDs are a privilege-escalation vector.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r6_to_r15_lifecycle.go",
	}
}

// Doc returns catalog metadata for R151RODCNoAllowedReplDetector.
func (*R151RODCNoAllowedReplDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R15.1 — RODC déployé mais 'Allowed RODC Password Replication Group' vide",
		Description: "ANSSI R15.1 (sub-reco) — when an RODC is deployed, the Allowed RODC Password Replication Group must define which accounts may have their hashes cached on the RODC. An empty group either means no caching (defeats RODC purpose) or that the security model is misunderstood.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/sub_recos.go",
	}
}

// Doc returns catalog metadata for R152T0AdminInRODCDetector.
func (*R152T0AdminInRODCDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R15.2 — Admins T0 présents dans 'Allowed RODC Password Replication Group'",
		Description: "ANSSI R15.2 (sub-reco) — Tier 0 administrators (Domain/Enterprise/Schema Admins) MUST NEVER be in the Allowed RODC Password Replication Group. Their hash on a physically-exposed RODC = instant golden ticket on RODC theft.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/compliance/anssi/sub_recos.go",
	}
}

// Doc returns catalog metadata for R15FunctionalLevelDetector.
func (*R15FunctionalLevelDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R15 — AD functional level below recommended baseline",
		Description: "ANSSI R15 recommends raising AD functional levels to at least Windows Server 2016 (msDS-Behavior-Version=7) so that modern hardening features (KDC armoring at forest scope, authentication policies, full Protected Users effect) become available. Current state: .",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r15_r19_r40_tier0.go",
	}
}

// Doc returns catalog metadata for R15TierModelViolationDetector.
func (*R15TierModelViolationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R15 — Comptes admin hors OU dédiée (modèle en tiers)",
		Description: "ANSSI R15 enforces tier isolation: privileged accounts should live in dedicated OUs (e.g. OU=Tier0) with their own GPOs and ACLs, not in the default CN=Users container. Accounts in CN=Users break tier-aware GPO targeting.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r6_to_r15_lifecycle.go",
	}
}

// Doc returns catalog metadata for R18GPCOMinimalDetector.
func (*R18GPCOMinimalDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R18 — Group Policy Creator Owners contient des membres en excès",
		Description: "ANSSI R18 recommends keeping Group Policy Creator Owners restricted to the bare minimum. Members can create new GPOs that, once linked, can affect Tier 0 systems if cross-tier links exist.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r16_to_r27_privileges_crypto.go",
	}
}

// Doc returns catalog metadata for R19ServerCoreNotUsedDetector.
func (*R19ServerCoreNotUsedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R19+ — Domain Controllers do not run Windows Server Core",
		Description: "ANSSI R19+ (renforcement) recommends Windows Server Core on the Tier 0 perimeter to reduce the local attack surface (no MMC, no IE/Edge, fewer optional components). %d/%d DC(s) currently run a full GUI install.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/compliance/anssi/r15_r19_r40_tier0.go",
	}
}

// Doc returns catalog metadata for R1PasswordPolicyDetector.
func (*R1PasswordPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R1 - Password Policy Non-Compliant",
		Description: "Password policy does not meet ANSSI R1 recommendations. ANSSI requires minimum 12 characters, password history of 12, lockout threshold ≤5, and max age ≤90 days.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r1-password-policy.go",
	}
}

// Doc returns catalog metadata for R22GuestEnabledDetector.
func (*R22GuestEnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R2.2 — Compte Guest activé",
		Description: "ANSSI R2.2 (sub-reco) requires the built-in Guest account (RID 501) to be permanently disabled.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/sub_recos.go",
	}
}

// Doc returns catalog metadata for R23LMHashStorageDetector.
func (*R23LMHashStorageDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R23 — Stockage des hashes LM non désactivé",
		Description: "ANSSI R23 requires disabling LM hash storage (NoLMHash=1 or LmCompatibilityLevel>=5). LM hashes are trivially crackable and pre-computable.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r16_to_r27_privileges_crypto.go",
	}
}

// Doc returns catalog metadata for R27KerberosFASTArmoringDetector.
func (*R27KerberosFASTArmoringDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R27 — Kerberos FAST armoring non activé",
		Description: "ANSSI R27 recommends Kerberos FAST (Flexible Authentication Secure Tunneling, RFC 6113) to protect AS-REQ from offline cracking. Requires both DC-side (KDC\\SupportedEncryptionTypes/SupportedEtypes) and client-side (Kerberos\\Parameters\\RequireFast) enforcement.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r16_to_r27_privileges_crypto.go",
	}
}

// Doc returns catalog metadata for R28KrbtgtRotationDetector.
func (*R28KrbtgtRotationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R28 — krbtgt non roté (>180j)",
		Description: "",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/compliance/anssi/r28_to_r33_trusts.go",
	}
}

// Doc returns catalog metadata for R291ForestTrustNoSelAuthDetector.
func (*R291ForestTrustNoSelAuthDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R29.1 — Trust forêt sans Selective Authentication",
		Description: "ANSSI R29.1 (sub-reco of R29) explicitly requires forest trusts (not just external) to enable Selective Authentication.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/sub_recos.go",
	}
}

// Doc returns catalog metadata for R29TrustSIDFilteringDetector.
func (*R29TrustSIDFilteringDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R29 — Trust externe/forêt sans SID filtering",
		Description: "ANSSI R29 requires SID filtering (TRUST_ATTRIBUTE_QUARANTINED_DOMAIN) on every external or forest trust to prevent cross-domain SID injection escalation.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r28_to_r33_trusts.go",
	}
}

// Doc returns catalog metadata for R2PrivilegedAccountsDetector.
func (*R2PrivilegedAccountsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R2 - Privileged Accounts Non-Compliant",
		Description: "Privileged account management does not meet ANSSI R2 recommendations. Minimize DA accounts and separate service accounts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r2-privileged-accounts.go",
	}
}

// Doc returns catalog metadata for R30TrustSelectiveAuthDetector.
func (*R30TrustSelectiveAuthDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R30 — Trust externe/forêt sans Selective Authentication",
		Description: "ANSSI R30 requires Selective Authentication on cross-organization trusts so principals from the partner domain can only access resources where they're explicitly granted 'Allowed to authenticate'.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r28_to_r33_trusts.go",
	}
}

// Doc returns catalog metadata for R31ScriptSecretsDetector.
func (*R31ScriptSecretsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R31 — Reusable secrets found in SYSVOL scripts",
		Description: "ANSSI R31 requires that reusable authentication secrets are not embedded in scripts. The SYSVOL scanner found cleartext credential patterns inside one or more script files (.ps1/.bat/.cmd/.vbs/...). Replace hardcoded secrets with a vault, gMSA, or runtime prompt.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r31_script_secrets.go",
	}
}

// Doc returns catalog metadata for R31TrustTGTDelegationDetector.
func (*R31TrustTGTDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R31 — Trust forêt potentiellement permissif au TGT delegation",
		Description: "ANSSI R31 forbids TGT delegation across forest boundaries (TRUST_ATTRIBUTE_DISABLE_AUTH_TARGET_VALIDATION). Without selective auth, a forest trust enables TGT relay in many setups.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r28_to_r33_trusts.go",
	}
}

// Doc returns catalog metadata for R32TrustRC4Detector.
func (*R32TrustRC4Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R32 — Trust autorisant RC4 (pas AES-only)",
		Description: "ANSSI R32 requires AES-only on trust referrals (msDS-SupportedEncryptionTypes flag). RC4 cross-realm tickets are kerberoastable and downgrade attacks remain possible.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r28_to_r33_trusts.go",
	}
}

// Doc returns catalog metadata for R33ExternalTrustPermissiveDetector.
func (*R33ExternalTrustPermissiveDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R33 — Trust externe permissif (pas de selective auth + pas de SID filtering)",
		Description: "ANSSI R33 forbids permissive external trusts. An external trust without selective auth AND without SID filtering opens cross-domain privilege paths and SID injection.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r28_to_r33_trusts.go",
	}
}

// Doc returns catalog metadata for R342RestrictRemoteSAMDetector.
func (*R342RestrictRemoteSAMDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R34.2 — RestrictRemoteSAM non configuré",
		Description: "ANSSI R34.2 (sub-reco) — SAM\\RestrictRemoteSam must be set to a SDDL allowing only admins. Without it, any domain user can enumerate local accounts via SAMR (Mimikatz / netsesh).",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/sub_recos.go",
	}
}

// Doc returns catalog metadata for R361LAPSExpiryDetector.
func (*R361LAPSExpiryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R36.1 — LAPS password expiry > 30 days",
		Description: "ANSSI R36.1 (sub-reco) requires LAPS password rotations no more than 30 days apart. %d computer(s) currently have a LAPS expiry timestamp more than %d days in the future, indicating a rotation interval that's too long. Reduce the LAPS GPO PasswordAgeDays to 30 (or lower).",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/sub_recos.go",
	}
}

// Doc returns catalog metadata for R36CARisksDetector.
func (*R36CARisksDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R36 — Certificate authority risks affecting Tier 0",
		Description: ". ANSSI R36 requires addressing CA-level risks before they enable attackers to mint Tier 0 credentials. Renew expiring/SHA-1 CA certs, lock down CA ACLs, restrict risky templates (approval, remove ESC patterns).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/phase_d_detectors.go",
	}
}

// Doc returns catalog metadata for R37AppLockerHeuristicDetector.
func (*R37AppLockerHeuristicDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R37 — AppLocker / WDAC absent (heuristique GPO)",
		Description: "ANSSI R37 requires application allow-listing (AppLocker, WDAC, or equivalent). HEURISTIC ONLY: no GPO display name mentions AppLocker / WDAC / Code Integrity / SRP. The actual policy quality (XML rules) is not inspected by this detector.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r34_to_r39_hardening.go",
	}
}

// Doc returns catalog metadata for R37WeakCertTemplatesDetector.
func (*R37WeakCertTemplatesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R37 — Weak or abusable certificate templates",
		Description: "%d certificate template(s) usable for AD authentication carry weaknesses that can produce attacker-controlled or over-permissive Tier 0 certs (ESC1, AnyPurpose, weak ACL): %s. ANSSI R37 forbids weak/vulnerable Tier 0 certs — restrict EnrolleeSuppliesSubject, require manager approval for Smart Card Logon templates, and remove the AnyPurpose EKU from templates issued to privileged identities.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r37_weak_certs.go",
	}
}

// Doc returns catalog metadata for R38AdvancedAuditDetector.
func (*R38AdvancedAuditDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R38 — Advanced Audit Policy incomplet",
		Description: "ANSSI R38 requires the full Advanced Audit Policy (all 9 subcategories enabled for success+failure). Heuristic check on [Event Audit] coverage: at least one of Account Logon / Account Mgmt / DS Access / Logon Events / Object Access is missing.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r34_to_r39_hardening.go",
	}
}

// Doc returns catalog metadata for R39SecurityLogSizeDetector.
func (*R39SecurityLogSizeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R39 — Security event log < 1 GB",
		Description: "ANSSI R39 requires the Security event log to be at least 1 GB on Domain Controllers (default 20 MB rolls in seconds under heavy auth load, losing forensic evidence).",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r34_to_r39_hardening.go",
	}
}

// Doc returns catalog metadata for R3StrongAuthDetector.
func (*R3StrongAuthDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R3 - Strong Authentication Non-Compliant",
		Description: "Strong authentication not enforced per ANSSI R3. Privileged accounts should require smartcard authentication.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r3-strong-auth.go",
	}
}

// Doc returns catalog metadata for R40NoPSOTier0Detector.
func (*R40NoPSOTier0Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R40 — Tier 0 admin groups are not covered by a fine-grained password policy",
		Description: "ANSSI R40 requires applying stricter password policies (FGPP/PSO) to Tier 0 accounts than to regular users. None of the %d configured PSO(s) targets any of the %d Tier 0 group(s) or %d Tier 0 user(s) (recursive expansion + AdminSDHolder). Create one PSO with stricter length/age/lockout settings and apply it to Domain Admins, Enterprise Admins, Schema Admins and the other privileged groups (or directly to user accounts).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r15_r19_r40_tier0.go",
	}
}

// Doc returns catalog metadata for R42TrustPasswordOldDetector.
func (*R42TrustPasswordOldDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R42 — Trust password not recently rotated",
		Description: "ANSSI R42 requires monitoring renewal of trust account passwords. %d trust(s) have a pwdLastSet older than %d days. Windows updates inter-domain trust passwords every 30 days by default; a value past one year indicates broken automatic rotation, turning the trust account into a long-lived static credential.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r42_r43_password_rotation.go",
	}
}

// Doc returns catalog metadata for R43DCPasswordOldDetector.
func (*R43DCPasswordOldDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R43 — Domain Controller machine password not rotated",
		Description: "ANSSI R43 requires monitoring renewal of sensitive computer account passwords. %d/%d Domain Controller(s) have a machine password older than %d days. Most often this indicates a misconfigured GPO disabling automatic machine account password change (Netlogon\\DisablePasswordChange=1) or a stale clone DC.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r42_r43_password_rotation.go",
	}
}

// Doc returns catalog metadata for R49R50MgmtCategorizationDetector.
func (*R49R50MgmtCategorizationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R49+R50 — Management agents not categorized into a dedicated Tier OU",
		Description: "%d computer(s) match centralized-management heuristics (SCCM/WSUS/Defender/Intune/...) but live outside any Tier 0/Tier 1/admin OU. ANSSI R49 + R50 require categorization of management infrastructure: place these systems into a dedicated OU and apply the corresponding tier-segregated GPOs/ACLs.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/phase_d_detectors.go",
	}
}

// Doc returns catalog metadata for R4LoggingDetector.
func (*R4LoggingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R4 - Insufficient Logging Configuration",
		Description: "Logging configuration does not meet ANSSI R4 requirements. Critical audit categories must be enabled for Success and Failure.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r4-logging.go",
	}
}

// Doc returns catalog metadata for R59Tier0OUPoliciesDetector.
func (*R59Tier0OUPoliciesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R59 — Weak-ACL GPO linked to a Tier 0 OU",
		Description: "%d GPO link(s) attach a GPO with a weak ACL (writable by non-admins) to a Tier 0 OU: %s. ANSSI R59 requires restricting security policies applicable to Tier 0 OUs — a low-trust user with write access on a linked GPO can pivot to Tier 0 by editing the policy.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/compliance/anssi/phase_d_detectors.go",
	}
}

// Doc returns catalog metadata for R5SegregationDetector.
func (*R5SegregationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R5 - Segregation Non-Compliant",
		Description: "Privilege segregation does not meet ANSSI R5 recommendations. Separate admin roles and minimize privilege overlap.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r5-segregation.go",
	}
}

// Doc returns catalog metadata for R6InactiveAccountsDetector.
func (*R6InactiveAccountsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R6 — Comptes inactifs non désactivés",
		Description: "ANSSI R6 recommends disabling accounts inactive for more than 90 days to reduce the attack surface.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r6_to_r15_lifecycle.go",
	}
}

// Doc returns catalog metadata for R73NTLMOutboundTier0Detector.
func (*R73NTLMOutboundTier0Detector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R73 — Outbound NTLM traffic not blocked on Tier 0",
		Description: "ANSSI R73 requires Tier 0 systems (DCs, admin servers) to refuse outgoing NTLM authentication. No GPO sets Lsa\\MSV1_0\\RestrictSendingNTLMTraffic to 2 (Deny all). Without it, a compromised low-trust server can coerce a DC to NTLM-authenticate to it (PetitPotam, PrinterBug) and have its hash relayed.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/r73_r74_ntlm_outbound.go",
	}
}

// Doc returns catalog metadata for R74NTLMOutboundDomainDetector.
func (*R74NTLMOutboundDomainDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R74+ — Outbound NTLM traffic not blocked domain-wide",
		Description: "ANSSI R74+ (renforcement) extends R73 to ALL systems that can support it. No GPO with Lsa\\MSV1_0\\RestrictSendingNTLMTraffic=2 (Deny) is linked at the domain root, so most member servers/workstations still emit NTLM, sustaining the relay/coercion attack surface. Link the deny-NTLM-outbound GPO at the domain root (with appropriate exemption WMI filters for legacy systems).",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/compliance/anssi/r73_r74_ntlm_outbound.go",
	}
}

// Doc returns catalog metadata for R79RDPHardenedDetector.
func (*R79RDPHardenedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R79 — Remote Desktop client encryption not hardened",
		Description: "ANSSI R79 requires hardening remote connection clients. Missing GPO setting(s): . Without forced high encryption + RPC traffic encryption, RDP sessions remain attackable from a network position (downgrade attacks, MITM).",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/phase_d_detectors.go",
	}
}

// Doc returns catalog metadata for R7StaleAccountsNotRemovedDetector.
func (*R7StaleAccountsNotRemovedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R7 — Comptes stales (180j+) non supprimés",
		Description: "ANSSI R7 recommends deleting disabled accounts that haven't been used in 180+ days to reduce directory bloat and risk of unnoticed reactivation.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/compliance/anssi/r6_to_r15_lifecycle.go",
	}
}

// Doc returns catalog metadata for R82R83AdminArchitectureDetector.
func (*R82R83AdminArchitectureDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R82+R83 — Tier 0 systems do not deny low-trust account logons",
		Description: "ANSSI R82 + R83 require Tier 0 systems to refuse logon (network, interactive, RDP) from non-Tier-0 accounts (Domain Users, Authenticated Users, etc.). No GPO sets the corresponding deny privileges with such SIDs: . Add these SIDs to SeDeny*Right via Group Policy on the Tier 0 OU.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/phase_d_detectors.go",
	}
}

// Doc returns catalog metadata for R86AdminForestSegregationDetector.
func (*R86AdminForestSegregationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R86 — Administration forest trust not properly segregated",
		Description: "%d trust(s) target what looks like an administration forest (name contains %s) but lack SID filtering and/or selective authentication. ANSSI R86 requires segregation of any administration forest deployed: enable SID filtering (quarantine) AND selective authentication on the trust, otherwise the admin forest's privileged accounts are not properly isolated from the production forest.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/anssi/phase_d_detectors.go",
	}
}

// Doc returns catalog metadata for R8ServiceAccountsAsUsersDetector.
func (*R8ServiceAccountsAsUsersDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R8 — Comptes de service indistincts des comptes nominatifs",
		Description: "ANSSI R8 requires service accounts to be clearly separated from nominative accounts (no mailbox, no HR attributes). Shared hybrids hide privilege and muddy audit trails.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r6_to_r15_lifecycle.go",
	}
}

// Doc returns catalog metadata for R9ServiceAccountSecretRotationDetector.
func (*R9ServiceAccountSecretRotationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ANSSI R9 — Secrets comptes de service non rotés (>1 an)",
		Description: "ANSSI R9 recommends rotating service account credentials at least annually (preferably via gMSA). Long-lived static secrets are a persistent credential-theft target.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/anssi/r6_to_r15_lifecycle.go",
	}
}
