// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package security

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for GuestInSecurityGroupDetector.
func (*GuestInSecurityGroupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Guest Users in Security Groups",
		Description: "External guest users are members of security groups, potentially gaining access to internal resources.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/groups/security/guest-in-security-group.go",
	}
}

// Doc returns catalog metadata for NoOwnerDetector.
func (*NoOwnerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Groups Without Owners",
		Description: "Groups without a designated owner cannot be properly governed: no one is accountable for reviewing membership or deciding whether the group is still needed. Groups synced from on-premises Active Directory are excluded - their governance lives in the source directory, not Entra.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/groups/security/group-no-owner.go",
	}
}

// Doc returns catalog metadata for OrphanedGroupsDetector.
func (*OrphanedGroupsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Empty Groups (No Members)",
		Description: "Groups with no members (and, where collected, no membership in any other group) may be abandoned. Distinct from ownerless groups - see AZ_GROUP_NO_OWNER for groups missing an owner.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/groups/security/group-orphaned.go",
	}
}

// Doc returns catalog metadata for OwnerIsGuestDetector.
func (*OwnerIsGuestDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Groups Owned by Guest Users",
		Description: "At least one owner of this group is an external guest account (userType 'Guest', cross-referenced against collected user data), meaning the group can be managed from outside the organization. Owners whose userType could not be resolved are not counted either way, rather than guessed from their UPN.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/groups/security/group-owner-is-guest.go",
	}
}

// Doc returns catalog metadata for PublicMembershipDetector.
func (*PublicMembershipDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Groups with Public Membership",
		Description: "Groups allowing any user to join without approval increase risk of unauthorized access.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/groups/security/group-public-membership.go",
	}
}

// Doc returns catalog metadata for SelfServiceUnrestrictedDetector.
func (*SelfServiceUnrestrictedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Self-Service Group Management Unrestricted",
		Description: "Users can create groups without restrictions, leading to sprawl and shadow IT.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/groups/security/self-service-unrestricted.go",
	}
}

// Doc returns catalog metadata for UnifiedGroupNoExpiryDetector.
func (*UnifiedGroupNoExpiryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Microsoft 365 Groups Without Expiry",
		Description: "M365 groups without expiration policy may accumulate unused groups over time.",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/groups/security/unified-group-no-expiry.go",
	}
}
