// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package security

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for GuestInSecurityGroupDetector.
func (*GuestInSecurityGroupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Guest Users in Security Groups",
		Description: "External guest users are members of security groups, potentially gaining access to internal resources.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/groups/security/guest-in-security-group.go",
	}
}

// Doc returns catalog metadata for NoOwnerDetector.
func (*NoOwnerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Groups Without Owners",
		Description: "Groups without designated owners cannot be properly governed.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/groups/security/group-no-owner.go",
	}
}

// Doc returns catalog metadata for OrphanedGroupsDetector.
func (*OrphanedGroupsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Orphaned Groups",
		Description: "Groups with no members and no membership in other groups may be abandoned.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/groups/security/group-orphaned.go",
	}
}

// Doc returns catalog metadata for OwnerIsGuestDetector.
func (*OwnerIsGuestDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Groups Owned by Guest Users",
		Description: "Groups owned by external guest users may be managed outside organizational control.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/groups/security/group-owner-is-guest.go",
	}
}

// Doc returns catalog metadata for PublicMembershipDetector.
func (*PublicMembershipDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Groups with Public Membership",
		Description: "Groups allowing any user to join without approval increase risk of unauthorized access.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/groups/security/group-public-membership.go",
	}
}

// Doc returns catalog metadata for SelfServiceUnrestrictedDetector.
func (*SelfServiceUnrestrictedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Self-Service Group Management Unrestricted",
		Description: "Users can create groups without restrictions, leading to sprawl and shadow IT.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/groups/security/self-service-unrestricted.go",
	}
}

// Doc returns catalog metadata for UnifiedGroupNoExpiryDetector.
func (*UnifiedGroupNoExpiryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Microsoft 365 Groups Without Expiry",
		Description: "M365 groups without expiration policy may accumulate unused groups over time.",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/groups/security/unified-group-no-expiry.go",
	}
}
