// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package passwordpolicy

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for BannedPasswordsDetector.
func (*BannedPasswordsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Custom Banned Password List Not Configured",
		Description: "No custom banned password list is configured in Azure AD Password Protection.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/password-policy/custom-banned-passwords.go",
	}
}

// Doc returns catalog metadata for ExpirationDetector.
func (*ExpirationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Password Expiration Enabled",
		Description: "Password expiration is enabled. NIST 800-63B recommends against periodic password changes as they lead to weaker passwords.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/password-policy/password-expiration-enabled.go",
	}
}

// Doc returns catalog metadata for PasswordPolicyWeakDetector.
func (*PasswordPolicyWeakDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak Password Policy",
		Description: "Azure AD password policy may not enforce sufficient complexity. Consider Azure AD Password Protection.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/password-policy/password-policy-weak.go",
	}
}

// Doc returns catalog metadata for ProtectionDetector.
func (*ProtectionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Azure AD Password Protection Not Enabled",
		Description: "Azure AD Password Protection is not enabled. This feature blocks commonly used weak passwords.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/password-policy/password-protection-disabled.go",
	}
}
