// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package secrets

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AppCertExpiredDetector.
func (*AppCertExpiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications with Expired Certificates",
		Description: "Application certificates have expired. Remove expired certificates or rotate if still in use.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/secrets/app-cert-expired.go",
	}
}

// Doc returns catalog metadata for AppMultipleSecretsDetector.
func (*AppMultipleSecretsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications with Multiple Active Secrets",
		Description: "Applications with more than 2 password credentials active at the same time. Concurrently active secrets expand the credential attack surface and make it harder to track which one is actually in use. Keep only the secrets needed for an in-progress rotation and remove the rest.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/secrets/app-multiple-secrets.go",
	}
}

// Doc returns catalog metadata for AppNoCredentialRotationDetector.
func (*AppNoCredentialRotationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Credential Rotation in Over a Year",
		Description: "No password credential has been created for this application in the past 12 months, meaning secrets have not been rotated in over a year. Microsoft recommends rotating secrets more frequently than that (\"less than 12 months\"); it does not publish a specific preferred cadence.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/secrets/app-no-credential-rotation.go",
	}
}

// Doc returns catalog metadata for AppSecretExpiredDetector.
func (*AppSecretExpiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications with Expired Secrets",
		Description: "Application credentials have expired. Expired secrets indicate abandoned or poorly maintained apps. Remove expired credentials or rotate if still in use.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/secrets/app-secret-expired.go",
	}
}

// Doc returns catalog metadata for AppSecretLongExpiryDetector.
func (*AppSecretLongExpiryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Application Secrets with Long Expiry",
		Description: "Application secrets configured to expire more than 6 months from now. Microsoft recommends secret lifetimes under 12 months; the 6-month threshold applied here is a stricter etc-collector best-practice repere, not itself a Microsoft-specified figure. Rotate to a shorter-lived secret and automate renewal.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/secrets/app-secret-long-expiry.go",
	}
}
