// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package secrets

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AppCertExpiredDetector.
func (*AppCertExpiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications with Expired Certificates",
		Description: "Application certificates have expired. Remove expired certificates or rotate if still in use.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/secrets/app-cert-expired.go",
	}
}

// Doc returns catalog metadata for AppMultipleSecretsDetector.
func (*AppMultipleSecretsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications with Multiple Active Secrets",
		Description: "Applications with more than 2 active password credentials. Multiple secrets suggest poor rotation. Remove unused credentials and implement proper rotation with max 2 active secrets.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/secrets/app-multiple-secrets.go",
	}
}

// Doc returns catalog metadata for AppNoCredentialRotationDetector.
func (*AppNoCredentialRotationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Credential Rotation",
		Description: "Application credentials created more than 1 year ago without newer replacements. Implement regular credential rotation (every 90-180 days).",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/secrets/app-no-credential-rotation.go",
	}
}

// Doc returns catalog metadata for AppSecretExpiredDetector.
func (*AppSecretExpiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications with Expired Secrets",
		Description: "Application credentials have expired. Expired secrets indicate abandoned or poorly maintained apps. Remove expired credentials or rotate if still in use.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/secrets/app-secret-expired.go",
	}
}

// Doc returns catalog metadata for AppSecretLongExpiryDetector.
func (*AppSecretLongExpiryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Application Secrets with Long Expiry",
		Description: "Application secrets with expiry > 2 years. Long-lived secrets increase risk if compromised. Configure secrets to expire within 90-180 days and implement rotation.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/secrets/app-secret-long-expiry.go",
	}
}
