// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package replication

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DcsyncCapableDetector.
func (*DcsyncCapableDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DCSync Capable",
		Description: "Account with DS-Replication-Get-Changes and DS-Replication-Get-Changes-All rights. Can extract all password hashes.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/replication/dcsync-capable.go",
	}
}

// Doc returns catalog metadata for DuplicateSpnDetector.
func (*DuplicateSpnDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Duplicate SPN",
		Description: "A Service Principal Name is registered on more than one account (compared case-insensitively, since SPNs are not case sensitive on Windows Server). Can cause Kerberos authentication failures against the wrong account. Count is the number of accounts (distinguished names) that hold a duplicated SPN, not the number of distinct duplicated SPN values - e.g. one SPN shared by two accounts yields Count=2.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/replication/duplicate-spn.go",
	}
}
