// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package replication

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DcsyncCapableDetector.
func (*DcsyncCapableDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "DCSync Capable",
		Description: "Account with DS-Replication-Get-Changes and DS-Replication-Get-Changes-All rights. Can extract all password hashes.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/replication/dcsync-capable.go",
	}
}

// Doc returns catalog metadata for DuplicateSpnDetector.
func (*DuplicateSpnDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Duplicate SPN",
		Description: "Service Principal Name registered multiple times. Can cause Kerberos authentication failures.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/replication/duplicate-spn.go",
	}
}
