// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package b2b

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for CrossTenantOpenDetector.
func (*CrossTenantOpenDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Cross-Tenant Access Open",
		Description: "No cross-tenant access restrictions configured. Any external tenant can collaborate.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/guest-external/b2b/b2b-cross-tenant-open.go",
	}
}

// Doc returns catalog metadata for DirectConnectEnabledDetector.
func (*DirectConnectEnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "B2B Direct Connect Enabled",
		Description: "B2B direct connect allows external users to access resources without being guests.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/guest-external/b2b/b2b-direct-connect-enabled.go",
	}
}

// Doc returns catalog metadata for InboundTrustAllDetector.
func (*InboundTrustAllDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Inbound Trust for All Organizations",
		Description: "Inbound B2B trust is configured for all organizations without restrictions.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/guest-external/b2b/b2b-inbound-trust-all.go",
	}
}

// Doc returns catalog metadata for OutboundUnrestrictedDetector.
func (*OutboundUnrestrictedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Outbound B2B Access Unrestricted",
		Description: "Users can collaborate with any external organization without restrictions.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/guest-external/b2b/b2b-outbound-unrestricted.go",
	}
}
