// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package legacyauth

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DeviceCodeDetector.
func (*DeviceCodeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Device Code Flow Not Blocked",
		Description: "No enabled Conditional Access policy blocks the device code authentication flow. This flow is commonly used in phishing attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/legacy-auth/device-code-flow-enabled.go",
	}
}

// Doc returns catalog metadata for LegacyAuthAllowedDetector.
func (*LegacyAuthAllowedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Legacy Authentication Protocols Allowed",
		Description: "No Conditional Access policy blocks legacy authentication protocols (POP, IMAP, SMTP). Legacy protocols cannot use MFA.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/identity/legacy-auth/legacy-auth-allowed.go",
	}
}

// Doc returns catalog metadata for NoCABlockDetector.
func (*NoCABlockDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Conditional Access Policy Blocks Legacy Auth",
		Description: "No Conditional Access policy explicitly blocks legacy authentication for all users.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/legacy-auth/legacy-auth-no-ca-block.go",
	}
}
