// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package sspr

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for MethodsWeakDetector.
func (*MethodsWeakDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak SSPR Authentication Methods",
		Description: "SSPR uses weak methods (security questions, SMS). Recommend app-based or FIDO2 methods.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/sspr/sspr-methods-weak.go",
	}
}

// Doc returns catalog metadata for NotRequiredAdminsDetector.
func (*NotRequiredAdminsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SSPR Not Required for Administrators",
		Description: "Admins are not subject to SSPR policy. Admin password resets should have stronger requirements.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/sspr/sspr-not-required-admins.go",
	}
}

// Doc returns catalog metadata for SsprNotEnabledDetector.
func (*SsprNotEnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Self-Service Password Reset Not Enabled",
		Description: "SSPR is not enabled for all users. Without SSPR, users must contact helpdesk for password resets.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/sspr/sspr-not-enabled.go",
	}
}
