// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package sspr

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for MethodsWeakDetector.
func (*MethodsWeakDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Weak SSPR Authentication Methods",
		Description: "SSPR uses weak methods (security questions, SMS) in the unified Authentication methods policy. Recommend app-based or FIDO2 methods. This reads the unified policy directly; on a tenant that has not completed migration to it (policyMigrationState != migrationComplete), the legacy SSPR policy governs instead and is not checked here.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/sspr/sspr-methods-weak.go",
	}
}

// Doc returns catalog metadata for NotRequiredAdminsDetector.
func (*NotRequiredAdminsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SSPR Not Required for Administrators",
		Description: "Some administrator accounts have never registered a self-service password reset method, so they cannot use SSPR even though Microsoft enables and enforces it for admins by default.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/sspr/sspr-not-required-admins.go",
	}
}

// Doc returns catalog metadata for SsprNotEnabledDetector.
func (*SsprNotEnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Self-Service Password Reset Not Enabled",
		Description: "SSPR is not enabled for all users. Without SSPR, users must contact helpdesk for password resets.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/identity/sspr/sspr-not-enabled.go",
	}
}
