// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package privileged

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AccountOperatorsDetector.
func (*AccountOperatorsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Account Operators Member",
		Description: "Users in Account Operators group. Can create/modify user accounts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/account-operators.go",
	}
}

// Doc returns catalog metadata for AccountOperatorsOnDisabledAccountDetector.
func (*AccountOperatorsOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Account Operators Member (Disabled Account)",
		Description: "Disabled users who are direct members of Account Operators cannot authenticate while disabled, so they cannot exercise the privilege. Membership is not removed by this state - it returns to full effect the instant the account is re-enabled. Remediation: remove the account from the group.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/privileged/account-operators-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for AdminNativeRecentLogonDetector.
func (*AdminNativeRecentLogonDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Built-in Administrator Account Used Recently",
		Description: "The native Administrator account (RID 500) was last used %d day(s) ago. This account should be reserved for break-glass scenarios. Routine use increases the risk of credential exposure.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/privileged/admin-native-recent-logon.go",
	}
}

// Doc returns catalog metadata for BackupOperatorsDetector.
func (*BackupOperatorsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Backup Operators Member",
		Description: "Active (non-disabled) real members of the Backup Operators group: users, nested groups, computers, and foreign security principals. Members can back up and restore all files on domain controllers regardless of the permissions protecting them, sign in interactively, log on as a batch job, and shut down the domain controller. Because they can replace any file - including OS files - on a domain controller, they are treated as service administrators with effective control comparable to Domain Admins, even though they cannot directly change server configuration or modify the membership of other administrative groups. A broad foreign security principal (e.g. Authenticated Users, Everyone) means the privilege is effectively unrestricted. Disabled user and computer members are reported separately by BACKUP_OPERATORS_MEMBER_ON_DISABLED_ACCOUNT.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/backup-operators.go",
	}
}

// Doc returns catalog metadata for BackupOperatorsOnDisabledAccountDetector.
func (*BackupOperatorsOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Backup Operators Member (Disabled Account)",
		Description: "Disabled users and computers that are direct members of Backup Operators cannot authenticate while disabled, so they cannot exercise the privilege. Membership is not removed by this state - it returns to full effect the instant the account is re-enabled. Remediation: remove the account from the group.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/privileged/backup-operators-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for DisabledAdminGroupDetector.
func (*DisabledAdminGroupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Disabled Account in Admin Group",
		Description: "Disabled user accounts still present in privileged groups. Should be removed immediately.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/disabled-admin-group.go",
	}
}

// Doc returns catalog metadata for DomainAdminDescriptionDetector.
func (*DomainAdminDescriptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Sensitive Terms in Description",
		Description: "User accounts with admin/privileged keywords in description field. Information disclosure.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/domain-admin-description.go",
	}
}

// Doc returns catalog metadata for DomainAdminInDescriptionOnDisabledAccountDetector.
func (*DomainAdminInDescriptionOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Sensitive Terms in Description - Disabled Accounts",
		Description: "Disabled user accounts with admin/privileged keywords in the description field. Not usable to target an active session today - UF_ACCOUNTDISABLE blocks authentication for this account across every protocol - but the description text remains readable on the object and would matter again if the account is re-enabled.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/privileged/domain-admin-description-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for ExpiredAdminGroupDetector.
func (*ExpiredAdminGroupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Expired Account in Admin Group",
		Description: "Expired user accounts still present in privileged groups. Should be removed immediately.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/expired-admin-group.go",
	}
}

// Doc returns catalog metadata for NotInProtectedUsersDetector.
func (*NotInProtectedUsersDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Accounts Not in Protected Users",
		Description: "Privileged accounts not in Protected Users group. Missing enhanced security protections (NTLM disabled, no Kerberos delegation, no credential caching).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/not-in-protected-users.go",
	}
}

// Doc returns catalog metadata for PrintOperatorsDetector.
func (*PrintOperatorsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Print Operators Member",
		Description: "Users in Print Operators group. Can load/unload device drivers, manage printers on domain controllers, sign in locally to domain controllers, and shut them down.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/print-operators.go",
	}
}

// Doc returns catalog metadata for PrintOperatorsOnDisabledAccountDetector.
func (*PrintOperatorsOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Print Operators Member (Disabled Account)",
		Description: "Disabled users who are direct members of Print Operators cannot authenticate while disabled, so they cannot exercise the privilege. Membership is not removed by this state - it returns to full effect the instant the account is re-enabled. Remediation: remove the account from the group.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/privileged/print-operators-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for PrivilegedAccountStaleDetector.
func (*PrivilegedAccountStaleDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Stale Privileged Accounts",
		Description: "Privileged accounts inactive for 90+ days. Dormant admin accounts increase attack surface.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/privileged/privileged-stale.go",
	}
}

// Doc returns catalog metadata for SensitiveDelegationDetector.
func (*SensitiveDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Sensitive Account with Delegation",
		Description: "Enabled privileged accounts (Domain Admins, Domain Controllers, Schema Admins, Enterprise Admins, Key Admins, Enterprise Key Admins, Administrators, Account Operators, Server Operators, Print Operators, Backup Operators) with unconstrained delegation. Extreme security risk.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/accounts/privileged/sensitive-delegation.go",
	}
}

// Doc returns catalog metadata for SensitiveDelegationOnDisabledAccountDetector.
func (*SensitiveDelegationOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Sensitive Account with Delegation (Disabled Account)",
		Description: "Disabled privileged accounts (Domain Admins, Domain Controllers, Schema Admins, Enterprise Admins, Key Admins, Enterprise Key Admins, Administrators, Account Operators, Server Operators, Print Operators, Backup Operators) with unconstrained delegation are not exploitable while disabled. Two separate refusals apply: the account cannot obtain a ticket-granting ticket of its own, which closes the delegation-origin role, and the KDC will not issue a service ticket for its SPN, which closes the delegation-target role. The configuration remains set, and both roles become exploitable again against a privileged account the instant it is re-enabled. Remediation: remove the delegation bit or delete the account.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/privileged/sensitive-delegation-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for ServerOperatorsDetector.
func (*ServerOperatorsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Server Operators Member",
		Description: "Active (non-disabled) real members of the Server Operators group: users, nested groups, computers, and foreign security principals. Members can sign in interactively to domain controllers, create and delete shared resources, stop and start services, back up and restore files, format the hard disk, and shut down the domain controller. A broad foreign security principal (e.g. Authenticated Users, Everyone) means the privilege is effectively unrestricted. Disabled user and computer members are reported separately by SERVER_OPERATORS_MEMBER_ON_DISABLED_ACCOUNT.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/server-operators.go",
	}
}

// Doc returns catalog metadata for ServerOperatorsOnDisabledAccountDetector.
func (*ServerOperatorsOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Server Operators Member (Disabled Account)",
		Description: "Disabled users and computers that are direct members of Server Operators cannot authenticate while disabled, so they cannot exercise the privilege. Membership is not removed by this state - it returns to full effect the instant the account is re-enabled. Remediation: remove the account from the group.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/privileged/server-operators-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for SidHistoryDetector.
func (*SidHistoryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SID History Present",
		Description: "User accounts with sIDHistory attribute. Can be abused for privilege escalation.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/sid-history.go",
	}
}
