// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package privileged

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AccountOperatorsDetector.
func (*AccountOperatorsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Account Operators Member",
		Description: "Users in Account Operators group. Can create/modify user accounts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/account-operators.go",
	}
}

// Doc returns catalog metadata for AdminNativeRecentLogonDetector.
func (*AdminNativeRecentLogonDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Built-in Administrator Account Used Recently",
		Description: "The native Administrator account (RID 500) was last used %d day(s) ago. This account should be reserved for break-glass scenarios. Routine use increases the risk of credential exposure.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/privileged/admin-native-recent-logon.go",
	}
}

// Doc returns catalog metadata for BackupOperatorsDetector.
func (*BackupOperatorsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Backup Operators Member",
		Description: "Users in Backup Operators group. Can backup/restore files and bypass ACLs.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/backup-operators.go",
	}
}

// Doc returns catalog metadata for DisabledAdminGroupDetector.
func (*DisabledAdminGroupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Disabled Account in Admin Group",
		Description: "Disabled user accounts still present in privileged groups. Should be removed immediately.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/disabled-admin-group.go",
	}
}

// Doc returns catalog metadata for DomainAdminDescriptionDetector.
func (*DomainAdminDescriptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Sensitive Terms in Description",
		Description: "User accounts with admin/privileged keywords in description field. Information disclosure.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/domain-admin-description.go",
	}
}

// Doc returns catalog metadata for ExpiredAdminGroupDetector.
func (*ExpiredAdminGroupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Expired Account in Admin Group",
		Description: "Expired user accounts still present in privileged groups. Should be removed immediately.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/expired-admin-group.go",
	}
}

// Doc returns catalog metadata for NotInProtectedUsersDetector.
func (*NotInProtectedUsersDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Accounts Not in Protected Users",
		Description: "Privileged accounts not in Protected Users group. Missing enhanced security protections (NTLM disabled, no Kerberos delegation, no credential caching).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/not-in-protected-users.go",
	}
}

// Doc returns catalog metadata for PrintOperatorsDetector.
func (*PrintOperatorsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Print Operators Member",
		Description: "Users in Print Operators group. Can load drivers and manage printers on DCs.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/print-operators.go",
	}
}

// Doc returns catalog metadata for PrivilegedAccountStaleDetector.
func (*PrivilegedAccountStaleDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Stale Privileged Accounts",
		Description: "Privileged accounts inactive for 90+ days. Dormant admin accounts increase attack surface.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/privileged/privileged-stale.go",
	}
}

// Doc returns catalog metadata for SensitiveDelegationDetector.
func (*SensitiveDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Sensitive Account with Delegation",
		Description: "Privileged accounts (Domain/Enterprise Admins) with unconstrained delegation. Extreme security risk.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/accounts/privileged/sensitive-delegation.go",
	}
}

// Doc returns catalog metadata for ServerOperatorsDetector.
func (*ServerOperatorsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Server Operators Member",
		Description: "Users in Server Operators group. Can manage domain controllers.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/server-operators.go",
	}
}

// Doc returns catalog metadata for SidHistoryDetector.
func (*SidHistoryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SID History Present",
		Description: "User accounts with sIDHistory attribute. Can be abused for privilege escalation.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/privileged/sid-history.go",
	}
}
