// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package membership

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for UnresolvedPrivilegedMembersDetector.
func (*UnresolvedPrivilegedMembersDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged role assignment references an unresolved principal",
		Description: "One or more privileged role assignments reference a principal whose object could not be resolved (empty displayName, UPN, and mail after Graph enrichment). This often indicates stale assignments, deleted users still holding privileged roles, or hybrid identities that failed to sync from on-premises.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/privileged-access/membership/unresolved-members.go",
	}
}
