// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package gmsa

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for GMSAPasswordReadersDetector.
func (*GMSAPasswordReadersDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Non-privileged principal can read gMSA password",
		Description: "One or more Group Managed Service Accounts (gMSA) allow non-privileged principals to retrieve their managed password via msDS-GroupMSAMembership. Any reader of the password can impersonate the service account.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/groups/gmsa/gmsa-password-readers.go",
	}
}
