// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package signinevents

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AITMTokenReplayDetector.
func (*AITMTokenReplayDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Possible AITM Token Replay",
		Description: "The same sign-in correlation ID appeared from geographically distant IPs in a short time window.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/risk-protection/signin-events/detectors.go",
	}
}

// Doc returns catalog metadata for DeviceCodeFlowUsageDetector.
func (*DeviceCodeFlowUsageDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Device Code Flow Sign-In Usage",
		Description: "Device code flow was used for one or more user sign-ins. This flow is frequently abused for phishing.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/risk-protection/signin-events/detectors.go",
	}
}

// Doc returns catalog metadata for FailedSignInBurstDetector.
func (*FailedSignInBurstDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Failed Sign-In Burst",
		Description: "A burst of invalid-credential sign-in failures indicates targeted brute force or password spray activity.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/risk-protection/signin-events/detectors.go",
	}
}

// Doc returns catalog metadata for ImpossibleTravelDetector.
func (*ImpossibleTravelDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Impossible Travel Sign-In Pattern",
		Description: "A user signed in from distant countries too quickly for normal travel.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/risk-protection/signin-events/detectors.go",
	}
}

// Doc returns catalog metadata for LegacyAuthFromUserDetector.
func (*LegacyAuthFromUserDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Legacy Authentication Used by User",
		Description: "One or more users actually used legacy authentication protocols that cannot satisfy modern MFA controls.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/risk-protection/signin-events/detectors.go",
	}
}

// Doc returns catalog metadata for PushFatigueDetector.
func (*PushFatigueDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "MFA Push Fatigue Pattern",
		Description: "A user received many MFA push prompts in a short window with several failed or denied prompts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/risk-protection/signin-events/detectors.go",
	}
}

// Doc returns catalog metadata for SPSignInSpikeDetector.
func (*SPSignInSpikeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Principal Sign-In Spike",
		Description: "A service principal signed in far more often in the last 24 hours than over the preceding days of the collected window. A sudden rate change on a machine identity is a token-abuse or compromised-credential signal.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/risk-protection/signin-events/baseline_detectors.go",
	}
}

// Doc returns catalog metadata for UnusualGeoAdminDetector.
func (*UnusualGeoAdminDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Admin Sign-In From Unusual Country",
		Description: "A privileged account signed in successfully from a country it had not used earlier in the collected window. A new geography on an admin account is a common first sign of credential or token theft.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/risk-protection/signin-events/baseline_detectors.go",
	}
}
