// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package standards

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AccessReviewsNotConfiguredDetector.
func (*AccessReviewsNotConfiguredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Access Reviews Not Configured",
		Description: "No access review definitions found for guest users or privileged roles.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/compliance/standards/access-reviews-not-configured.go",
	}
}

// Doc returns catalog metadata for CISBenchmarkGapsDetector.
func (*CISBenchmarkGapsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "CIS Benchmark Compliance Gaps",
		Description: "Multiple CIS Azure AD benchmark recommendations are not implemented.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/compliance/standards/cis-benchmark-gaps.go",
	}
}

// Doc returns catalog metadata for EntitlementManagementDetector.
func (*EntitlementManagementDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Entitlement Management Not Used",
		Description: "No entitlement management access packages configured for access governance.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/compliance/standards/entitlement-management.go",
	}
}

// Doc returns catalog metadata for IdentityProtectionDisabledDetector.
func (*IdentityProtectionDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Identity Protection Not Configured",
		Description: "Azure AD Identity Protection risk policies are not configured.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/compliance/standards/identity-protection-disabled.go",
	}
}

// Doc returns catalog metadata for NoPrivacyStatementDetector.
func (*NoPrivacyStatementDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Privacy Statement Configured",
		Description: "Organization privacy statement URL is not configured in Azure AD.",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/compliance/standards/no-privacy-statement.go",
	}
}

// Doc returns catalog metadata for NoTermsOfUseDetector.
func (*NoTermsOfUseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Terms of Use Configured",
		Description: "No Terms of Use agreements configured (referenceable from Conditional Access policies).",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/compliance/standards/no-terms-of-use.go",
	}
}
