// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package security

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ACLAbuseDetector.
func (*ACLAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer ACL Abuse",
		Description: "Computer with dangerous ACL permissions. Can modify computer object properties and escalate privileges.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/security/acl-abuse.go",
	}
}

// Doc returns catalog metadata for ComputerStaleWithAdminGroupsDetector.
func (*ComputerStaleWithAdminGroupsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Stale Computers in Admin Groups",
		Description: "Computer accounts inactive 90+ days but in privileged groups. Highly unusual configuration.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/security/stale-admin.go",
	}
}

// Doc returns catalog metadata for DuplicateSpnDetector.
func (*DuplicateSpnDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Duplicate SPNs Detected",
		Description: "Multiple computers share the same Service Principal Name. This causes Kerberos authentication failures.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/security/duplicate-spn.go",
	}
}

// Doc returns catalog metadata for LegacyProtocolDetector.
func (*LegacyProtocolDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Legacy Operating System or Weak Kerberos Encryption",
		Description: "Computer runs an end-of-life Windows version that predates Microsoft disabling SMBv1 by default, or has no AES Kerberos encryption type enabled (DES/RC4 only, crackable offline). SMB dialect and NTLM version are not directly observed by this detector.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/security/legacy-protocol.go",
	}
}

// Doc returns catalog metadata for NoBitlockerDetector.
func (*NoBitlockerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Server BitLocker Status Not Verifiable From AD Metadata",
		Description: "Enabled server computer accounts for which this detector cannot confirm BitLocker status one way or the other - no BitLocker signal is read from AD for individual computers. Flagged for manual review only, not as a confirmed absence of encryption.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/computers/security/no-bitlocker.go",
	}
}

// Doc returns catalog metadata for NoLapsDetector.
func (*NoLapsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LAPS Not Deployed (Schema Not Extended)",
		Description: "LAPS schema is not extended in Active Directory. ALL local admin passwords are unmanaged and likely shared across computers.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/security/no-laps.go",
	}
}

// Doc returns catalog metadata for WeakEncryptionDetector.
func (*WeakEncryptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Weak Encryption",
		Description: "Computer with weak encryption types (DES/RC4 only). Vulnerable to Kerberos downgrade attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/security/weak-encryption.go",
	}
}

// Doc returns catalog metadata for WithSPNsDetector.
func (*WithSPNsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer with Service Principal Names",
		Description: "Computer account has Service Principal Names registered. Unlike user service accounts, computer account passwords are long, random, and automatically rotated by the domain, making offline Kerberoasting impractical against them - this is an inventory signal, not a confirmed attack path.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/computers/security/with-spns.go",
	}
}
