// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package security

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ACLAbuseDetector.
func (*ACLAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer ACL Abuse",
		Description: "Computer with dangerous ACL permissions. Can modify computer object properties and escalate privileges.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/security/acl-abuse.go",
	}
}

// Doc returns catalog metadata for ComputerStaleWithAdminGroupsDetector.
func (*ComputerStaleWithAdminGroupsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Stale Computers in Admin Groups",
		Description: "Computer accounts inactive 90+ days but in privileged groups. Highly unusual configuration.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/security/stale-admin.go",
	}
}

// Doc returns catalog metadata for DuplicateSpnDetector.
func (*DuplicateSpnDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Duplicate SPNs Detected",
		Description: "Multiple computers share the same Service Principal Name. This causes Kerberos authentication failures.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/security/duplicate-spn.go",
	}
}

// Doc returns catalog metadata for LegacyProtocolDetector.
func (*LegacyProtocolDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Legacy Protocol Support",
		Description: "Computers configured to use legacy protocols (SMBv1, NTLMv1, DES/RC4 only). These are vulnerable to relay attacks, credential theft, and encryption downgrade.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/security/legacy-protocol.go",
	}
}

// Doc returns catalog metadata for NoBitlockerDetector.
func (*NoBitlockerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "BitLocker Not Detected",
		Description: "Servers without BitLocker recovery information in AD. Unencrypted disks are vulnerable to physical theft and offline attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/security/no-bitlocker.go",
	}
}

// Doc returns catalog metadata for NoLapsDetector.
func (*NoLapsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LAPS Not Deployed (Schema Not Extended)",
		Description: "LAPS schema is not extended in Active Directory. ALL local admin passwords are unmanaged and likely shared across computers.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/security/no-laps.go",
	}
}

// Doc returns catalog metadata for SMBSigningDisabledDetector.
func (*SMBSigningDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer SMB Signing Disabled",
		Description: "Computer with SMB signing disabled. Vulnerable to SMB relay attacks (informational finding).",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/computers/security/smb-signing-disabled.go",
	}
}

// Doc returns catalog metadata for WeakEncryptionDetector.
func (*WeakEncryptionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer Weak Encryption",
		Description: "Computer with weak encryption types (DES/RC4 only). Vulnerable to Kerberos downgrade attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/security/weak-encryption.go",
	}
}

// Doc returns catalog metadata for WithSPNsDetector.
func (*WithSPNsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer with SPNs",
		Description: "Computer with Service Principal Names. Enables Kerberoasting attack against computer account.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/security/with-spns.go",
	}
}
