// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package computer

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for GenericAllDetector.
func (*GenericAllDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer ACL GenericAll",
		Description: "GenericAll permission on computer objects. Attacker with this permission can take over the computer, configure Resource-Based Constrained Delegation (RBCD), or extract credentials.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/permissions/computer/genericall.go",
	}
}
