// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package nesting

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for CircularNestingDetector.
func (*CircularNestingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Circular Group Nesting",
		Description: "Groups contain circular membership references. This can cause authentication issues and makes privilege analysis unreliable.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/groups/nesting/circular-nesting.go",
	}
}

// Doc returns catalog metadata for DangerousNestingDetector.
func (*DangerousNestingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Dangerous Group Nesting",
		Description: "Sensitive group nested in less sensitive group. Unintended privilege escalation path.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/groups/nesting/dangerous-nesting.go",
	}
}
