// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package adcs

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ADCSWeakPermissionsDetector.
func (*ADCSWeakPermissionsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ADCS Weak Permissions",
		Description: "Weak permissions on ADCS objects or certificate templates allow unauthorized enrollment.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/adcs/adcs-weak-permissions.go",
	}
}

// Doc returns catalog metadata for ESC1VulnerableTemplateDetector.
func (*ESC1VulnerableTemplateDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC1 Vulnerable Template",
		Description: "ADCS template with client auth + enrollee supplies subject. Enables domain compromise by obtaining cert for any user.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/adcs/esc1-vulnerable-template.go",
	}
}

// Doc returns catalog metadata for ESC2AnyPurposeDetector.
func (*ESC2AnyPurposeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC2 Any Purpose",
		Description: "ADCS template with Any Purpose EKU or no usage restriction. Certificate can be used for domain authentication.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/adcs/esc2-any-purpose.go",
	}
}

// Doc returns catalog metadata for ESC3EnrollmentAgentDetector.
func (*ESC3EnrollmentAgentDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC3 Enrollment Agent",
		Description: "ADCS template with enrollment agent EKU. Can request certificates on behalf of other users.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/adcs/esc3-enrollment-agent.go",
	}
}

// Doc returns catalog metadata for ESC4VulnerableTemplateACLDetector.
func (*ESC4VulnerableTemplateACLDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC4 Vulnerable Template ACL",
		Description: "Certificate template with weak ACLs. Can modify template to make it vulnerable to ESC1/ESC2.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/adcs/esc4-vulnerable-template-acl.go",
	}
}

// Doc returns catalog metadata for ESC6EditfDetector.
func (*ESC6EditfDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC6 EDITF Flag",
		Description: "ADCS CA with EDITF_ATTRIBUTESUBJECTALTNAME2 flag. Allows specifying arbitrary SAN in certificate requests.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/adcs/esc6-editf.go",
	}
}

// Doc returns catalog metadata for ESC8HttpEnrollmentDetector.
func (*ESC8HttpEnrollmentDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "ESC8 HTTP Enrollment",
		Description: "ADCS web enrollment via HTTP. Enables NTLM relay attacks against certificate enrollment.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/adcs/esc8-http-enrollment.go",
	}
}
