// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package cis

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for NetworkSecurityDetector.
func (*NetworkSecurityDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "CIS Network Security Non-Compliant",
		Description: "Network security settings do not meet CIS Benchmark requirements for SMB signing, LDAP signing, or LDAP channel binding.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/cis/network-security.go",
	}
}

// Doc returns catalog metadata for PasswordPolicyDetector.
func (*PasswordPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "CIS Password Policy Non-Compliant",
		Description: "Password policy does not meet CIS Benchmark requirements. CIS requires minimum 14 characters, 24 password history, max age 1-365 days (not 0), min age 1 day, and lockout threshold 1-5 (not 0).",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/cis/password-policy.go",
	}
}

// Doc returns catalog metadata for UserRightsDetector.
func (*UserRightsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "CIS User Rights Assignment Review",
		Description: "User rights assignments should follow CIS Benchmark recommendations: 'Act as part of the operating system' and 'Enable computer and user accounts to be trusted for delegation' should both be set to 'No One'.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/cis/user-rights.go",
	}
}
