// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package laps

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for LAPSDomainCoverageDetector.
func (*LAPSDomainCoverageDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LAPS Coverage Low (%.1f%%)",
		Description: "LAPS deployment coverage is %.1f%% across domain computers. Industry best practice recommends >95%% coverage.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/laps/laps-domain-coverage.go",
	}
}

// Doc returns catalog metadata for LapsLegacyAttributeDetector.
func (*LapsLegacyAttributeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LAPS Legacy Attribute",
		Description: "Legacy LAPS attribute used instead of Windows LAPS. Less secure implementation.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/laps/laps-legacy-attribute.go",
	}
}

// Doc returns catalog metadata for LapsNotDeployedDetector.
func (*LapsNotDeployedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LAPS Not Deployed (domain-wide)",
		Description: "No computer in the domain has a LAPS-managed local administrator password. Local admin credentials are shared or static across the estate, so one compromised machine yields lateral movement to all of them.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/advanced/laps/laps-not-deployed.go",
	}
}

// Doc returns catalog metadata for LapsPasswordLeakedDetector.
func (*LapsPasswordLeakedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LAPS Password Leaked",
		Description: "LAPS password visible to too many users. Reduces effectiveness of LAPS.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/advanced/laps/laps-password-leaked.go",
	}
}

// Doc returns catalog metadata for LapsPasswordReadableDetector.
func (*LapsPasswordReadableDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LAPS Password Readable",
		Description: "Non-admin users can read LAPS password attributes. Exposure of local admin passwords.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/advanced/laps/laps-password-readable.go",
	}
}

// Doc returns catalog metadata for LapsPasswordSetDetector.
func (*LapsPasswordSetDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "LAPS Password Set",
		Description: "LAPS password successfully managed. Informational - indicates proper LAPS deployment.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/advanced/laps/laps-password-set.go",
	}
}
