// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package detection

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for NoSignInRiskPolicyDetector.
func (*NoSignInRiskPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Sign-In Risk Policy",
		Description: "No CA policy uses sign-in risk conditions. Risk-based policies block compromised sign-ins.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/risk-protection/detection/no-signin-risk-policy.go",
	}
}

// Doc returns catalog metadata for NoUserRiskPolicyDetector.
func (*NoUserRiskPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No User Risk Policy",
		Description: "No CA policy uses user risk conditions. User risk policies force password change for compromised users.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/risk-protection/detection/no-user-risk-policy.go",
	}
}

// Doc returns catalog metadata for SignInRiskLowThresholdDetector.
func (*SignInRiskLowThresholdDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Sign-In Risk Threshold Too Low",
		Description: "Sign-in risk policies should trigger at medium risk or above, not just high.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/risk-protection/detection/signin-risk-low-threshold.go",
	}
}

// Doc returns catalog metadata for UserRiskLowThresholdDetector.
func (*UserRiskLowThresholdDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "User Risk Threshold Too Low",
		Description: "User risk policies should trigger at medium risk or above.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/risk-protection/detection/user-risk-low-threshold.go",
	}
}
