// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package registrations

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AppImplicitGrantEnabledDetector.
func (*AppImplicitGrantEnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications with Implicit Grant Flow",
		Description: "Applications using OAuth implicit grant flow. Implicit flow exposes tokens in the URL fragment. Migrate to authorization code flow with PKCE for better security.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/registrations/app-implicit-grant-enabled.go",
	}
}

// Doc returns catalog metadata for AppMultiTenantDetector.
func (*AppMultiTenantDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Multi-Tenant Application Registrations",
		Description: "Applications accepting sign-ins from any Azure AD tenant. Review if multi-tenant access is needed. Restrict to single tenant unless multi-tenant access is required.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/registrations/app-multi-tenant.go",
	}
}

// Doc returns catalog metadata for AppNoOwnerDetector.
func (*AppNoOwnerDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications Without Owner",
		Description: "Application registrations without an assigned owner. Orphaned apps cannot be managed. Assign owners to these applications as orphaned applications pose security and compliance risks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/registrations/app-no-owner.go",
	}
}

// Doc returns catalog metadata for AppReplyURLHTTPDetector.
func (*AppReplyURLHTTPDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications with HTTP Reply URLs",
		Description: "Applications using non-HTTPS reply URLs. Tokens transmitted over HTTP can be intercepted. Use HTTPS for all production reply URLs to prevent token interception.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/registrations/app-reply-url-http.go",
	}
}

// Doc returns catalog metadata for AppReplyURLWildcardDetector.
func (*AppReplyURLWildcardDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Applications with Wildcard Reply URLs",
		Description: "Applications using wildcard reply URLs. Attackers can redirect tokens to malicious endpoints. Use explicit URLs for production applications.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/registrations/app-reply-url-wildcard.go",
	}
}

// Doc returns catalog metadata for AppUnused90DaysDetector.
func (*AppUnused90DaysDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Unused Application Registrations",
		Description: "Applications created more than 90 days ago that may not be actively used. Remove unused applications to reduce attack surface.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/applications/registrations/app-unused-90-days.go",
	}
}
