// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package mail

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ExternalForwardingDetector.
func (*ExternalForwardingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "External Mail Forwarding Enabled",
		Description: "Mailboxes with forwarding rules to external addresses. Auto-forwarding is a common data exfiltration technique.",
		Severity:    types.SeverityCritical,
		SourceFile:  "exchange/mail/external-forwarding.go",
	}
}

// Doc returns catalog metadata for MailboxDelegationDetector.
func (*MailboxDelegationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Excessive Mailbox Delegation",
		Description: "Mailboxes with broad delegation permissions. Excessive delegations may indicate privilege creep or misconfiguration.",
		Severity:    types.SeverityMedium,
		SourceFile:  "exchange/mail/mailbox-delegation.go",
	}
}
