// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package rodc

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for RODCPrivilegedCachingDetector.
func (*RODCPrivilegedCachingDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "RODC caches credentials for privileged principals",
		Description: "One or more Read-Only Domain Controllers have revealed (cached) credentials for principals in privileged groups. A compromise of the RODC would expose these credentials even though RODCs are designed to hold only non-sensitive passwords.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/computers/rodc/rodc-privileged-caching.go",
	}
}
