// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package pim

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for PIMLongActivationDetector.
func (*PIMLongActivationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Long PIM Activation Duration",
		Description: "PIM role activations allow durations longer than 8 hours. Shorter activation periods limit exposure window if credentials are compromised.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/privileged-access/pim/pim-long-activation.go",
	}
}

// Doc returns catalog metadata for PIMNoApprovalRequiredDetector.
func (*PIMNoApprovalRequiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PIM Activation Without Approval",
		Description: "PIM-eligible privileged roles can be activated without approval. Approval provides an additional security checkpoint for sensitive role activations.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/privileged-access/pim/pim-no-approval-required.go",
	}
}

// Doc returns catalog metadata for PIMNoJustificationDetector.
func (*PIMNoJustificationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PIM Activation Without Justification",
		Description: "PIM role activations don't require justification. Justification provides audit trail and accountability for privilege use.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/privileged-access/pim/pim-no-justification.go",
	}
}

// Doc returns catalog metadata for PIMNoMFAOnActivationDetector.
func (*PIMNoMFAOnActivationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PIM Activation Without MFA",
		Description: "PIM may not require MFA on role activation. MFA ensures identity verification before granting privileges. Review PIM role settings in Azure Portal to enable MFA requirement on activation for all privileged roles.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/privileged-access/pim/pim-no-mfa-activation.go",
	}
}

// Doc returns catalog metadata for PIMNotEnabledDetector.
func (*PIMNotEnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PIM Not Configured for Privileged Roles",
		Description: "Privileged Identity Management (PIM) not enabled for sensitive admin roles. All assignments are permanent with standing privileges.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/privileged-access/pim/pim-not-enabled.go",
	}
}
