// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package roles

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminNoCAPolicyDetector.
func (*AdminNoCAPolicyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No CA Policy for Administrative Roles",
		Description: "No Conditional Access policy specifically targets admin directory roles. Administrative roles should be protected by CA policies requiring MFA, compliant devices, and other security controls.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/privileged-access/roles/admin-no-ca-policy.go",
	}
}

// Doc returns catalog metadata for AdminStaleAccountDetector.
func (*AdminStaleAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Stale Administrative Accounts",
		Description: "Admin role assignments to users who haven't signed in for %d+ days. Found %d stale administrative assignments. Review and remove unused privileged access.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/privileged-access/roles/admin-stale-account.go",
	}
}

// Doc returns catalog metadata for CustomRoleExcessiveDetector.
func (*CustomRoleExcessiveDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Excessive Custom Directory Roles",
		Description: "Many custom directory roles defined (%d found). Custom roles add complexity and may have overly broad permissions. Review and consolidate where possible.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/privileged-access/roles/custom-role-excessive.go",
	}
}

// Doc returns catalog metadata for GlobalAdminNotMFADetector.
func (*GlobalAdminNotMFADetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Global Admins Without MFA Enforcement",
		Description: "No Conditional Access policy specifically requires MFA for Global Administrator role. Global Administrators should always be protected by MFA due to their extensive privileges.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/privileged-access/roles/global-admin-not-mfa.go",
	}
}

// Doc returns catalog metadata for GroupAssignedAdminDetector.
func (*GroupAssignedAdminDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Admin Role Assigned to Group",
		Description: "Administrative roles are assigned to groups. Found %d group admin assignments. Ensure group membership is tightly controlled and audited regularly.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/privileged-access/roles/group-assigned-admin.go",
	}
}

// Doc returns catalog metadata for PermanentAdminAssignmentsDetector.
func (*PermanentAdminAssignmentsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Permanent Administrative Role Assignments",
		Description: "Administrative roles are permanently assigned instead of using time-limited PIM eligible assignments. Found %d permanent administrative assignments. Use PIM to provide just-in-time access.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/privileged-access/roles/permanent-admin-assignments.go",
	}
}

// Doc returns catalog metadata for ServicePrincipalAdminDetector.
func (*ServicePrincipalAdminDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Service Principal with Admin Role",
		Description: "Service principals have administrative directory roles. Found %d service principal admin assignments. Compromised service principals provide persistent admin access and cannot use MFA.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/privileged-access/roles/service-principal-admin.go",
	}
}

// Doc returns catalog metadata for TooManyGlobalAdminsDetector.
func (*TooManyGlobalAdminsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Too Many Global Administrators",
		Description: "More than 5 users have Global Administrator role (%d found). Microsoft recommends fewer than 5 to minimize security risk.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/privileged-access/roles/too-many-global-admins.go",
	}
}

// Doc returns catalog metadata for UnusedAdminRoleDetector.
func (*UnusedAdminRoleDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Unused Administrative Roles",
		Description: "Active directory roles with no assignments. Found %d unused roles. Review if these roles are needed or can be disabled to reduce attack surface.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/privileged-access/roles/unused-admin-role.go",
	}
}

// Doc returns catalog metadata for thresholdRoleDetector.
func (*thresholdRoleDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Too Many %ss",
		Description: "",
		Severity:    types.SeverityInfo,
		SourceFile:  "azure/privileged-access/roles/too-many-privileged-roles.go",
	}
}
