// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package advanced

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminCountOrphanedDetector.
func (*AdminCountOrphanedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Orphaned AdminCount Flag",
		Description: "Active accounts with adminCount=1 that are not a DIRECT member - via memberOf or primary group - of any group AdminSDHolder/SDProp protects (Microsoft Learn, \"Appendix C: Protected Accounts and Groups in Active Directory\", https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-c--protected-accounts-and-groups-in-active-directory), and are not krbtgt or the built-in Administrator account (identified by RID, not name). May indicate a removed admin that still carries residual privileges, or intact SDProp protection. Limitation: membership reached through a NESTED group - a group that is itself a member of a protected group, or a primary group that is itself nested - is not resolved and can still produce a false positive here.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/advanced/admin-count-orphaned.go",
	}
}

// Doc returns catalog metadata for AdminCountOrphanedOnDisabledAccountDetector.
func (*AdminCountOrphanedOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Orphaned AdminCount Flag (Disabled Account)",
		Description: "Disabled accounts with adminCount=1 that are not a DIRECT member - via memberOf or primary group - of any group AdminSDHolder/SDProp protects (Microsoft Learn, \"Appendix C: Protected Accounts and Groups in Active Directory\", https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-c--protected-accounts-and-groups-in-active-directory), and are not krbtgt or the built-in Administrator account (identified by RID, not name). A disabled account cannot authenticate ([MS-KILE], \"Check Account Policy for Every TGT Request\", KDC_ERR_CLIENT_REVOKED), so any residual privilege here is currently dormant - but adminCount is not removed by disabling the account, and it returns to full relevance the instant the account is re-enabled. Limitation: membership reached through a NESTED group is not resolved and can still produce a false positive here.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/advanced/admin-count-orphaned-on-disabled-account.go",
	}
}

// Doc returns catalog metadata for AdminNoSmartcardDetector.
func (*AdminNoSmartcardDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Admin Account Without Smartcard Requirement",
		Description: "Privileged accounts can authenticate with passwords instead of smartcards. Passwords are more vulnerable to theft and phishing.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/advanced/admin-no-smartcard.go",
	}
}

// Doc returns catalog metadata for DangerousBuiltinMembershipDetector.
func (*DangerousBuiltinMembershipDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Dangerous Built-in Group Membership",
		Description: "User accounts with membership in overlooked but dangerous built-in groups. These groups grant elevated privileges that may allow privilege escalation.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/advanced/dangerous-builtin-membership.go",
	}
}

// Doc returns catalog metadata for LockedAccountAdminDetector.
func (*LockedAccountAdminDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Locked Administrative Account",
		Description: "Administrative accounts that are currently locked out. May indicate password spray attacks or compromised credential attempts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/advanced/locked-account-admin.go",
	}
}

// Doc returns catalog metadata for ReplicaDirectoryChangesDetector.
func (*ReplicaDirectoryChangesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Directory Replication Rights (DCSync)",
		Description: "Active accounts hold both the DS-Replication-Get-Changes and DS-Replication-Get-Changes-All extended rights - or an equivalent grant (GenericAll, or a CONTROL_ACCESS ACE with no ObjectType, which AD grants as every extended right) - on the domain root (Microsoft Learn, Win32 AD Schema reference, \"DS-Replication-Get-Changes[-All] extended right\"). Holding only one of the two rights cannot perform DCSync and is not reported. These accounts can extract all password hashes from the domain (DCSync). Limits: only user accounts are checked - computer accounts and groups holding the rights are not, and group membership is not expanded to the users inside; an ACE flagged inherit-only (applies only to descendants, not the domain root itself) is ignored; and an explicit ACCESS_DENIED ACE elsewhere in the same ACL is not evaluated against a separate grant.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/accounts/advanced/replica-directory-changes.go",
	}
}

// Doc returns catalog metadata for ReplicaDirectoryChangesOnDisabledAccountDetector.
func (*ReplicaDirectoryChangesOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Directory Replication Rights (DCSync) - Disabled Account",
		Description: "Disabled accounts hold both the DS-Replication-Get-Changes and DS-Replication-Get-Changes-All extended rights - or an equivalent grant (GenericAll, or a CONTROL_ACCESS ACE with no ObjectType, which AD grants as every extended right) - on the domain root (Microsoft Learn, Win32 AD Schema reference, \"DS-Replication-Get-Changes[-All] extended right\"). A disabled account cannot obtain a new ticket-granting ticket ([MS-KILE], \"Check Account Policy for Every TGT Request\", KDC_ERR_CLIENT_REVOKED); however [MS-KILE] does not revoke a ticket-granting ticket already issued before the account was disabled, and when POLICY_KERBEROS_VALIDATE_CLIENT is set, [MS-KILE] 3.3.5.7.1 (\"Check Account Policy for Every Session Ticket Request\") still has the account KDC re-check a ticket-granting ticket older than 20 minutes on every new service-ticket request and reject it once Disabled is true - so the residual window is bounded by the lifetime of service tickets already issued before that 20-minute re-check, not by the ticket-granting ticket's own lifetime. The grant itself is not removed by disabling the account, and it returns to full relevance the instant the account is re-enabled. Holding only one of the two rights cannot perform DCSync and is not reported. Limits: only user accounts are checked - computer accounts and groups holding the rights are not, and group membership is not expanded to the users inside; an ACE flagged inherit-only (applies only to descendants, not the domain root itself) is ignored; and an explicit ACCESS_DENIED ACE elsewhere in the same ACL is not evaluated against a separate grant.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/accounts/advanced/replica-directory-changes-on-disabled-account.go",
	}
}
