// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package advanced

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminCountOrphanedDetector.
func (*AdminCountOrphanedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Orphaned AdminCount Flag",
		Description: "Accounts with adminCount=1 but not in any privileged group. This may indicate removed admins that still have residual privileges or SDProp protection.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/advanced/admin-count-orphaned.go",
	}
}

// Doc returns catalog metadata for AdminNoSmartcardDetector.
func (*AdminNoSmartcardDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Admin Account Without Smartcard Requirement",
		Description: "Privileged accounts can authenticate with passwords instead of smartcards. Passwords are more vulnerable to theft and phishing.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/advanced/admin-no-smartcard.go",
	}
}

// Doc returns catalog metadata for DangerousBuiltinMembershipDetector.
func (*DangerousBuiltinMembershipDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Dangerous Built-in Group Membership",
		Description: "User accounts with membership in overlooked but dangerous built-in groups. These groups grant elevated privileges that may allow privilege escalation.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/accounts/advanced/dangerous-builtin-membership.go",
	}
}

// Doc returns catalog metadata for LockedAccountAdminDetector.
func (*LockedAccountAdminDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Locked Administrative Account",
		Description: "Administrative accounts that are currently locked out. May indicate password spray attacks or compromised credential attempts.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/accounts/advanced/locked-account-admin.go",
	}
}

// Doc returns catalog metadata for ReplicaDirectoryChangesDetector.
func (*ReplicaDirectoryChangesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Potential Directory Replication Rights",
		Description: "Accounts that may have directory replication rights (DCSync capability). These accounts can extract all password hashes from the domain.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/accounts/advanced/replica-directory-changes.go",
	}
}
