// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package membership

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DynamicRuleBroadDetector.
func (*DynamicRuleBroadDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Groups with Broad Dynamic Rules",
		Description: "Dynamic groups with broad membership rules may include unintended users.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/groups/membership/dynamic-rule-broad.go",
	}
}

// Doc returns catalog metadata for LargeMembershipDetector.
func (*LargeMembershipDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Groups with Large Membership",
		Description: "Groups with more than 500 members are difficult to manage and audit.",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/groups/membership/group-large-membership.go",
	}
}

// Doc returns catalog metadata for NestedPrivilegedDetector.
func (*NestedPrivilegedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Nested Groups with Privileged Access",
		Description: "Groups nested in other privileged groups create indirect privilege escalation paths.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/groups/membership/nested-privileged-access.go",
	}
}

// Doc returns catalog metadata for PrivilegedChangesDetector.
func (*PrivilegedChangesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privileged Groups Without Change Monitoring",
		Description: "Privileged group membership changes should be monitored and alerted.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/groups/membership/privileged-group-changes.go",
	}
}

// Doc returns catalog metadata for RoleAssignableDetector.
func (*RoleAssignableDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Role-Assignable Groups",
		Description: "Groups that can be assigned to directory roles require careful membership control.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/groups/membership/role-assignable-excessive.go",
	}
}
