// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package size

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ExcessiveMembersDetector.
func (*ExcessiveMembersDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Group with Excessive Members",
		Description: "Groups with more than 100 direct members. Large groups are difficult to audit and may grant unintended access.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/groups/size/excessive-members.go",
	}
}

// Doc returns catalog metadata for OversizedCriticalDetector.
func (*OversizedCriticalDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Oversized Group (Critical)",
		Description: "Groups with 500+ members. Management/audit difficulty, excessive privileges, performance issues.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/groups/size/oversized-critical.go",
	}
}

// Doc returns catalog metadata for OversizedDetector.
func (*OversizedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Oversized Group",
		Description: "Groups with 100-500 members. May indicate overly broad permissions.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/groups/size/oversized.go",
	}
}

// Doc returns catalog metadata for OversizedHighDetector.
func (*OversizedHighDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Oversized Group (High)",
		Description: "Groups with 200-500 members. Management difficulty and potential privilege creep.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/groups/size/oversized-high.go",
	}
}
