// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package credentials

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for RBCDAbuseDetector.
func (*RBCDAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "RBCD Abuse",
		Description: "Computers with msDS-AllowedToActOnBehalfOfOtherIdentity configured. This enables privilege escalation via resource-based constrained delegation attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/credentials/rbcd-abuse.go",
	}
}

// Doc returns catalog metadata for ShadowCredentialsDetector.
func (*ShadowCredentialsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Shadow Credentials",
		Description: "msDS-KeyCredentialLink attribute configured. Allows Kerberos authentication bypass by adding arbitrary public keys.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/credentials/shadow-credentials.go",
	}
}
