// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package credentials

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for RBCDAbuseDetector.
func (*RBCDAbuseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "RBCD Abuse",
		Description: "Computers with msDS-AllowedToActOnBehalfOfOtherIdentity configured. This enables privilege escalation via resource-based constrained delegation attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/credentials/rbcd-abuse.go",
	}
}

// Doc returns catalog metadata for ShadowCredentialsDetector.
func (*ShadowCredentialsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Shadow Credentials",
		Description: "msDS-KeyCredentialLink is configured on a user or computer account. This is the prerequisite for a Shadow Credentials attack (Kerberos PKINIT authentication as the account via an attacker-controlled key) - it is not proof of compromise: Windows Hello for Business legitimately populates this attribute on every enrolled device and user. Review each entry to confirm the key credential is expected.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/advanced/credentials/shadow-credentials.go",
	}
}
