// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package high

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for GpoToDADetector.
func (*GpoToDADetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "GPO Modification Path to Domain Admin",
		Description: "GPOs can be modified by non-admin users. If these GPOs apply to privileged users or DCs, attackers can achieve Domain Admin.",
		Severity:    types.SeverityCritical,
		SourceFile:  "ad/attack-paths/high/gpo-to-da.go",
	}
}
