// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package medium

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for TrustLateralDetector.
func (*TrustLateralDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Trust Relationship Enables Lateral Movement",
		Description: "Domain trusts configured without proper security controls (SID filtering, selective authentication). Compromising trusted domain can lead to this domain.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/attack-paths/medium/trust-lateral.go",
	}
}
