package saas

import "net"

// IsLoopbackHost reports whether host is a loopback-only bind address. Anything else
// — 0.0.0.0, a specific external IP, an empty string (net/http treats "" the same as
// "all interfaces") — is network-reachable and falls under B_136's TLS requirement.
// Exported: both StartEmbeddedGUI (this package) and runServer (cmd/etc-collector)
// need it to decide whether to log a plaintext-on-network warning.
func IsLoopbackHost(host string) bool {
	switch host {
	case "127.0.0.1", "localhost", "::1":
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}

// ResolveGUITLS arbitrates the admin GUI's transport security (B_136, T_060).
// Exported: called from both StartEmbeddedGUI (daemon mode) and runServer
// (cmd/etc-collector, standalone mode) — the two startup paths that serve this API.
//
// Two dimensions, kept explicit rather than conflated:
//   - WHAT interface is bound (loopback vs. anything else) is what decides whether
//     TLS is required at all. A self-signed HTTPS certificate on 0.0.0.0 isn't
//     automatically safer than plain HTTP on 127.0.0.1 — an unverified certificate
//     defends against passive network sniffing and nothing more, while loopback
//     traffic never leaves the host in the first place (anyone who can intercept it
//     already has code execution on the box, at which point TLS buys nothing). What a
//     self-signed cert on a non-loopback interface DOES fix: plain HTTP there sends
//     the admin token across whatever network reaches that interface, in the clear,
//     to any passive listener — that's the gap this closes.
//   - Whether TLS is ALREADY explicitly configured (real cert+key on disk, from
//     config.yaml or a previous run) vs. needs to be established automatically.
//
// Behaviour:
//   - host is loopback: enabled/certFile/keyFile pass through untouched, whatever
//     they already are.
//   - host is not loopback, TLS already configured (enabled + both files given):
//     pass through untouched — an operator-provided certificate always wins.
//   - host is not loopback, TLS not configured, allowInsecureHTTP is true: pass
//     through untouched (plain HTTP on the network) — the caller MUST log this
//     loudly; resolveGUITLS only decides, it doesn't have the request-specific
//     details (actual host/port) to put in that message.
//   - host is not loopback, TLS not configured, allowInsecureHTTP is false (the
//     default): a bootstrap self-signed certificate is generated on demand
//     (ensureSelfSignedCert — the same on-demand model as the JWT keypair) and TLS is
//     enabled. This is what protects the ALREADY-INSTALLED fleet from an outage: a
//     collector already running --gui-host 0.0.0.0 keeps running after an upgrade,
//     now serving HTTPS instead of plaintext, with no operator action required.
//
// Returns an error only when a bootstrap certificate is genuinely needed and could
// not be generated (e.g. a disk write failure) — this is the one case that should
// stop the server from starting at all: it can't offer the required protection level,
// and the operator hasn't explicitly opted out of it.
func ResolveGUITLS(host string, enabled bool, certFile, keyFile, certDir string, allowInsecureHTTP bool) (outEnabled bool, outCertFile, outKeyFile string, autoGenerated bool, err error) {
	if IsLoopbackHost(host) {
		return enabled, certFile, keyFile, false, nil
	}
	if enabled && certFile != "" && keyFile != "" {
		return enabled, certFile, keyFile, false, nil
	}
	if allowInsecureHTTP {
		return enabled, certFile, keyFile, false, nil
	}

	cert, key, genErr := ensureSelfSignedCert(certDir, host)
	if genErr != nil {
		return enabled, certFile, keyFile, false, genErr
	}
	return true, cert, key, true, nil
}
