// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package monitoring

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminAuditBypassDetector.
func (*AdminAuditBypassDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Administrators Can Bypass Audit",
		Description: "Privileged accounts not in Protected Users group with old passwords may bypass audit controls.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/monitoring/admin-audit-bypass.go",
	}
}

// Doc returns catalog metadata for AuditAccountMgmtDetector.
func (*AuditAccountMgmtDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Account Management Auditing Disabled",
		Description: "Account management events are not audited for Success and Failure, preventing detection of unauthorized account changes.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/monitoring/audit-account-mgmt.go",
	}
}

// Doc returns catalog metadata for AuditLogonEventsDetector.
func (*AuditLogonEventsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Logon Event Auditing Insufficient",
		Description: "Logon events are not fully audited. Both Account Logon and Logon/Logoff events should audit Success and Failure.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/monitoring/audit-logon-events.go",
	}
}

// Doc returns catalog metadata for AuditPolicyChangeDetector.
func (*AuditPolicyChangeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Policy Change Auditing Disabled",
		Description: "Policy change events are not audited, preventing detection of GPO poisoning and security policy tampering.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/monitoring/audit-policy-change.go",
	}
}

// Doc returns catalog metadata for AuditPrivilegeUseDetector.
func (*AuditPrivilegeUseDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Privilege Use Auditing Disabled",
		Description: "Privilege use events are not audited, preventing detection of privilege abuse and token manipulation.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/monitoring/audit-privilege-use.go",
	}
}

// Doc returns catalog metadata for DCAuditPolicyIncompleteDetector.
func (*DCAuditPolicyIncompleteDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Domain Controller Audit Policy Incomplete",
		Description: "The audit policy applied to Domain Controllers does not log both success and failure events for all critical security categories. Incomplete audit policies create blind spots that attackers exploit to operate undetected.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/monitoring/dc-audit-policy-incomplete.go",
	}
}

// Doc returns catalog metadata for HoneypotAccountsDetector.
func (*HoneypotAccountsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Honeypot/Decoy Accounts Detected",
		Description: "No honeypot or decoy accounts detected in the directory. These accounts help detect attackers during enumeration phase.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/monitoring/honeypot-accounts.go",
	}
}

// Doc returns catalog metadata for SecurityLogSizeDetector.
func (*SecurityLogSizeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Security Log Size Too Small",
		Description: "Security event log maximum size is below recommended 128 MB, risking loss of critical audit events.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/monitoring/security-log-size.go",
	}
}
