// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package pr001

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for PR001AdminHasNormalAccountDetector.
func (*PR001AdminHasNormalAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-022 R27 - Admins sans compte nominatif standard distinct",
		Description: "ANSSI PA-022 R27 requires every admin to have a dedicated account, separate from their daily user account. HEURISTIC, not a direct measurement: matched via EmployeeID overlap - admins whose EmployeeID isn't found on any non-admin enabled account are flagged. This cannot verify R27's 'different authentication secrets' requirement, and false positives are possible if EmployeeID is not populated organisation-wide.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/pr001/pr001.go",
	}
}

// Doc returns catalog metadata for PR001DCOSObsoleteDetector.
func (*PR001DCOSObsoleteDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PA-099 R16 - Domain Controller sur OS obsolète",
		Description: "ANSSI PA-099 R16 requires domain controller operating systems to be kept regularly up to date, moving to recent stable Windows Server versions. Windows Server 2000/2003/2008/2012 are fully out of support (no security patches at all, outside paid custom agreements). Windows Server 2016 is past mainstream support (ended January 2022) and, while it still receives free security updates under Extended Support until January 2027, no longer receives feature updates or the fastest security response - R16 asks for staying current, not merely avoiding full end-of-support.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/pr001/pr001.go",
	}
}
