// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package pr001

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for PR001AdminHasNormalAccountDetector.
func (*PR001AdminHasNormalAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PR-001 §3.3 — Admins sans compte nominatif standard distinct",
		Description: "ANSSI PR-001 §3.3 requires every admin to have a separate daily account. HEURISTIC: matched via EmployeeID — admins whose EmployeeID isn't found on any non-admin enabled account are flagged. False positives possible if EmployeeID is not populated organisation-wide.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/compliance/pr001/pr001.go",
	}
}

// Doc returns catalog metadata for PR001DCOSObsoleteDetector.
func (*PR001DCOSObsoleteDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "PR-001 §5.1 — Domain Controller sur OS obsolète",
		Description: "ANSSI PR-001 §5.1 requires DCs to run a supported OS. Windows Server 2003/2008/2012/2016 are out of mainstream support — security patches limited or non-existent.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/compliance/pr001/pr001.go",
	}
}
