// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package permissions

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AdminConsentNotRequiredDetector.
func (*AdminConsentNotRequiredDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Admin Consent Not Required for High-Privilege Permissions",
		Description: "Users can consent to application permissions without admin approval. Configure user consent settings to require admin approval for high-privilege permissions to prevent unauthorized app access.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/permissions/admin-consent-not-required.go",
	}
}

// Doc returns catalog metadata for ConsentGrantedTenantWideDetector.
func (*ConsentGrantedTenantWideDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Tenant-Wide Consent Grants",
		Description: "OAuth2 permissions granted for all users (tenant-wide consent). Review for excessive access. Consider granting permissions to specific users instead of all principals.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/permissions/consent-granted-tenant-wide.go",
	}
}

// Doc returns catalog metadata for DangerousPermissionDirDetector.
func (*DangerousPermissionDirDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "App with Dangerous Directory Permissions",
		Description: "Applications with Directory.ReadWrite.All can modify all directory objects. Use more specific permissions like User.ReadWrite.All or Group.ReadWrite.All.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/applications/permissions/dangerous-permission-dir.go",
	}
}

// Doc returns catalog metadata for DangerousPermissionFilesDetector.
func (*DangerousPermissionFilesDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "App with Dangerous File Permissions",
		Description: "Applications with Files.ReadWrite.All can access all users' OneDrive and SharePoint files. Limit scope to specific sites or use delegated permissions.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/applications/permissions/dangerous-permission-files.go",
	}
}

// Doc returns catalog metadata for DangerousPermissionMailDetector.
func (*DangerousPermissionMailDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "App with Dangerous Mail Permissions",
		Description: "Applications with Mail.ReadWrite or Mail.Read application permissions can access all mailboxes. Review these applications and use delegated permissions instead of application permissions where possible.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/applications/permissions/dangerous-permission-mail.go",
	}
}

// Doc returns catalog metadata for DangerousPermissionRoleDetector.
func (*DangerousPermissionRoleDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "App with Role Management Permissions",
		Description: "Applications with RoleManagement.ReadWrite.Directory can assign any directory role. This permission allows privilege escalation.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/applications/permissions/dangerous-permission-role.go",
	}
}

// Doc returns catalog metadata for ExcessiveDelegatedDetector.
func (*ExcessiveDelegatedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "App with Excessive Delegated Permissions",
		Description: "Applications with many delegated permission scopes granted tenant-wide. Apply principle of least privilege.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/applications/permissions/excessive-delegated.go",
	}
}

// Doc returns catalog metadata for UserConsentUnrestrictedDetector.
func (*UserConsentUnrestrictedDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "User Consent Unrestricted",
		Description: "Users can consent to any application requesting permissions. This enables consent phishing attacks. Disable user consent or restrict it to verified publishers and specific permissions to prevent consent phishing attacks.",
		Severity:    types.SeverityCritical,
		SourceFile:  "azure/applications/permissions/user-consent-unrestricted.go",
	}
}
