// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package trusts

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for AESDisabledDetector.
func (*AESDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "AES Encryption Disabled on Trust",
		Description: "Trust relationship does not support AES encryption. This forces the use of weaker encryption algorithms (RC4/DES) which are more vulnerable to offline cracking.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/trusts/aes-disabled.go",
	}
}

// Doc returns catalog metadata for BidirectionalDetector.
func (*BidirectionalDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Bidirectional Trust Relationship",
		Description: "Two-way trust allows authentication in both directions, increasing the attack surface. A compromise in either domain can lead to lateral movement to the other.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/trusts/bidirectional.go",
	}
}

// Doc returns catalog metadata for ExternalNoSelectiveAuthDetector.
func (*ExternalNoSelectiveAuthDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "External Trust Without Selective Authentication",
		Description: "External trust without selective authentication allows any user from the trusted domain to authenticate to any resource in this domain.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/trusts/external-no-selective-auth.go",
	}
}

// Doc returns catalog metadata for ForestTransitiveDetector.
func (*ForestTransitiveDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Transitive Forest Trust",
		Description: "Forest trust is transitive, meaning all domains in the trusted forest can access this domain. This significantly increases the trust boundary.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/trusts/forest-transitive.go",
	}
}

// Doc returns catalog metadata for InactiveDetector.
func (*InactiveDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Inactive Trust Relationship",
		Description: "Trust relationship has not been modified in over 180 days. May indicate an abandoned or forgotten trust that should be reviewed for necessity.",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/trusts/inactive.go",
	}
}

// Doc returns catalog metadata for RC4OnlyDetector.
func (*RC4OnlyDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Trust Only Supports RC4 Encryption",
		Description: "Trust relationship only supports RC4 encryption (no AES). RC4 is deprecated and Kerberos tickets encrypted with RC4 are vulnerable to offline cracking attacks.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/trusts/rc4-only.go",
	}
}

// Doc returns catalog metadata for SIDFilteringDisabledDetector.
func (*SIDFilteringDisabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SID Filtering Disabled on Trust",
		Description: "Trust relationships without SID filtering allow SID history injection attacks, enabling attackers to impersonate any user in the trusted domain.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/trusts/sid-filtering-disabled.go",
	}
}
