// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package authmethods

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for EmailOTPDetector.
func (*EmailOTPDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Email OTP Authentication Enabled",
		Description: "Email one-time password is enabled. If the email account is compromised, OTP codes are also compromised.",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/identity/auth-methods/auth-methods-email-otp.go",
	}
}

// Doc returns catalog metadata for NoRegistrationDetector.
func (*NoRegistrationDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Authentication Method Registration Campaign",
		Description: "Registration enforcement is not enabled. Users are not prompted to register strong authentication methods.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/auth-methods/no-registration-campaign.go",
	}
}

// Doc returns catalog metadata for SmsEnabledDetector.
func (*SmsEnabledDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "SMS Authentication Method Enabled",
		Description: "SMS is enabled as an authentication method. SMS codes can be intercepted via SIM-swapping attacks.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/auth-methods/auth-methods-sms-enabled.go",
	}
}

// Doc returns catalog metadata for VoiceDetector.
func (*VoiceDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Voice Call Authentication Enabled",
		Description: "Voice call is enabled as an authentication method. Voice calls can be forwarded or intercepted.",
		Severity:    types.SeverityLow,
		SourceFile:  "azure/identity/auth-methods/auth-methods-voice-enabled.go",
	}
}

// Doc returns catalog metadata for WeakDefaultDetector.
func (*WeakDefaultDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Only Weak Authentication Methods Enabled",
		Description: "SMS or voice is enabled while Microsoft Authenticator and FIDO2 are both disabled, leaving no stronger method for users to register or fall back to. This does not observe an actual per-user default sign-in method - Microsoft Graph's authentication methods policy has no such setting to check.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/identity/auth-methods/weak-default-method.go",
	}
}
