// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package exclusions

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for ExcessiveExclusionsDetector.
func (*ExcessiveExclusionsDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "CA Policies with Excessive Exclusions",
		Description: "CA policies with many user/group exclusions weaken security coverage.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/conditional-access/exclusions/ca-excessive-exclusions.go",
	}
}

// Doc returns catalog metadata for GroupExclusionLargeDetector.
func (*GroupExclusionLargeDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "CA Policies with Large Group Exclusions",
		Description: "CA policies exclude groups that may contain many members, reducing policy effectiveness.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/conditional-access/exclusions/ca-group-exclusion-large.go",
	}
}

// Doc returns catalog metadata for NoBreakGlassExclusionDetector.
func (*NoBreakGlassExclusionDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "No Break-Glass Account Exclusion Pattern",
		Description: "CA policies targeting all users should exclude emergency access (break-glass) accounts to prevent lockout.",
		Severity:    types.SeverityHigh,
		SourceFile:  "azure/conditional-access/exclusions/ca-no-break-glass-exclusion.go",
	}
}

// Doc returns catalog metadata for UserExclusionsStaleDetector.
func (*UserExclusionsStaleDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "CA Policies with User-Level Exclusions",
		Description: "CA policies exclude individual users instead of groups. User exclusions are harder to manage and audit.",
		Severity:    types.SeverityMedium,
		SourceFile:  "azure/conditional-access/exclusions/ca-user-exclusions-stale.go",
	}
}
