// Code generated by tools/cataloggen; DO NOT EDIT.
// Run `go generate ./...` (or `go run ./tools/cataloggen`) to regenerate.

package organization

import (
	"github.com/etcsec-com/etc-collector/internal/audit"
	"github.com/etcsec-com/etc-collector/pkg/types"
)

// Doc returns catalog metadata for DCNotInDCOUDetector.
func (*DCNotInDCOUDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Domain Controller Not in Domain Controllers OU",
		Description: "Domain Controllers found outside the Domain Controllers OU. This may indicate misconfiguration or an attempt to hide a rogue DC.",
		Severity:    types.SeverityHigh,
		SourceFile:  "ad/computers/organization/dc-not-in-dc-ou.go",
	}
}

// Doc returns catalog metadata for DomainControllerInventoryDetector.
func (*DomainControllerInventoryDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Domain Controller",
		Description: "Inventory entry - exposes the DC as a first-class asset to the SaaS (FSMO roles, RODC flag, replication partners, site).",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/computers/organization/dc-inventory.go",
	}
}

// Doc returns catalog metadata for ServerNoAdminGroupDetector.
func (*ServerNoAdminGroupDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Server Without Managed Admin Group",
		Description: "Servers whose local Administrators group membership is not pinned by any GPO Restricted Groups / Group Policy Preferences setting. Local admin access can accumulate uncontrolled instead of being managed through a documented group (e.g. SRV01-Admins).",
		Severity:    types.SeverityMedium,
		SourceFile:  "ad/computers/organization/server-no-admin-group.go",
	}
}

// Doc returns catalog metadata for WorkstationInServerOuDetector.
func (*WorkstationInServerOuDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Workstation in Server OU",
		Description: "Workstation computers found in server OUs. This causes incorrect GPO application and may indicate organizational issues.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/computers/organization/workstation-in-server-ou.go",
	}
}

// Doc returns catalog metadata for WrongOuDetector.
func (*WrongOuDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer in Default Container",
		Description: "Computer in default Computers container instead of an organizational OU. May not receive proper Group Policy and indicates lack of organization.",
		Severity:    types.SeverityLow,
		SourceFile:  "ad/computers/organization/wrong-ou.go",
	}
}

// Doc returns catalog metadata for WrongOuOnDisabledAccountDetector.
func (*WrongOuOnDisabledAccountDetector) Doc() audit.DetectorDoc {
	return audit.DetectorDoc{
		Title:       "Computer in Default Container - Disabled Accounts",
		Description: "Disabled computer account in the default Computers container instead of an organizational OU. Group Policy no longer applies while the account is disabled, so this is organizational residue rather than a live policy gap - but it would resurface as a live concern if the account is re-enabled without being relocated first.",
		Severity:    types.SeverityInfo,
		SourceFile:  "ad/computers/organization/wrong-ou-on-disabled-account.go",
	}
}
